### PR TITLE
net-mgmt/zabbix-proxy/agent: Added preliminar support for 6.0

### PR DESCRIPTION
**Pull request by rmundel**
Hey guys, I'm trying to add zabbix proxy and agent 6.0 into the main plugin as the port already exists.

I'm stuck with two issues (maybe is my test setup):

- No log text shows in the *Log File* tab (although file permissions are ok, there's content inside)
- Zabbix Proxy 6.0 deprecated the ServerPort parameter. Now it must be specified with the host adress separated by ':' instead

### CODE REVIEW

**Comment by rmundel** [comment]
In our standalone proxy setups we didn't find any other changes that could break the current plugin.

To handle the config change in the ServerPort parameter maybe we could just change the help text to reflect that?

**Comment by mimugmail** [comment]
Can you split this into 2 PR's for agent and proxy? I also wanted to have a look at proxy this week.

**Comment by rmundel** [comment]
Sure. I'll split in two.

**Comment by rmundel** [comment]
@mimugmail 

Done in #2964 and #2963

**Pull request closed without merging**
