### PR TITLE
Added All-Inkl v4 and v6 DynDNS support

### PR DESCRIPTION
**Pull request by polkhigh33**
Added All-Inkl v4 and v6 DynDNS support

All-Inkl is a german webhoster which supports DynDNS updates for registered domains.
Unfortunately the update domain/url only supports IPv4, so there is a small fix if we are updating an IPv6 address.

### CODE REVIEW

**Comment by Starkstromkonsument** [comment]
Hi, please take a look at https://github.com/opnsense/plugins/issues/1611#issuecomment-706129596 and #2053. As you are also interested in contributing to the dyndns-plugin, would you like to help? Please join the discussion at #1611 if you are interested. Thank you.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by polkhigh33** [comment]
Hi @fichtner,

thanks for merging. But it looks like we lost a `break` in switch-case. Could you fix this or should i create a new PR?

**Comment by fichtner** [comment]
@polkhigh33 happy if you could provide a PR

**Comment by polkhigh33** [comment]
@fichtner Done, thanks.

#2420

**Pull request merged**
