### PR TITLE
add backup api; closes #865

### LINKED ISSUE #865: config-export via MVC
via: https://github.com/opnsense/core/issues/2731

### PR DESCRIPTION
**Pull request by fabianfrz**
@fichtner as I told you less than 10 lines of code (7)

### CODE REVIEW

**Comment by AdSchellevis** [comment]
easy as that indeed, it would be good to add some simple template with a download button (+menu registration) which triggers this, so people know where to look after installation.

**Comment by mimugmail** [comment]
Isnt this something for core :)

**Comment by AdSchellevis** [comment]
@mimugmail https://github.com/opnsense/core/issues/2731

**Comment by fabianfrz** [comment]
@AdSchellevis I don't think we should duplicate core features as you already mentioned in the ticket before. This is just for automation.

**Comment by fichtner** [comment]
I'd prefer this to be API-only, point to the docs in the description and maybe add an XML push as well for symmetry?

**Comment by fabianfrz** [comment]
@fichtner the ticket said read-only API…

Push is IMHO not so easy (XML validation) and may have other issues (new machine ist not yet set up).

**Comment by fichtner** [comment]
ok, fine. :)

**Comment by AdSchellevis** [comment]
@fichtner ack, using api-backup as endpoint name, better to remove the ui/* acl as well then.

**Comment by fabianfrz** [comment]
@fichtner @AdSchellevis  api-backup would move it at the top of the list of available plugins and may lead to a group of `api-` plugins.

If you are talking about the namespace or endpont: they cannot contain dashes.

**Comment by fichtner** [comment]
just the name, we do the same for "theme-"

**Comment by fabianfrz** [comment]
ok, no problem

**Comment by fichtner** [comment]
We could ultimately work on fireware GUI showing "theme-" and "api-" in different blocks if you worry about ordering :)

**Comment by fabianfrz** [comment]
@fichtner wait for it when it is needed

**Comment by fabianfrz** [comment]
@fichtner merge now?

**Comment by fichtner** [comment]
yes 👍

**Comment by Clement-Ruiz** [comment]
Hello there.

Nice job you've done here.
Could you add this feature to documentation please ? the usage might be kind of an evidence for you guys, but I'm not a OpnSense contributor, and even looking at source code I can't figure out which url I must request in order to get my backup.
Mabe somewhere like here ? https://wiki.opnsense.org/development/api.html#plugins-api

Thank you

**Comment by mimugmail** [comment]
@Clement-Ruiz How about this, you clone the docs repo and write it to contribute to all other? :) 

This is the API call:

curl -k -u "key":"secret" https://192.168.0.1/api/backup/backup/download

**Comment by Clement-Ruiz** [comment]
Hello @mimugmail, thanks for your response.
Expect your PR. ;)
Have a great one

**Comment by mimugmail** [comment]
Thx 👍

**Pull request merged**
