### PR TITLE
Freeradius save act improvements

### PR DESCRIPTION
**Pull request by fichtner**

### CODE REVIEW

**Comment by mimugmail** [comment]
@fichtner We should also do this for Quagga

**Comment by fichtner** [comment]
yup, would be nice :)

I was here because of the LibreSSL error, it seems the incoming bump to LibreSSL 2.5.5 in 17.7.1 will fix it automagically...

**Comment by mimugmail** [comment]
17.7.1 will be one of my favourites :)

**Comment by fichtner** [comment]
"the best version since 17.7"

**Comment by fichtner** [comment]
FYI, kosmetische Änderung in e3997bd48e5133b7b125f5898ee2cb0019769563

**Pull request merged**
