### PR TITLE
Add OSPF Router ID

### PR DESCRIPTION
**Pull request by fabianfrz**
Please remove the source branch when merged.

This should fix https://forum.opnsense.org/index.php?topic=6054.0

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by clystron** [comment]
I have a very similar issue but with BGP (highest IP is chosen by default and BGP is restarted if that IP goes down), being able to set the BGP router-id would help.

**Comment by mimugmail** [comment]
Can you open a new issue please? I'll take care of it

**Comment by clystron** [comment]
Wow, that was quick...
Done: https://github.com/opnsense/plugins/issues/948

**Pull request merged**
