### PR TITLE
Dedicated Sensei repo links for OPNsense major versions

### PR DESCRIPTION
**Pull request by muratbalaban43**
To be able to maintain repository consistency between OPNsense and Sensei, we'll have seperate repository links for every OPNsense major version.

### CODE REVIEW

**Comment by fichtner** [comment]
@muratbalaban43 take a look at d3ce811 please, should be easy enough to build upon :)

**Comment by muratbalaban43** [comment]
@fichtner , this is neat :) Will send another commit with the honoring the new implementation.

**Comment by muratbalaban43** [comment]
@fichtner , tested this. %%PLUGIN_ABI%% got replaced successfully whereas %%PLUGIN_FLAVOUR%% did not. 

Resulting repo file:
```
SunnyValley: {
  fingerprints: "/usr/local/etc/pkg/fingerprints/SunnyValley",
  url: "https://updates.sunnyvalley.io/opnsense/${ABI}/20.1//latest",
  signature_type: "fingerprints",
  priority: 7,
  enabled: yes
}
```


Any hints for me?

**Comment by fichtner** [comment]
It works from here in a correct build env... maybe you don't have /usr/local/bin/openssl around?

```
# make package
>>> Generating metadata for os-sunnyvalley-devel-1.2... done
>>> Staging files for os-sunnyvalley-devel-1.2... done
>>> Packaging files for os-sunnyvalley-devel-1.2:
file sizes/checksums     [4]: 100%
packing files            [4]: 100%
packing directories      [0]: 100%
# cat work/
pkg/ src/ 
# cat work/src/
+DESC      +MANIFEST  plist      usr/       
# cat work/src/usr/local/etc/pkg/repos/SunnyValley.conf 
SunnyValley: {
  fingerprints: "/usr/local/etc/pkg/fingerprints/SunnyValley",
  url: "https://updates.sunnyvalley.io/opnsense/${ABI}/20.1/LibreSSL/latest",
  signature_type: "fingerprints",
  priority: 7,
  enabled: yes
}
```

**Comment by muratbalaban43** [comment]
@fichtner , great. Let me check again.

**Comment by muratbalaban43** [comment]
@fichtner , you are right. It was a missing openssl binary. Thanks for the support.

**Pull request merged**
