### PR TITLE
net-mgmt/collectd: add prefix and postfix input fields

### PR DESCRIPTION
**Pull request by mimugmail**
As discussed in #296 and requested in #297

### CODE REVIEW

**Comment by mimugmail** [comment]
But what if the user doesn't want any pre- or postfix? 
The problem is that in conf per default collectd is set for both, but it's not in DB.

I believe the 2 previos authors want to just zeroize this field which wont work if required Y

**Comment by fichtner** [comment]
Ok, that wasn’t obvious to me that blanking and appending is both needed. In this case we only need the config model bump.

**Comment by mimugmail** [comment]
I set it to 1.1.0, version was missing completely, unsure if default is 1.0.0, so I decided 1.1.0.

**Comment by fichtner** [comment]
Stupid auto-correct. 1.0.0 is ok here

**Comment by mimugmail** [comment]
Ok we're at 1.0.0 :)

**Comment by fichtner** [comment]
Thanks!

**Pull request merged**
