### PR TITLE
multiple inet6 bug

### PR DESCRIPTION
**Pull request by peppelinux**
Fixed: https://github.com/opnsense/plugins/issues/506

### CODE REVIEW

**Comment by fichtner** [comment]
Is this the same as #511 or what happened here?

**Comment by peppelinux** [comment]
You're right Franco, First of all I made the commit though the web, I thought that I was working on my repo but it was not so and my changements were made as proposed changement over your repo.

Then, I made I pushed the same thing through my locale git folder.
It's incredible about how many excuse I have to do for every freaky PR I do, really sorry!

**Comment by fichtner** [comment]
No worries, I just want to make sure I pull the correct one. Take your time.

**Comment by peppelinux** [comment]
Patch is complete, will not spend no more time on this task Franco
really thank you

**Comment by fichtner** [comment]
merged manually due to conflicts

**Pull request closed without merging**
