### PR TITLE
Minor colour corrections

### PR DESCRIPTION
**Pull request by marjohn56**
Fix some colours

### CODE REVIEW

**Comment by fraenki** [comment]
@marjohn56 I just stumbled across this old PR... is this still relevant?

**Comment by marjohn56** [comment]
I would expect so as it's not been closed or pulled.

**Comment by fraenki** [comment]
@fichtner LGTM, OK to merge?

**Review by fichtner — APPROVED** [review]
ok

**Comment by fraenki** [comment]
@marjohn56 Thank you for your patience, and sorry that it took so long.

**Pull request merged**
