### PR TITLE
Add BFD diagnostics to new style FRR diagnostics

### PR DESCRIPTION
**Pull request by MarkStitson**
This adds the missing BFD diagnostics for FRR.
See #3484 and #2399 for more detail.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@MarkStitson as I don't have anything available with BFD enabled, it would be quite practical to have some test output for the related  commands (json).  When https://github.com/opnsense/plugins/pull/3484 is finished, I don't mind spending some time pulling this in, but I will likely need a bit of your time as well then for test and validation.

**Comment by MarkStitson** [comment]
I have a small test box and some live boxes with BFD enabled.

From the test box for the neighbors tab:
image
`root@OPNsense:~ # /usr/local/bin/vtysh -c "show bfd peers json"
[{"multihop":false,"peer":"192.168.6.1","vrf":"default","id":436640337,"remote-id":2849227342,"passive-mode":false,"status":"up","uptime":12632,"diagnostic":"ok","remote-diagnostic":"ok","receive-interval":300,"transmit-interval":300,"echo-interval":0,"detect-multiplier":3,"remote-receive-interval":10,"remote-transmit-interval":100,"remote-echo-interval":0,"remote-detect-multiplier":5},{"multihop":false,"peer":"192.168.6.18","vrf":"default","id":4197871521,"remote-id":0,"passive-mode":false,"status":"down","downtime":12633,"diagnostic":"ok","remote-diagnostic":"ok","receive-interval":300,"transmit-interval":300,"echo-interval":0,"detect-multiplier":3,"remote-receive-interval":1000,"remote-transmit-interval":1000,"remote-echo-interval":0,"remote-detect-multiplier":3}]
`

From the test box for the summary tab:
image
Plain as used in diagnostics:
`root@OPNsense:~ # /usr/local/bin/vtysh -c "show bfd peers brief"
Session count: 2
SessionId  LocalAddress                             PeerAddress                             Status
=========  ============                             ===========                             ======
436640337  192.168.6.125                            192.168.6.1                             up
4197871521 unknown                                  192.168.6.18                            down
`
The JSON is not useful as a summary:
`root@OPNsense:~ # /usr/local/bin/vtysh -c "show bfd peers brief json"
[{"multihop":false,"peer":"192.168.6.1","vrf":"default","id":436640337,"remote-id":2849227342,"passive-mode":false,"status":"up","uptime":12701,"diagnostic":"ok","remote-diagnostic":"ok","receive-interval":300,"transmit-interval":300,"echo-interval":0,"detect-multiplier":3,"remote-receive-interval":10,"remote-transmit-interval":100,"remote-echo-interval":0,"remote-detect-multiplier":5},{"multihop":false,"peer":"192.168.6.18","vrf":"default","id":4197871521,"remote-id":0,"passive-mode":false,"status":"down","downtime":12702,"diagnostic":"ok","remote-diagnostic":"ok","receive-interval":300,"transmit-interval":300,"echo-interval":0,"detect-multiplier":3,"remote-receive-interval":1000,"remote-transmit-interval":1000,"remote-echo-interval":0,"remote-detect-multiplier":3}]
`

From the test box for the counters:
image
`root@OPNsense:~ # /usr/local/bin/vtysh -c "show bfd peers counters json"
[{"multihop":false,"peer":"192.168.6.1","vrf":"default","control-packet-input":51792,"control-packet-output":47552,"echo-packet-input":0,"echo-packet-output":0,"session-up":1,"session-down":0,"zebra-notifications":2},{"multihop":false,"peer":"192.168.6.18","vrf":"default","control-packet-input":0,"control-packet-output":14560,"echo-packet-input":0,"echo-packet-output":0,"session-up":0,"session-down":0,"zebra-notifications":0}]
`

**Comment by MarkStitson** [comment]
Here is output from a real live box, but I don't have the new diagnostics installed, so no screenshots.

[bfddiagfromlive box.txt](https://github.com/opnsense/plugins/files/11860435/bfddiagfromlive.box.txt)

I am happy to help when you get to this.

**Comment by AdSchellevis** [comment]
@MarkStitson this is already incredibly helpful, thanks! I'll try to pick this up after merging https://github.com/opnsense/plugins/pull/3484

**Comment by AdSchellevis** [comment]
@MarkStitson I've reworked the code a bit in https://github.com/opnsense/plugins/commit/12f61c65e44545e09f3b5e8119ef3dc79ed58216, removed the plain text output as we're planning to do that for the other endpoints as well. Can you try if this works for you? Thanks in advance

**Comment by MarkStitson** [comment]
A small issue is using the ID in bfdTreeFetch, the ID is a random string, so using 
$peerid = $peer['peer']
is always better.

The bigger problem with FRR is that the output of 
/usr/local/bin/vtysh -c "show bfd peers brief"
and
/usr/local/bin/vtysh -c "show bfd peers brief json"
are different.

/usr/local/bin/vtysh -c "show bfd peers json"
is the same as
/usr/local/bin/vtysh -c "show bfd peers json"

Do you want me to go away and write some code that will take the output of 
/usr/local/bin/vtysh -c "show bfd peers json"
and produce sensible output like the tables used for BGP/OSPF routing tables?

**Comment by AdSchellevis** [comment]
> A small issue is using the ID in bfdTreeFetch, the ID is a random string, so using
> $peerid = $peer['peer']
> is always better.

No problem, we can revert that, I was triggered by the "show bfd peers brief" output. 


> The bigger problem with FRR is that the output of
> /usr/local/bin/vtysh -c "show bfd peers brief"
> and
> /usr/local/bin/vtysh -c "show bfd peers brief json"
> are different.

If we're actually interested in `SessionId`, `LocalAddress`, `PeerAddress` and `Status`, we can split the data, not a big deal, I assumed both offered the same info, which doesn't appear to be the case. I would prefer converting it to usable (json) output, so other consumers would be able to use the feed. I can do that it that helps.

> Do you want me to go away and write some code that will take the output of
> /usr/local/bin/vtysh -c "show bfd peers json"
> and produce sensible output like the tables used for BGP/OSPF routing tables?

I'm not sure 100% sure I know what you mean, if you want to return a recordset and show it as a grid, it certainly helps to know which information is most relevant, it would be practical if you can write the grid part or explain which fields we should add.

**Comment by MarkStitson** [comment]
Oh, and the ourtput in the summary tab should be a table with one line per peer, rather than a tree, otherwise it fails at being a simple summary.

**Comment by AdSchellevis** [comment]
> Do you want to do that, or do you want me to look at it? You're probably a better at this than I am, but I am happy to test it.

I can do that with the data you offered, no problem. 

> Oh, and the ourtput in the summary tab should be a table with one line per peer, rather than a tree, otherwise it fails at being a simple summary.

that's easy, if I can find a bit of time tonight I'll take a look at this. 

So to summarize, the "Summary" tab should contain a grid with the parsed data, the other two tabs are ok accept for the `id` field, right?

**Comment by AdSchellevis** [comment]
@MarkStitson there you go https://github.com/opnsense/plugins/commit/1552cf4395d10a4480057f8d9fac792c452fb1bf, just let me know what you think.

**Comment by MarkStitson** [comment]
The web UI looks good. 

There is a bug in the parsing function "public function bfdsummaryAction(): array" though.
If I manually add a record there it is displayed:
            $records[] = [
                    'id' => '0',
                    'local' => 'Local',
                    'peer' => 'Remote',
                    'status' => 'Fake'
            ];
But it doesn't print any of the actual output from the actions_quagga.conf

I will do some debugging and give you a more helpful response later.

**Comment by MarkStitson** [comment]
Adding an rtrim fixes the problem. The preg_split function produces 5 elemnts with an empty element at the end otherwise.

    public function bfdsummaryAction(): array
    {
        $records = [];
        foreach (explode("\n", $this->getInformation("bfd", "summary", "plain")['response']) as $line) {
            $line = rtrim($line);
            $parts = preg_split('/\s+/', $line);
            if (count($parts) == 4 && filter_var($parts[0], FILTER_VALIDATE_INT) !== false) {
                $records[] = [
                    'id' => $parts[0],
                    'local' => $parts[1],
                    'peer' => $parts[2],
                    'status' => $parts[3]
                ];
            }
        }
        return $this->searchRecordsetBase($records);
    }

**Comment by MarkStitson** [comment]
Looking good:
image

**Comment by AdSchellevis** [comment]
@MarkStitson ok, this https://github.com/opnsense/plugins/commit/a689c9fd8bca361e3df466f4c3a9098e321255be should be the missing piece then. Ready to merge?

**Comment by MarkStitson** [comment]
Ready to merge!

Looks good. I tested it on one of our larger opnsense boxes.

**Comment by AdSchellevis** [comment]
@MarkStitson thanks!

**Pull request closed without merging**
