### PR TITLE
dns/ddclient Add Njal.la DNS provider support

### PR DESCRIPTION
**Pull request by satrapes**
I have created a pull request in the [ddclient](https://github.com/ddclient/ddclient/pull/459) project for this as well.

A couple of things that I would like your help are:
1. When do you not need to update ddclient.conf? I saw ovh does not need to be updated but didn't fully understand why.
2. Do I need to manually update the `pkg-descr`?
3. Where is the version of `ddclient` specified?

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@satrapes 

> 1. When do you not need to update ddclient.conf? I saw ovh does not need to be updated but didn't fully understand why.

When only a protocol is needed, in which case the "else" covers the item

https://github.com/opnsense/plugins/blob/e9c2a613c315349a35a8a38e21b8982fc7d60b4b/dns/ddclient/src/opnsense/service/templates/OPNsense/ddclient/ddclient.conf#L90-L91

> 2. Do I need to manually update the pkg-descr?

Can do this later, when it's being added to a release

> 3. Where is the version of ddclient specified?
 In ports (https://github.com/opnsense/ports/blob/master/dns/ddclient/Makefile)

just ping us when ddlcient includes your feature in a release version.

**Comment by satrapes** [comment]
Thanks for the reply @AdSchellevis . I figured 1. out so edited my initial post before I saw your answer.
I will push for it to be included into next release then.

**Comment by satrapes** [comment]
So the DNS provider has been added to ddclient master branch. I am a bit puzzled as to which release it needs to be added for this to make it onto OPNSense plugin directory. The OPNsense plugin ddclient release is 1.9 but I am not sure if or how it maps to the ddclient release versions. Current is [v3.10.0_2](https://github.com/ddclient/ddclient/releases/tag/v3.10.0_2) last released in May and FreeBSD is still on [v3.9.1](https://github.com/ddclient/ddclient/releases/tag/v3.9.1) according to this page https://repology.org/project/ddclient/versions

**Comment by dabruh** [comment]
@fichtner if people could just decide to use [semver](https://semver.org/)

**Comment by satrapes** [comment]
Damn this is awesome. This is going to be my first open source contribution. I am so happy to give back to the community.

**Comment by dabruh** [comment]
>just ping us when ddlcient includes your feature in a release version

Ping @AdSchellevis :-)

**Comment by AdSchellevis** [comment]
@dabruh pong :) I'll try to sync the merge with our inclusion of 3.10.0 (https://github.com/ddclient/ddclient/releases/tag/v3.10.0)

**Comment by fichtner** [comment]
port is more or less ready, but we won't publish before FreeBSD ports inclusion (which we will try to do on Monday)

**Comment by dabruh** [comment]
@fichtner @AdSchellevis any updates on this? Thanks! :-))

**Comment by AdSchellevis** [comment]
We are trying to get the final 3.10.0 into FreeBSD ports currently to progress this... https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267323

(from https://forum.opnsense.org/index.php?topic=26446.msg148989#msg148989)

**Comment by lucaschoeneberg** [comment]
Hi, do we still have to wait for the 3.10.0 (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267323), or can we also take the 3.10.0-devel? 
In addition, support for other DNS providers must be added, such as Hetzner. 
Can I help in any way?

**Comment by fichtner** [comment]
@lucaschoeneberg I made a ddclient-devel for os-ddclient-devel to use which will be available in 22.7.8. I'm not sure about FreeBSD ports movement. Doesn't seem to be very enthusiastic at this point.

**Comment by fichtner** [comment]
I haven't gotten around picking those that are new in 3.10.0 where a PR exists. This is going to be a mess for plugin backporting management in any case..

**Comment by AdSchellevis** [comment]
should be in ddclient (development)

**Pull request closed without merging**
