### PR TITLE
www/nginx - newsyslog: added tls_handshake.log rotation

### PR DESCRIPTION
**Pull request by juliocbc**
Fix problem with tls_handshake.log lacking rotation.

### CODE REVIEW

**Comment by fabianfrz** [comment]
This file should not be rotated as it is not designed to be a common log file. It is processed by a cron job after every 10 minutes and afterwards deleted:

https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/scripts/nginx/ngx_autoblock.php#L87
https://github.com/opnsense/plugins/blob/master/www/nginx/src/opnsense/scripts/nginx/tls_ua_fingerprint.php

The purpose of that file is building the input for the Man in the middle detection.

**Comment by juliocbc** [comment]
We are noting here several OPNsense installations with this log file growing without been deleted, since which version this should be working?

**Comment by fabianfrz** [comment]
I don't know that something is not working. There is a change upcoming which is refactoring the whole script: #1773

**Comment by juliocbc** [comment]
Thanks! So I'll close this one to wait for the definitive solution you mention above.

**Pull request closed without merging**
