### PR TITLE
net/frr: replace legacy ruby code, get rid of dependency

### LINKED ISSUE #1877: Increase BGP functionality
I've switched from pfsense to opnsense and got opnsense be my favourite Router/Firewall before pfsense and also vyos.
Pfsense has a ton of BGP options in the GUI while opnsense lacks of many options without which i've to edit my FRR config manually.
Are there plans to increase bgp functions in the GUI?

### LINKED ISSUE #2101: FRR: replace ruby dependancy
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Since most of our core components are written in either `python` or `php` and FRR is being used more ofter, it would be practical to increase the maintainability of the plugin since output formats of `vtysh`  change over time.

looking briefly at quagga.rb, a list of diagnostics can be retrieved, for which a part can already be extracted natively in json format, some will still need a (simple) conversion from plain text to json. To ease the user interface parsing, we might hook into a similar tree view as is being used in the netstat view (`/ui/diagnostics/interface/netstat`).

**Describe the solution you'd like**
The solution depends on the diagnostic to fetch, when a native json output is available, we should probably use that, if not, we need a (simple) parser. Below the list of diagnostics being extracted split in both groups.

**vtysh -u -c "[command] json"**
- show ip[6] route
- show ip ospf neighbor
- show ip ospf interface
- show ip ospf route
- show ip ospf json
- show ip bgp

**need parser**
- show ip ospf database
- show ipv6 ospf6
- show ipv6 ospf6
- show ipv6 ospf6 linkstate
- show ipv6 ospf6 route
- show ipv6 ospf6 neighbor
- show ipv6 ospf6 database
- show ipv6 ospf6 interface

**Describe alternatives you've considered**
not applicable.

**Additional context**
In the long term we likely will start classifying plugins in relation to official support levels, to increase chances of a plugin to gain a higher level it should match certain criteria in terms of documentation and manageability.

### LINKED ISSUE #2137: FRR v1.19 Routing: Diagnostics: General:IPv4 Routes
https://github.com/opnsense/plugins/blob/8a72865e007cd157f0cbf6eace34a67971525c46/net/frr/src/opnsense/scripts/quagga/quagga.rb#L121

"ruby -d /usr/local/opnsense/scripts/quagga/quagga.rb --general-routes"

"Exception NoMethodError at /usr/local/opnsense/scripts/quagga/quagga.rb:121 - undefined method split for nil:NilClass"

Results in blank output in the Web-UI

### PR DESCRIPTION
**Pull request by marcquark**
closes #2101
closes #1877
closes #2137
very much a work in progress, will continue to add commits

### CODE REVIEW

**Comment by marcquark** [comment]
converting to a tree style display format could come in handy for OSPF interfaces and maybe also the overview. but routing tables should be kept in a tabular format imho (they're _tables_ after all).

**Comment by marcquark** [comment]
I'd like to try out FRR 7.5 because I suspect it could already have JSON support for `show ip ospf database` aswell as `show ipv6 ospf6 *`. The docs aren't super clear - they only list the json commands in "latest". However some of the commands have obviously already made it into 7.4, and 7.5 is pretty new. Would like to at least give it a shot before i spend time writing a parser...

Anyway, i'm not much of a BSD guy. Could use some guidance as to how i can install v7.5. According to https://www.freshports.org/net/frr7/ it should be available _somewhere_ in the FreeBSD 12 ports. I just have no clue where to look, and even if i found it, don't know how i would go about actually installing it. The FreeBSD docs seem to be offline at the moment, which doesn't help either...

**Comment by marcquark** [comment]
on another note
closes #1877

**Comment by AdSchellevis** [comment]
@marcquark our's is still at 7.4 (https://github.com/opnsense/ports/blob/master/net/frr7/Makefile), upstream (FreeBSD) seems to ship 7.5 at the moment (https://github.com/freebsd/freebsd-ports/blob/master/net/frr7/Makefile). Given the incompatibilities in the past, I expect we're not switching ours over instantly. The easiest step is probably to install our build tools (https://github.com/opnsense/tools) and copy their frr7 port in (either cherry pick or just download the changed files). 

The normal ports installation procedure is documented at FreeBSD (https://www.freebsd.org/doc/handbook/ports-using.html) as well.

**Comment by fichtner** [comment]
Yes, @mimugmail is still opting for 7.4 at this point due to general breakage in the 7 series...

**Comment by marcquark** [comment]
I tested 7.5 from the FreeBSD ports and it doesn't add any of the JSON commands. So they likely won't be available for the plugin anytime soon. Parsing it is then.

**Comment by marcquark** [comment]
summoning @mimugmail @fichtner @AdSchellevis
I need some help. Can't figure out how to make FRR output "Net Link States" without explicitly using `show ip ospf database network`, and even then the output is empty on my test installs. Do they only appear in certain non-trivial setups? I mimiced the parsing logic from the original script but have no way of verifying that it actually works. Maybe the default output of FRR for `show ip ospf database` has changed over time without anybody noticing?

If any of you can produce such output, could you please upload it so i can use it for testing?

**Comment by AdSchellevis** [comment]
probably @mimugmail can try this on his end, I only have a boring pretty empty setup over here, which outputs an empty dataset like yours:

```
# show ip ospf database network

       OSPF Router with ID (192.168.123.125)


                Net Link States (Area 0.0.0.0)
```

**Comment by marcquark** [comment]
finished :-) pls give it a test and lmk if you encounter and bugs or have suggestions for improvements

BTW should i also commit an update to the changelog in pkg-descr?

**Comment by AdSchellevis** [comment]
I'll try to give it a spin on my end, check the code style and if @mimugmail agrees pull it into master for further testing.

**Comment by mimugmail** [comment]
Please bump to 1.21 and add a Changelog :)
Tonight I have a maintenance and can test it as well .. would be nice to have this one

**Comment by marcquark** [comment]
sure thing, there u go

**Review by mimugmail — APPROVED** [review]
Looks good, thank you 👍 
For me it's ok if it stays in master for a while.

I didn't test multi area ospf yet, maybe over christmas season.

**Comment by AdSchellevis** [comment]
I've some style fixes and typo corrections stashed, will commit them with the merge of this one. The python script is a bit difficult to read, but since it's only temporary until frr supports json on the other commands as well, I don't mind pulling it in. 

The user interface diagnostics code in general is quite buggy, lot's of errors in your browser when functionality isn't used, but this was already the case.

@marcquark thanks, and if you would like to add your name/email to the license, just open a new PR for the files you changed, I only added your name to the python script.

**Pull request merged**
