### PR TITLE
new plugin Monit

### PR DESCRIPTION
**Pull request by fbrendel**
This is a plugin to configure the Monit daemon.
[https://mmonit.com/monit/](https://mmonit.com/monit/)

### CODE REVIEW

**Comment by fichtner** [comment]
Looks good, let's go and thank you! :)

**Comment by fbrendel** [comment]
:simple_smile:
documentation follows

**Comment by fichtner** [comment]
neat. so far it looks good. it wouldn't start automatically or from the GUI, so I typed "service monit start" on the console. Will leave it installed on my main box to see if this happens again.

**Comment by fbrendel** [comment]
Monit is not enabled by default.
If you start it via "service" it uses probably an empty config (/usr/local/etc/monitrc).
Please use the GUI.

**Comment by fichtner** [comment]
I did, but it wouldn't start (always show as stopped) and left no indication as to why in the logs

**Comment by fbrendel** [comment]
What do you get if you click on "Test Configuration"?

**Comment by fichtner** [comment]
It said the configuration was ok:

Control file syntax OK

**Comment by fbrendel** [comment]
I guess you can start it now.
When will the +POST_INSTALL.post script executed on install?
Before or after template reload?

**Comment by fichtner** [comment]
After. I switched it to the expected position in the follow up commit. It seemed to work. Let me try to reproduce this later today. :)

**Comment by fbrendel** [comment]
The problem is that the .post is executed with make target script-post and this comes after scripts-auto which contains the template reload.
I think using the postfix .pre instead of .post, (what a pun ;-) ), should solve it.

**Comment by fichtner** [comment]
I see, that makes sense :)

**Comment by fbrendel** [comment]
Would you be so kind and rename it?
I would test it.

**Comment by fichtner** [comment]
sure, done https://github.com/opnsense/plugins/commit/b615789bfe33d66d28594722391bebc79aa52f82

**Comment by fbrendel** [comment]
No, doesn't work. And it wouldn't because Monit is not enabled by default.

Simply enabling it and clicking on "Apply" wouldn't work too.
The only effect is that it appears in the Services list. But with an empty monitrc it wouldn't start either.
Only clicking "Test Configuration" or "Reload Configuration" creates a monitrc, if Monit is enabled.

Hmm, somewhat tricky.

**Comment by fichtner** [comment]
Normally services don't show up in the list until they are disabled, something in monit.inc isn't entirely correct. I don't mind it not starting on first install, in fact that is what all services do (and FreeBSD does too). Could this be all we need to change?

**Comment by fbrendel** [comment]
> in fact that is what all services do

I've thought about that.
You need at least a working mail server (maybe localhost) and a valid alert recipient email address (maybe local root with a forward).
And good settings to avoid bothering the admin with alerts.

**Comment by fbrendel** [comment]
OK, if we enable monit per default (within Monit.xml) the service would appear in the Services list.
The user could start it but it wouldn't send any alerts.

How can I start it right after install?

**Comment by fichtner** [comment]
Short answer: we don't do this auto startup after install with services. :)

**Comment by fbrendel** [comment]
So leaving it stopped but enabled is ok?

**Comment by fichtner** [comment]
No it should be disabled and not show up in the services until configured/enabled by the user. That's what all the services and VPNs are doing.

**Comment by fbrendel** [comment]
This is what the plugin already does. :confused: 

Merely the handling - click "Enable monit", click "Apply", click "Test Configuration", start service - is not so optimal but IMHO reasonable.

**Comment by fbrendel** [comment]
Reasonable if documented of course.

**Pull request merged**
