### PR TITLE
[WIP] RIP Quagga

### PR DESCRIPTION
**Pull request by fabianfrz**
Work in progress...

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner It currently produces this error, any idea where this comes from:
```
configd.py: [40e17d38-fa5c-4ce3-b459-cc411ce2bad2] 
Inline action failed with OPNsense/Quagga OPNsense/Quagga/quagga 'collections.OrderedDict object' has no attribute 'ripd' at Traceback (most recent call last): 
File "/usr/local/opnsense/service/modules/processhandler.py", line 505, in execute return ph_inline_actions.execute(self, inline_act_parameters) 
File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute filenames = tmpl.generate(parameters) 
File "/usr/local/opnsense/service/modules/template.py", line 309, in generate raise render_exception Exception: OPNsense/Quagga OPNsense/Quagga/quagga 'collections.OrderedDict object' has no attribute 'ripd'
```

**Comment by fichtner** [comment]
unprotected access of "ripd" in the template? should be easy to find...

**Comment by fabianfrz** [comment]
@fichtner the template does not contain the 'word' ripd

**Comment by fichtner** [comment]
$ git grep ripd
net/quagga/src/opnsense/service/templates/OPNsense/Quagga/quagga:if helpers.exists('OPNsense.quagga.rip.enabled') and OPNsense.quagga.ripd.enabled == '1' %} ripd{% endif %}{%

**Comment by fabianfrz** [comment]
ok, thats an older bug then, which I did not suspect...

**Comment by fabianfrz** [comment]
@fichtner so this is working now - I need to bump version so it can be in 17.1.4

**Comment by fichtner** [comment]
it's not that strict, version or revision bumps are only needed from release to release, e.g. 0.0.2 is good enough for now

**Comment by fabianfrz** [comment]
@fichtner can I merge that?

**Pull request merged**
