### PR TITLE
net/haproxy: release 3.12

### PR DESCRIPTION
**Pull request by fraenki**
see plugin changelog for details

### CODE REVIEW

**Comment by fichtner** [comment]
@fraenki the 22.7.6 release is tomorrow. I don't want to rush this but if you have an easy bugfix that is required (any plugin) you can decide to make that first and skip the changes for later

**Comment by fraenki** [comment]
@fichtner Thanks for the heads-up! There's nothing too important planned, so it's OK to wait for 22.7.7 or a later release.

**Comment by fichtner** [comment]
Thanks, then I'll go through with building 22.7.6 now. No plugins updates in this one, but why not keep it light for once. :D 

Thanks,
Franco

**Comment by fraenki** [comment]
@fichtner Oh wait, security/acme-client is broken in master. I've fixed it in https://github.com/opnsense/plugins/pull/3157/commits/14870830eb5441ae947bbdbd3225fc6c79527a05 only, because I thought the build was already started.

**Comment by fichtner** [comment]
@fraenki from the new commits? I didn't base the build on them so I guess we are fine

**Pull request merged**
