### PR TITLE
www/nginx: njs0.7.1 compatibility (fixes startup error)

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi! can fix https://forum.opnsense.org/index.php?topic=28831.0 i hope
njs module now requires js_import directive (http://nginx.org/en/docs/http/ngx_http_js_module.html#js_include) and the use of the export statement in .js

Thanks!

### CODE REVIEW

**Comment by johnnyslee** [comment]
Even though this one is not using namespace, fixes #3015, too. `nginx -t` reports ok.

**Comment by kulikov-a** [comment]
@johnnyslee thanks! my bad - forgot about namespaces (although report is ok and nginx starts up, the function won't be found without a namespace). fixed. thanks again )

**Comment by Arnavion** [comment]
>(although report is ok and nginx starts up, the function won't be found without a namespace).

nginx starts up even if it can't find the function anyway. You can comment out the `js_include` / `js_import` entirely while leaving the `js_set` and nginx starts up fine. (People were doing to mitigate #3015 initially.)

So probably something more rigorous should be done to make sure the function is actually getting run correctly. Make it write a file to `/tmp` or something?

**Comment by kulikov-a** [comment]
@Arnavion if a function cannot be found for a `js_set` $variable, then the corresponding error is logged in SERVICES: NGINX: LOGS / HTTP ERROR (like "...js function "check_intercept" not found, client:..")
so I don't think there is a need to create a temp file?

**Comment by Arnavion** [comment]
Okay, that sounds good then.

**Comment by fichtner** [comment]
@kulikov-a nice to hear from you. Ready for merge?

**Comment by kulikov-a** [comment]
@fichtner thanks!! 
it seems to me ready (nginx starts, `$tls_intercepted` variable is successfully assigned values)

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
