### PR TITLE
dns/dnscrypt-proxy: fixed "disabled_server_names"

### PR DESCRIPTION
**Pull request by Karlson2k**
Fixed function of "Disabled Servers List" when more than one server specified in the list.

### CODE REVIEW

**Comment by fichtner** [comment]
How does the generated output differ?

**Comment by Karlson2k** [comment]
Before this patch:

``` toml
disabled_server_names = ['name1,name2,name3']
```

After this patch:
``` toml
disabled_server_names = ['name1','name2','name3']
```

**Comment by fichtner** [comment]
@Karlson2k ok makes sense. jinja doesn't offer anything quite less obscure than this so we have to go with this solution.. just a bit hard to read (and GitHub markup for toml isn't helping here either). waiting for @mimugmail to wake up and nod

**Comment by Karlson2k** [comment]
It was actually copied from `server_names` a few lines above.

**Review by mimugmail — APPROVED** [review]
Looks good! Do you want to add a changelog to pkg-descr? Version bump not needed as I also pushed a fix

**Comment by Karlson2k** [comment]
@mimugmail will do it in minutes.

**Comment by Karlson2k** [comment]
@mimugmail Done.

**Review by mimugmail — APPROVED** [review]

**Comment by fichtner** [comment]
merged, thank you!

**Pull request merged**
