### PR TITLE
www/nginx: add request limits

### PR DESCRIPTION
**Pull request by fabianfrz**
allow to limit the rate of requests per minute or second

### CODE REVIEW

**Comment by fabianfrz** [comment]
preferly later

**Comment by fichtner** [comment]
Will you bump to 1.1 then? I already copied 1.0 to stable-

**Comment by fabianfrz** [comment]
I'll do before merge, model too.

**Comment by fabianfrz** [comment]
@fichtner when will 18.7.2 be out?

**Comment by fichtner** [comment]
Thursday

**Pull request merged**
