### PR TITLE
fix(Issue: 2111) Nginx Apply load balancing for UDP

### PR DESCRIPTION
**Pull request by poggenpower**
Fix for 
https://github.com/opnsense/plugins/issues/2111

### CODE REVIEW

**Comment by fraenki** [comment]
@poggenpower This is about nginx, not HAProxy. I've corrected the title accordingly.

**Comment by poggenpower** [comment]
Thanks, I should not do two things in parallel 😇

**Review by fabianfrz — APPROVED** [review]
looks good.

**Review by fichtner — APPROVED** [review]

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
