### PR TITLE
Theme-Cicada Release 1.0

### PR DESCRIPTION
**Pull request by opnsenseuser12123**
with sass and less adaptation

Install and screenshots:
https://forum.opnsense.org/index.php?topic=7524.0

### CODE REVIEW

**Comment by fichtner** [comment]
@opnsenseuser12123 for the second time, you are intertwining with theme-rebellion plugin for this sudden push to version 1.0. To be clear, all plugins start as 0.1 and, after merge and community feedback, are moved to a release state in accord.

I don't understand your motives and you still haven't explained them after the last time we did a review.

I still have this one question: why is there a need for a second dark theme? And to add to the question would it not be better to work together?

So I need  you to understand that this is not a personal attack on your work like you implied last time. It is a valid question for the sake of avoiding community split over (allegedly) equal plugins, duplication of efforts, avoiding confusion about which theme receives which bug report and most importantly why you see your work as important, what makes it unique and how willing you are to advance this in the next weeks, months and possibly years to come.

Only when you answer we can move forward with this, whichever direction fits best. But if you start acting up again, I will not start picking this up *a third time*. I hope we are clear.


Cheers,
Franco

**Comment by opnsenseuser12123** [comment]
First...Sorry, for my Bad english

So, its Version 1 behause its ready and has no problems at all. 
I did a lot of fixes, but the Problem was it never was accepted for the opnsense repo. Why? Only of the dark Team?
I did a lot of request on github but noone accepted my PR.

If you compare both themes, you will See that there are big differences in all.
Cicada is not Black and has thoughtful links and hovers. Its orange grey and I really struggled to get everything aligned. Links, hover, headings, search, health, so that a uniform picture is created and the people are happy. By the way. Did you Test my Theme yourself? 
I tested also the dark team and in my personal opinion it has no concept. 

The challenge for me was to make a Perfect Team.it was a coincidence that this Theme and the dark team appear at the same time.
To make it short. Let the community decide which theme to choose and this should be adopted. 

I can only say, that I like to make templates and I enjoy it. I would also like to continue the next years and make another complete different template in the future. But if you and the community don’t want it, then I keep this template for myself and delete all entries in the Forum.

I would like you to make a desicion now before investing more days in nothing.

Thx

**Comment by opnsenseuser12123** [comment]
So, what is your decision now?

**Comment by fichtner** [comment]
You are impatient, impulsive and overly fixated on your personal work with little regard for cooperation and friendliness along the way. I'll save us both the time and ask you to drop this. I'm sorry.

**Comment by opnsenseuser12123** [comment]
Have fun with the incredible dark team my friend




Dienstag, 27. März 2018, 14:26 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by fichtner** [comment]
Sure, thanks.

**Comment by opnsenseuser12123** [comment]
Idiot




Dienstag, 27. März 2018, 14:38 +0200 von notifications@github.com  <notifications@github.com>:

**Comment by fichtner** [comment]
Not sure if you meant to send this. Remember: friendliness is key. :)

**Pull request closed without merging**
