### PR TITLE
Themes - Tukan/Cicada - "The settings have been applied" color fix

### PR DESCRIPTION
**Pull request by opnsenseuser**
see my screenshot with the wrong colors! This is now been fixed!

grafik

### CODE REVIEW

**Comment by fichtner** [comment]
Makes sense. I started to use alert-success as an experiment in the firewall rules...

**Comment by fichtner** [comment]
merged, thanks!

**Comment by opnsenseuser** [comment]
@fichtner I thought I was crazy already! Because the problem was not present in the 19.1 version. I accidentally came across it! thx! 👍

**Comment by fichtner** [comment]
yep, only 19.7 at the moment. thank you for fixing this ahead of schedule :)

**Comment by opnsenseuser** [comment]
no problem! :-)

**Pull request merged**
