### PR TITLE
www/nginx Load naxsi core rules / Learningmode working

### PR DESCRIPTION
**Pull request by juliocbc**
Added an option in Global HTTP settings to load naxsi core rules and fix the problem with learning mode not working.

TODO: check if the core rules exists / make it work with some routine that update this rules.

### CODE REVIEW

**Comment by fabianfrz** [comment]
I have to reject it for license reasons - the core rules are GPL. That's the reason why they cannot be included. See #891 for my alternative.

**Comment by fichtner** [comment]
The GPL rules are not linked to a binary, are they? Or do you mean GPLv3?

**Comment by fabianfrz** [comment]
@fichtner File is under LGPL: https://github.com/nbs-system/naxsi/issues/423#issuecomment-394407953

**Comment by fichtner** [comment]
LGPL is perfectly fine. If you are worried we can have a separate nginx-naxi-rules plugin so it's more clear to the end-user?

**Comment by fabianfrz** [comment]
@fichtner this one is in my opinion obsolete because #891 loads the core rules into the configuration and after assignment to the location you have the same result in this issue with the exception that my version is configurable and more flexible. It also does not require to hardcode any rules.

**Comment by fichtner** [comment]
Ok, closing due to #891.

**Comment by juliocbc** [comment]
Thank you guys!

**Pull request closed without merging**
