### PR TITLE
www/caddy: Version 1.5.2

### PR DESCRIPTION
**Pull request by Monviech**
* ~~More DNS Providers added: dnsmadeeasy, bunny, civo, scaleway, acmeproxy, inwx, netcup, namedotcom, easydns, infomaniak, directadmin, hosttech, rfc2136, loopia, mythicbeasts, glesys, dynv6.~~
* ~~This means all possible current caddy-dns Providers have been added and it won't have to be touched for a while. :)~~ :( nope.
* Increased timeout of message area in reverse_proxy.volt and general.volt to 15 seconds, so users have a chance to actually read validation error messages before they disappear.
* When pressing Apply, the form is saved automatically before the reconfigure action. (general.volt) This prevents confusion when pressing apply but nothing happens because the changes haven't been saved with the save button first.
* Satisfy make lint
* Bug with DynDNS Interface is fixed upstream, it will be reflected once the Caddy binary has been rebuild (comes automatically). https://github.com/mholt/caddy-dynamicdns/issues/59
* Made sure the pkg-descr changelog reflects all changes and contributors to the plugin onward from the first stable release.
* Deleted Readme.md and started to write a doc article: https://github.com/opnsense/docs/pull/545

### CODE REVIEW

**Comment by Monviech** [comment]
The additional DNS Provider will be redacted due to challenges with the build in poudriere.

**Comment by fichtner** [comment]
@Monviech ready to go?

**Review by fichtner — APPROVED** [review]

**Comment by Monviech** [comment]
@Fichtner Yup ready to go, no more changes in pipeline for now.

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
