### PR TITLE
security/acme-client: release 1.10

### PR DESCRIPTION
**Pull request by fraenki**
## New features
- allow to configure acme.sh's log level (advanced option)
- write import events to the system log (#256)
- update acme.sh to version 2.7.4

## Bugfixes
- fix log file display in GUI (https://github.com/opnsense/plugins/issues/69)
- switch default log level for acme.sh from 2 to 1

### CODE REVIEW

**Comment by fichtner** [comment]
BTW, acme.sh is at 2.7.4 now

**Comment by fichtner** [comment]
@fraenki 17.7.2 is due on Wednesday, so this needs to go in today to be considered for the release.

**Comment by fraenki** [comment]
@fichtner Not sure if I can make the required changes timely, but I'll try later today.

**Comment by fraenki** [comment]
@fichtner Please add/merge acme.sh 2.7.4 for 17.7.2. It only contains many fixes and no functional change, AFAICT.

**Comment by fichtner** [comment]
ok, will do

**Comment by fichtner** [comment]
@fraenki thank you!

**Pull request merged**
