### PR TITLE
Themes - Tukan/Cicada dropdown-menu shadow and other fixes

### PR DESCRIPTION
**Pull request by opnsenseuser**
Themes - Tukan/Cicada dropdown-menu shadow

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@fichtner please merge  before next release. thx regards rené

**Comment by opnsenseuser** [comment]
@fichtner 
@AdSchellevis 
I do not want to annoy anyone, but I can not find another way to ask you, as I said, to merge the changes. thanks and sorry for the pointless stress. best regards rené

**Comment by AdSchellevis** [comment]
@opnsenseuser sure, consider it done.

**Comment by opnsenseuser** [comment]
@AdSchellevis 👍

**Pull request merged**
