### PR TITLE
Tukan Theme Update - Additional fixes for Firewall Schedule

### PR DESCRIPTION
**Pull request by marjohn56**

### CODE REVIEW

**Comment by fabianfrz** [comment]
did you generate that CSS file? It has many strange whitespace changes where I think SASS (rubygem, sassc) is not doing that.

**Comment by opnsenseuser** [comment]
i can´t see any whitespace in my original scss and css. did it as usual!

**Comment by opnsenseuser** [comment]
sorry, don´t how to fix this!

**Comment by opnsenseuser** [comment]
what do you mean exactly with white spaces (tab button)? How can I get rid of this and avoid having to go through each line manually?

**Comment by marjohn56** [comment]
@fabianfrz - When I issued the commit, there were no odd whitespaces, It all looked clean.

**Comment by opnsenseuser** [comment]
if, then it's my fault. but I do not really know what to do differently except in the future to work only with the tab button on the keyboard. 

but as I said in my original, I can not find anything

**Comment by marjohn56** [comment]
@opnsenseuser - I sent you back a file the other day where I had cleared all the whitespaces, ave you from doing it yourself. did you not get it?

**Comment by opnsenseuser** [comment]
Of course I got it. Tested it -> found no difference an I also sent this back to you.!

**Comment by opnsenseuser** [comment]
Can you give me a tip, so in the future, before I send martin files, I can simply check this on "whitespace".
I use notepad ++

Thank you. lg rene

**Comment by marjohn56** [comment]
opnsenseuser - I'll come back to you PM with how to check.

@fabianfrz - Check that now, looks clean on the diffs

**Comment by fabianfrz** [comment]
@marjohn56 The diff looks far better now. Have you fixed the syntax issue?

**Comment by marjohn56** [comment]
I cannot compile the existing repo main.scss file, can you?

**Comment by marjohn56** [comment]
Seems too many errors there. I have used a 'reverse' method at http://css2sass.herokuapp.com/ and taken the css file which is working to create the scss file, that then compiles nicely. I am just doing a compare on the compiled css with the original css now to see if it all checks out.

**Comment by marjohn56** [comment]
Hi Rene,

Having issues with the SCSS file not compiling. Can you check out the attached files. I have taken the css file and ‘reversed’ it to scss. I would like you to make a copy of your existing source, replace the files with the ones attached and check that it works nicely on your system, by that I mean the GUI is all correct etc. Please ask if you are not sure and we’ll get this worked out.

Regards,

Martin

**Comment by opnsenseuser** [comment]
you have not attached any files

and in your email before that, is still the tukan file without scheduler fix!

 

regards rene


Gesendet: Samstag, 19. Mai 2018 um 13:48 Uhr
Von: "Martin Wasley" <notifications@github.com>
An: opnsense/plugins <plugins@noreply.github.com>
Cc: opnsenseuser <noname12123@gmx.at>, Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/plugins] Tukan Theme Update - Additional fixes for Firewall Schedule (#679)

Hi Rene,

Having issues with the SCSS file not compiling. Can you check out the attached files. I have taken the css file and ‘reversed’ it to scss. I would like you to make a copy of your existing source, replace the files with the ones attached and check that it works nicely on your system, by that I mean the GUI is all correct etc. Please ask if you are not sure and we’ll get this worked out.

Regards,

Martin

**Comment by opnsenseuser** [comment]
but the scheduler fix is inside. my mistake. could not find any mistakes.

 

retgards rene

 

Gesendet: Samstag, 19. Mai 2018 um 13:48 Uhr
Von: "Martin Wasley" <notifications@github.com>
An: opnsense/plugins <plugins@noreply.github.com>
Cc: opnsenseuser <noname12123@gmx.at>, Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/plugins] Tukan Theme Update - Additional fixes for Firewall Schedule (#679)

Hi Rene,

Having issues with the SCSS file not compiling. Can you check out the attached files. I have taken the css file and ‘reversed’ it to scss. I would like you to make a copy of your existing source, replace the files with the ones attached and check that it works nicely on your system, by that I mean the GUI is all correct etc. Please ask if you are not sure and we’ll get this worked out.

Regards,

Martin

**Comment by opnsenseuser** [comment]
I did not find any mistakes. everything should fit. thanks Martin

 

regards rene

 

Gesendet: Samstag, 19. Mai 2018 um 13:48 Uhr
Von: "Martin Wasley" <notifications@github.com>
An: opnsense/plugins <plugins@noreply.github.com>
Cc: opnsenseuser <noname12123@gmx.at>, Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/plugins] Tukan Theme Update - Additional fixes for Firewall Schedule (#679)

Hi Rene,

Having issues with the SCSS file not compiling. Can you check out the attached files. I have taken the css file and ‘reversed’ it to scss. I would like you to make a copy of your existing source, replace the files with the ones attached and check that it works nicely on your system, by that I mean the GUI is all correct etc. Please ask if you are not sure and we’ll get this worked out.

Regards,

Martin

**Comment by marjohn56** [comment]
@fabianfrz - OK, Rene says it's working OK. Can you check the compile now. Lots of changes I know, but at least it appears to be correct now.

**Comment by fabianfrz** [comment]
still not working:
```
sassc theme_tucan_orig.scss 
Error: Invalid CSS after "  color:": expected expression (e.g. 1px, bold), was "#2d2d2d333;"
        on line 3039 of theme_tucan_orig.scss
>>   color: #2d2d2d333;
   ---------^
```

**Comment by opnsenseuser** [comment]
i made a new main.scss. perhaps this helps! regards rene
[main.scss.zip](https://github.com/opnsense/plugins/files/2019575/main.scss.zip)

**Comment by marjohn56** [comment]
@fabianfrz  - fixed that particular color issue. Mine compiled OK  though. How do you compile, or what flags the error?

**Comment by fabianfrz** [comment]
@marjohn56 @opnsenseuser both of your files do raise errors in different sass implementations in the same lines (sassc, sass).

The bug is raised because the color is not valid.

You run it via sass inputfile.csss > outputfile.css (same command line syntax works with the sassc command).

**Comment by marjohn56** [comment]
@fabianfrz - Thanks for that tip. I've installed sass and run the command

sass main.scss > main,css and it reports no errors, and does give a much cleaner css file than koala.

**Comment by opnsenseuser** [comment]
Hi Fabian,

hi Martin,

 

i changed the color (from 2d2d2d333 to 2d2d2d) and build the main.scss file again.

Couldn´t find any problem.

i sent the complete theme with the whitespace fix from martin as zip to martin back again.

now it should work.

 

thx Fabian

thx Martin

 

 

Gesendet: Samstag, 19. Mai 2018 um 21:55 Uhr
Von: "Fabian Franz BSc" <notifications@github.com>
An: opnsense/plugins <plugins@noreply.github.com>
Cc: opnsenseuser <noname12123@gmx.at>, Mention <mention@noreply.github.com>
Betreff: Re: [opnsense/plugins] Tukan Theme Update - Additional fixes for Firewall Schedule (#679)


@marjohn56 @opnsenseuser both of your files do raise errors in different sass implementations in the same lines (sassc, sass).

The bug is raised because the color is not valid.

You run it via sass inputfile.csss > outputfile.css (same command line syntax works with the sassc command).

**Comment by marjohn56** [comment]
@fabianfrz - When you get 10 minutes can you check this and confirm all is good now?

**Comment by fabianfrz** [comment]
```
Error: Invalid CSS after "...rder: 1px solid": expected expression (e.g. 1px, bold), was "#565656cc;"
        on line 7960 of theme_tucan_orig.scss
>>   border: 1px solid #565656cc;
   --------------------^
```

**Comment by fabianfrz** [comment]
@marjohn56 finally your sass file works

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
