### PR TITLE
Theme Tukan/Vicuna/Cicada - Updates

### PR DESCRIPTION
**Pull request by opnsenseuser**
because of merging problems

PR READY

### CODE REVIEW

**Comment by opnsenseuser** [comment]
it found no difference as you can see. so can´t reupload it. must be a merging problem!

**Comment by fichtner** [comment]
GitHub only merges what you provide? I thought this was ready...

**Comment by opnsenseuser** [comment]
@fichtner i know. you have aleady merged it, a few days ago, but it doesn´t work. so what can i do?
errors see >> https://github.com/opnsense/plugins/pull/2249#issuecomment-797315011
https://github.com/opnsense/plugins/pull/2251#issuecomment-797314398

**Comment by fichtner** [comment]
Use the plugins.git to install the target theme? I think everyone contributing to plugins does this.

**Comment by opnsenseuser** [comment]
I only know this possibility >>  `opnsense-patch -c plugins e7eed12d` and `opnsense-patch -c plugins c8b20efd`
for these themes.  am I doing something wrong?

**Comment by fichtner** [comment]
You need a local clone of this repository in your test device:

    # opnsense-code plugins
    # cd /usr/plugins/misc/theme-abc
    # git checkout master
    # make upgrade

Now you have the latest version installed...

**Comment by opnsenseuser** [comment]
thats very nice, that you help me. but i already have the latest version.

grafik

**Comment by opnsenseuser** [comment]
if you say there are no problems, then the problem will be somewhere else. Thank you for your support

**Pull request closed without merging**
