### PR TITLE
Update settings.xml

### PR DESCRIPTION
**Pull request by JSuenram**
Prepare WebGUI in Plugin to accept E-Mail-Adresses for Whitelisted E-Mails.

### CODE REVIEW

**Comment by mimugmail** [comment]
What about templating?

**Comment by JSuenram** [comment]
> What about templating?

If I am right this is already there in #3611 . 
https://github.com/opnsense/plugins/pull/3611

**Comment by mimugmail** [comment]
No, in #3611 you define a local file which is not templated, I thought it's already there. 

Now you create a form where you can add adresses without a model and without a file where those settings gets written for rspamd. 

Maybe you want to open a feature request with alle the things you need and we work on a complete PR together?

**Comment by JSuenram** [comment]
Yeah, you are right. I need more "practice" in this. I will create a feature request for rspamd-Plugin....

**Pull request closed without merging**
