### PR TITLE
Add quagga directory structure init script

### PR DESCRIPTION
**Pull request by fabianfrz**
This will create the directories if needed.

Merge when the script is hooked.

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner Where should I call this little script as it should be there when the system creates the mounts for the temporary file system?

**Comment by fichtner** [comment]
see how setup.sh for squid is handled:

$ git grep proxy.setup.sh
plist:/usr/local/opnsense/scripts/proxy/setup.sh
src/opnsense/service/conf/actions.d/actions_proxy.conf:command:/usr/local/opnsense/scripts/proxy/setup.sh;/usr/local/etc/rc.d/squid start
src/opnsense/service/templates/OPNsense/Proxy/rc.conf.d:squid_opnsense_bootup_run="/usr/local/opnsense/scripts/proxy/setup.sh"

**Comment by fabianfrz** [comment]
* plist does not exist in plugins
* actions: done
* rc.conf file: done

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
