### PR TITLE
net/haproxy: bugfix release 2.2

### PR DESCRIPTION
**Pull request by fraenki**
## New features
none

## Bugfixes
- fix for rules parameters (values could not be saved, leading to invalid rules)

### CODE REVIEW

**Comment by fraenki** [comment]
@fichtner Yet another critical bugfix :( This prevents most TCP/HTTP rules from working. It would be great if you could build another hotfix package...

**Comment by fichtner** [comment]
I have one other change in core anyway. Will do this tomorrow morning. Thanks for your relentless support! :)

**Comment by mimugmail** [comment]
I'm waiting for a tweet by Jim about your high frequency updates :P

**Comment by fichtner** [comment]
sure, can't be good, right? :D

**Comment by mimugmail** [comment]
Doesn't me .. now my customer has a stable redirect for HAProxy ;)

P.S.: Hi Jim! :)

**Pull request merged**
