### PR TITLE
rspamd: fix templates (don't render unless the model exists)

### PR DESCRIPTION
**Pull request by fabianfrz**
@mimugmail try this patch for #353

### CODE REVIEW

**Comment by mimugmail** [comment]
I switched to branch rspamd but it didn't fix the error when installing the pkg

`Nov  1 06:20:53 OPNsense configd.py: [75d450c0-ec31-427b-95a9-1463f9df708c] Inline action failed with OPNsense/Rspamd OPNsense/Rspamd/antivirus.conf 'collections.OrderedDict object' has no attribute 'max' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 507, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Rspamd OPNsense/Rspamd/antivirus.conf 'collections.OrderedDict object' has no attribute 'max'
`

**Comment by fabianfrz** [comment]
@mimugmail thanks for this report. This is a jinja / python issue -> it interprets `-` as an operator and not as part of the name.

**Comment by mimugmail** [comment]
Now it's whitelist, not max:

`Nov  1 09:02:22 OPNsense configd.py: [440cef91-92ad-461b-a9f9-8282701b87ca] Inline action failed with OPNsense/Rspamd OPNsense/Rspamd/antivirus.wl 'collections.OrderedDict object' has no attribute 'whitelist' at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 507, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 50, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 309, in generate     raise render_exception Exception: OPNsense/Rspamd OPNsense/Rspamd/antivirus.wl 'collections.OrderedDict object' has no attribute 'whitelist'
`

**Comment by fabianfrz** [comment]
@mimugmail I have added some locks to the template - cannot reproduce it.

**Comment by mimugmail** [comment]
:D Was wondering why it doesn't found rspamd branch. Ok it's working now with master, will test some more tomorrow

**Pull request merged**
