### PR TITLE
C-icap whitelist

### PR DESCRIPTION
**Pull request by kekek2**
Exclude domains from antivirus check.

### CODE REVIEW

**Comment by fabianfrz** [comment]
@kekek2 this is wrong here. This should go to core -> proxy as it has absolutely nothing to do with the c-icap plugin. However it should work there without many modifications.

CC @fichtner

**Comment by fabianfrz** [comment]
@AdSchellevis I assigned that to you as I think it is not correctly placed.

**Comment by fichtner** [comment]
if anything, we would like to avoid circular configuration + dependencies... this is getting tricky after trying to keep clamav and c-icap clean of dependencies.

**Comment by AdSchellevis** [comment]
I agree with @fabianfrz here, if you don't want to send requests to a configured icap server, you should exclude it in squid, preferably on the icap tab.

**Pull request closed without merging**
