### PR TITLE
security/acme-client: add acme client

### PR DESCRIPTION
**Pull request by fraenki**
# Introduction
Sponsored by: [markt.de](http://www.markt.de/)

This is the first version of our acme plugin. It utilizes [acme.sh](https://github.com/Neilpang/acme.sh) and supports 14 DNS providers. Besides that, there's our integrated HTTP-01 validation which should makes it very easy to validate certificates (provided that the official IP address points to the OPNsense box).

This is the _initial_ relase and is expected to contain bugs. Support for many DNS-01 providers is largely untested. Please don't use it in production just yet. :)

# Remarks
Initially I wanted to integrate [acme-client](https://github.com/kristapsdz/acme-client), but this would have meant additional efforts to integrate DNS-01 providers. That's why I decided to switch to acme.sh.

Support for HTTP-01 validation is currently limited to the internal OPNsense provider. I plan to add support for more providers in the coming weeks.

This version lacks support for deploy/restart actions. Thus it can't automatically restart a service if a certificate was renewed. This will be addressed in a future release very soon.

# Quick start guide

#### 3b. Example: DNS-01 nslookup

004a
004b

#### 5a. Issue/Renew ALL certificates

006a

#### 5b. Issue/Renew a specific certificate

006b

### CODE REVIEW

**Comment by fraenki** [comment]
#6

**Comment by fichtner** [comment]
Merged, many many thanks for your work! <3

**Comment by AdSchellevis** [comment]
@fraenki nice work! Thanks!

**Comment by EugenMayer** [comment]
thank you @fraenki , awesome!

**Comment by fraenki** [comment]
@AdSchellevis I could need your help to add some JavaScript to hide GUI fields if they are not relevant, especially the "Validation" form is crowded with input fields and only some of them are useful at a time :)

**Comment by AdSchellevis** [comment]
@fraenki no problem, I saw there are quite some dns related fields, we might consider changing them to property value combinations as well. Next week I'll try to install it on my box and see what I can do about the JS part.

**Comment by lrosenman** [comment]
when I put a new name in for a certificate, it doesn't like a FQDN, therefore sending a bad CN=. 

What info do you need?

**Comment by fraenki** [comment]
@lrosenman Please open a new issue and provide some details on how to reproduce this problem.

**Comment by lrosenman** [comment]
done, #70

**Comment by zen2** [comment]
Is it possible to use this plugin to get a letencrypt certificate that is used for the firewall gui HTTPS access ?

**Comment by fraenki** [comment]
@zen2 Please use the [OPNsense forum](https://forum.opnsense.org/) or IRC channel to get your questions answered. :)

**Comment by BoardWatcher** [comment]
Using your plug-crashes OPNSense 17.1.  I just installed your plug-in and am trying to figure out how to use it.  Your short tutorial is not very clear to me and does not match the configuration settings in the current version. It would be appreciated if you would assist me.  I'm new to this.

Attached are the log files and the error contents when the OPNSense Server crashes.
[LetsEncrypt_Error.txt](https://github.com/opnsense/plugins/files/1684255/LetsEncrypt_Error.txt)

**Comment by fichtner** [comment]
Please update to 18.1 before reporting details. Both 17.1 and 17.7 are out of support.

**Comment by BoardWatcher** [comment]
Hi;
From my OPNSense Dashboard, I have the latest version available per the firmware update.  Version 18.1 is shown only as a 18.1rc, not a GA product yet and is only available to developers not general users.  How can OPNsense 17.7.12-amd64 be not supported when it is the absolutely the latest version available short of going to a beta version or a release candidate?

**Comment by fichtner** [comment]
check for updates again... there is 18.1.r2 and 18.1 now. You should see 17.7.12_1 as an intermediate step, which adds the end-of-life message and an upgrade possibility.


Cheers,
Franco

**Comment by fichtner** [comment]
PS: It's ok if you are on 17.7.12 to report issues as versions are not so far appart (17.1 would have been), but keep in mind that we do not ship fixes to this version. It would also be beneficial if you opened a new issue as this one was closed a year ago and does not fit the context of your request/report.

**Comment by BoardWatcher** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1517477298/6c8d9c14f024e2dc8178ec6f96c76aa7/39/26df6ae060f1a5dafcb06fd7fc571469/2ed3af5d163012a7b471f8bed9fb91c6/9efab2399c7c560b34de477b9aa0a465/newton.gif]Ok,

Will do after I upgrade.

Sent Digitally
Charles Naslund, CDR USNR RET, ASAE, BSCS, MBA
Charles@Naslund.nz<mailto:charles@naslund.nz>
via Newton Mail<https://cloudmagic.com/k/d/mailapp?ct=dw&cv=9.8.245&pv=10.0&source=email_footer_2>

On Thu, Feb 01, 2018 at 10:27pm, Franco Fichtner <notifications@github.com<mailto:notifications@github.com>> wrote:

PS: It's ok if you are on 17.7.12 to report issues as versions are not so far appart (17.1 would have been), but keep in mind that we do not ship fixes to this version. It would also be beneficial if you opened a new issue as this one was closed a year ago and does not fit the context of your request/report.

**Comment by fraenki** [comment]
Please open a [new issue](https://github.com/opnsense/plugins/issues) or use the [forum](https://forum.opnsense.org/) to further discuss potential bugs. :)
Please don't hijack ancient issues or pull-requests. :(

**Comment by BoardWatcher** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1517479799/6c8d9c14f024e2dc8178ec6f96c76aa7/39/26df6ae060f1a5dafcb06fd7fc571469/8320129d1e65e288df2da63305dba961/d852c7a657e4534f5b5ce2d63a80bdda/newton.gif]Frank;

Sorry, but I'm an noob and don't understand your language.  Hijacking what??  What is a pull-request?  I have an issue and need to report it here.  How do I do this?

Sent Digitally
Charles Naslund, CDR USNR RET, ASAE, BSCS, MBA
Charles@Naslund.nz<mailto:charles@naslund.nz>
via Newton Mail<https://cloudmagic.com/k/d/mailapp?ct=dw&cv=9.8.245&pv=10.0&source=email_footer_2>

On Thu, Feb 01, 2018 at 11:08pm, Frank Wall <notifications@github.com<mailto:notifications@github.com>> wrote:

Please open a new issue<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fopnsense%2Fplugins%2Fissues&data=02%7C01%7C%7Ccb784c7f24494c6f777108d5695bc415%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636530765202798514&sdata=C%2FPUO%2B9m003NvblQV1eiZfjqcERRvxJYfpQQfdSP%2BwI%3D&reserved=0> or use the forum<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fforum.opnsense.org%2F&data=02%7C01%7C%7Ccb784c7f24494c6f777108d5695bc415%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636530765202798514&sdata=ShXUQpNwaa2voMGW4va6GNQsreW27YI7lzwZTbCOiIY%3D&reserved=0> to further discuss potential bugs. :)
Please don't hijack ancient issues or pull-requests. :(

**Comment by BoardWatcher** [comment]
I've opened a new issue regarding this matter under 18.1.
Thank you for your assistance.

**Comment by Julien-nl** [comment]
just got it configured, thank you fraenki

**Comment by Nornode** [comment]
Turns out I had the same issue!
The trick is to have a proper domain (CN) in the CN field do not name it something random.
If you need to leave the "Alt names" field empty.

> Hi Fraenki,
> i've got this error
> 
> ```
> [Tue Jul 17 14:13:55 CEST 2018] | Please check log file for more details: /var/log/acme.sh.log
> -- | --
> [Tue Jul 17 14:13:55 CEST 2018] | _on_issue_err
> [Tue Jul 17 14:13:55 CEST 2018] | skip dns.
> [Tue Jul 17 14:13:55 CEST 2018] | _clearupdns
> [Tue Jul 17 14:13:55 CEST 2018] | No need to restore nginx, skip.
> [Tue Jul 17 14:13:55 CEST 2018] | pid
> [Tue Jul 17 14:13:55 CEST 2018] | Create domain key error.
> ```

**Comment by fraenki** [comment]
@Nornode, please don't hijack pull requests. Instead please post on the forums or open a new issue.

**Pull request merged**
