### PR TITLE
net-mgmt/zabbix-agent: add sudo rule to grant root permissions

### PR DESCRIPTION
**Pull request by fraenki**
As discussed in https://github.com/opnsense/core/issues/3777 this adds a static sudo rule for Zabbix Agent. I've added a small option so that this feature can be disabled, because it may be seen as a security risk.

(I've also took the opportunity to update the plugin's description.)

### CODE REVIEW

**Comment by fichtner** [comment]
Static rule but wrapped in a template. We really need more precautions to remove files we otherwise leave behind on deinstall.

**Comment by fraenki** [comment]
>We really need more precautions to remove files we otherwise leave behind on deinstall.

Yes, that would be useful I guess. Basically all files that are generated from templates should probably be removed on deinstall.

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/issues/46 I reopened

**Comment by fichtner** [comment]
FYI: I’m not going to release until the template revoke is in place.

**Pull request merged**
