### PR TITLE
net/vnstat: added yearly table to vnstat service

### PR DESCRIPTION
**Pull request by jamiew0w**
currently the vnstat service offers hourly/daily/monthly - vnstat tracks yearly too so why not.

marking as draft for now as i don't have a machine spare to test this on, might be a few days.

### CODE REVIEW

**Comment by mimugmail** [comment]
Thx, for me OK. Can you bump version in Makefile and add Changelog to pkg-descr too?

**Comment by jamiew0w** [comment]
> Thx, for me OK. Can you bump version in Makefile and add Changelog to pkg-descr too?

Done. As a note though I still haven't tested it myself and it may be a day or two before I can. If you want to test before then feel free :)

I don't foresee any issues, the code is already there, it's just some pretty minor changes.

**Review by fichtner — APPROVED** [review]

**Comment by fichtner** [comment]
Reopened and set to non-draft. Any complaints against merge @jamiew0w ? :)

**Review by mimugmail — APPROVED** [review]
Will test it next week, but fine for me :)

**Comment by jamiew0w** [comment]
@fichtner no complaints, definitely not. only a bit mad at myself that i haven't found time to properly test my own PR.

**Comment by mimugmail** [comment]
Works fine on my end:

image

If you want to test in your local instance, go via SSH:

```
pkg install git
git clone https://github.com/jamiew0w/plugins
cd plugins/net/vnstat
make upgrade
```

If you encounter some errors in code, fix via github and then in same directory
`git pull && make upgrade`

**Pull request merged**
