### PR TITLE
Fix README to get a valid markdown file

### PR DESCRIPTION
**Pull request by x-jokay**
Fix README to get a valid markdown file.

### CODE REVIEW

**Comment by fichtner** [comment]
It is supposed to work for github. some of it is automatically generated as well..

**Comment by x-jokay** [comment]
It works for Github, have a look [here](https://github.com/x-jokay/plugins/tree/redesign-README).

**Comment by fichtner** [comment]
I agree that it works, but having the new format will force contributors to spend more time formatting the page in the years to come so this is scaling into the wrong direction.

**Comment by x-jokay** [comment]
You really think inserting a line

```sh
| package/newpkg                               | My new package                                         |
```

takes **much** more time than inserting

```sh
* package/newpkg -- My new package
```

I don't think there will be package names exceeding `46 chars` or descriptions exceeding `63 chars` otherwise some shortening should be a good idea? :wink:

**Comment by fichtner** [comment]
"make list" returns the current list of plugins

**Pull request closed without merging**
