### PR TITLE
 net/reeradius: Cron for Start and Stop

### PR DESCRIPTION
**Pull request by clanto007**
Added description to Cron action so can be set a Cron Job to Start and Stop FreeRADIUS.

### CODE REVIEW

**Comment by mimugmail** [comment]
Isnt restart enough? Why do want to schedule start and stop?

**Comment by clanto007** [comment]
Because sometimes freeradius stop and doing a cron with start we can do a start command.
Doing restart stops it and restart it, with start if it's started it does nothing.

**Review by mimugmail — APPROVED** [review]
Ok for me

**Comment by clanto007** [comment]
@fichtner also this please, so I can publish another pull always for freeraduis.

**Comment by fichtner** [comment]
Although this is unusual and a bit weird, I have no technical objection if it's being used... thanks!

Cheers,
Franco

**Pull request merged**
