### PR TITLE
dns/unbound-plus: add whitelisting

### PR DESCRIPTION
**Pull request by mimugmail**
@fichtner I know you'll have a deeper look into dnsbl.sh :)

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks ❤️

**Comment by mimugmail** [comment]
Can you add the chmod to dnsbl.sh when times allow please :)

**Comment by fichtner** [comment]
Fixed that on Saturday 5edc3cfd1d077e

**Comment by mimugmail** [comment]
Hm, seems my branch was outdated, sorry&thx

**Pull request merged**
