### PR TITLE
net/haproxy: Fix "not all arguments converted during string formatting" in cert_sync

### PR DESCRIPTION
**Pull request by m-kozlowski**
fix for opnsense/plugins#4035

Workaround for this ligering issue is simple and well described, but it seems that noone has created a PR yet. So here it is.

### CODE REVIEW

**Comment by fraenki** [comment]
Merged, thanks!

**Comment by aque** [comment]
@fraenki will this make release 25.1? I think it would fix issue #4203 as well.

**Comment by fraenki** [comment]
It's already available in 24.7.11.

**Comment by aque** [comment]
I am running 24.7.11_2 and I do not see the updated `actions_haproxy.conf`.

**Comment by fraenki** [comment]
Oh, you're right. It was not synced to the 24.7 branch, that's unusual. But it will be in the final 24.7 stable or at least in 25.1(.0) then. Sorry about that.

**Comment by fichtner** [comment]
Wasn’t this merged to master right before 24.7.11 when builds were already finished?

**Comment by fraenki** [comment]
Dec 3, but no worries, I did not want to blame anyone. It's really not a big deal. :)

**Comment by aque** [comment]
No worries. I ran the consistency check in case I was working with an old version. 😆 It's all good. I'm looking forward to that patch.

**Pull request merged**
