### PR TITLE
Add proxy_max_temp_file_size

### PR DESCRIPTION
**Pull request by ibanezbass**
Based on http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size

### CODE REVIEW

**Comment by ibanezbass** [comment]
Based on http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size

**Comment by fabianfrz** [comment]
sorry - have not seen that one - just the one which has been closed. I made my own implementation in between.

**Comment by ibanezbass** [comment]
I had an issue with my source branch that required me to close and recreate the pull.

**Comment by fabianfrz** [comment]
I just packed it on #1302

**Pull request closed without merging**
