### PR TITLE
net/freeradius: add Service-Type to users

### LINKED ISSUE #1444: FreeRADIUS plugin feature request: user attributes
Hi! 
I apologize for my poor English.
In the web form "Services: FreeRADIUS: Users -> Edit User" there is a limited number of attributes. The administrator cannot add an arbitrary user attribute (Service-Type, Framed-Protocol, Reply-Message ... etc). 
Is it possible to add to the form "Edit User" a field to specify an arbitrary attribute? 
As on page "Services: FreeRADIUS: Users" - at the bottom of the "add" "delete" button. 
Clicking on "add" opens to fill in the field: attribute, operator, value; аllowing an administrator to assign an arbitrary attribute to a user.

### PR DESCRIPTION
**Pull request by mimugmail**
Closes #1444

### CODE REVIEW

**Comment by fichtner** [comment]
Is this free form type or can we predefine the values?

**Comment by mimugmail** [comment]
There are 19 predefined values, I can make a dropdown too https://www.iana.org/assignments/radius-types/radius-types.xhtml#radius-types-4

**Comment by fichtner** [comment]
Okay, either multi-select or integer validation with range 1 to 19. Both can be extended, multi-select is clearer for sure.

**Comment by mimugmail** [comment]
Going down for maintenance :)

**Pull request closed without merging**
