### PR TITLE
MDNS: add status indicator

### LINKED ISSUE #242: mdns-repeater: add status indicator

### PR DESCRIPTION
**Pull request by fabianfrz**
closes #242

### CODE REVIEW

**Comment by fichtner** [comment]
We should add this to the validation:

mdns-repeater: error: at least 2 interfaces must be specified

**Comment by fichtner** [comment]
FYI https://github.com/opnsense/plugins/commit/49f860905b398775753ad5c3644af333634b370a

**Comment by fabianfrz** [comment]
@fichtner what should we do because of the model?

afaik it is not possible to run migrations on data which does not exist

**Comment by fichtner** [comment]
migration on data that not exists should work fine. it is for filling a set of default values.

**Comment by fichtner** [comment]
have you not set a default for interfaces maybe? ;)

**Comment by fabianfrz** [comment]
https://github.com/opnsense/plugins/blob/master/net/mdns-repeater/src/opnsense/mvc/app/models/OPNsense/MDNSRepeater/MDNSRepeater.xml#L10-L13

It has no default and it should not (I don't know how a user calls his networks - so this would be guessing random values)

**Comment by fichtner** [comment]
Then can't set to required, it's an impossible condition. IDS defaults to lan for that reason.

**Comment by fabianfrz** [comment]
does lan always exist?

**Comment by fichtner** [comment]
no, but it doesn't matter. we should simply make sure the validation works in the enforced defaults.

it's even trickier here: we would have to assume lan,opt1. it's not pretty, but then it would work in the most default cases hitting "enable" and apply :)

**Comment by fichtner** [comment]
the other thing would be to remove required

**Comment by fabianfrz** [comment]
the required must stay as the configuration is invalid without the interface name. So I will add a default of lan in the hope that it will work.

**Comment by fichtner** [comment]
ok 👍

**Comment by fabianfrz** [comment]
added it directly to master

**Pull request merged**
