### PR TITLE
Fix for Sidebar Line - various updates

### PR DESCRIPTION
**Pull request by marjohn56**
Added fix for sidebar line ( thanks René ). Updated scss to match opnsense theme changes.

### CODE REVIEW

**Comment by fichtner** [comment]
@marjohn56 I missed this, is it still relevant? René pushed some changes in the meantime.

**Comment by marjohn56** [comment]
Dunno, did he push changes for rebellion?

**Comment by marjohn56** [comment]
Cannot see the line anymore so I guess it's sorted.

**Comment by fichtner** [comment]
ok, thanks 👍

**Pull request closed without merging**
