### PR TITLE
Bump Zerotier

### PR DESCRIPTION
**Pull request by dharrigan**
Upgrade to 1.4.6

### CODE REVIEW

**Comment by mimugmail** [comment]
This is only the plugin version, not the package.

**Comment by dharrigan** [comment]
Hi,

Yes, that's right. I didn't make it clear in my message - sorry! It's a bump of Zerotier package to 1.4.6, not the plugin version. Thanks @mimugmail !

**Comment by mimugmail** [comment]
You can safely close this PR, @fichtner is watching every update on used packages and sync them.
You can have a look here:
https://github.com/opnsense/ports/blob/master/net/zerotier/Makefile

**Comment by dharrigan** [comment]
Closed as per above.

**Pull request closed without merging**
