### PR TITLE
Rebellion theme update

### PR DESCRIPTION
**Pull request by marjohn56**
This commit adds the external CSS files such as nv.d3.css to the rebellion css folder. With a commit in the core I am about to do this will fix all external references EXCEPT the ones in the *gateways*.php files.

There are also a couple of minor color changes that make items more legible.

Even without the core commit this update should be pulled as the added css files will have no effect without the core pull, but they will be needed when that happens.

### CODE REVIEW

**Comment by fichtner** [comment]
Going to defer this to @AdSchellevis which will be back next week.

I like this direction, but I think that we need to do something about the larger font files (not relevant in the context of this commit). Not sure what that is yet... :)

**Comment by fabianfrz** [comment]
@fichtner Unmodified font files can be included from the base theme OR a symbolic link can be used.

**Comment by fabianfrz** [comment]
@marjohn56 opnsense/core#2139 should fix some of your gateway issues.

**Comment by fabianfrz** [comment]
@marjohn56 can you try to run the following command (to install the widget patch for testing - it is the PR mentioned above):
```sh
opnsense-patch 9d8e53e
```

**Comment by marjohn56** [comment]
I get this... :)

image

**Comment by marjohn56** [comment]
just status_gateways.php to be fixed and looks like a job done.

**Comment by fabianfrz** [comment]
@marjohn56 Page should be fixed in the PR GitHub shows above.

**Comment by marjohn56** [comment]
These have been updated since, closing this PR.

**Pull request closed without merging**
