### PR TITLE
net/haproxy: Avoid duplicate port option (linked to commit new option…

### PR DESCRIPTION
**Pull request by manusfreedom**
… "checkport" for health checks SHA-1: f14eebe9e2e97edf790d5616d3650aca1bfcb812)

### CODE REVIEW

**Comment by fichtner** [comment]
@fraenki seems to be on vacation at the moment, this could take a little longer

Thanks for your submission 👍

**Comment by fraenki** [comment]
Looks good to me! And good catch, btw.

@fichtner Please merge :)

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by fraenki** [comment]
@fichtner There are no other changes pending on my side, so feel free to bump version.

**Comment by fichtner** [comment]
done :)

**Pull request merged**
