### PR TITLE
Replace nocoin-justdomains.txt with the original CoinBlockerLists

### PR DESCRIPTION
**Pull request by ZeroDot1**
Hi @mimugmail,
I replaced the list because CoinBlockerLists are more up-to-date and contain some URLs more than other lists, and poor copies of CoinBlockerLists.

CoinBlockerLists Homepage: 
https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html

If necessary, there are also other lists on the homepage see:
https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html

If you have any questions please let [me](https://twitter.com/zero_dot1?lang=en) know.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
unbound plus is moved into core, only merges to the master branch are considered for adoption.

**Comment by ZeroDot1** [comment]
For me it all looks a bit messed up, in which repository should I put it?

**Comment by fichtner** [comment]
https://github.com/opnsense/core

**Comment by ZeroDot1** [comment]
Please change it yourself, this is a unique mess (I could not find the corresponding file directly.). It is no fun to contribute here.

**Comment by ZeroDot1** [comment]
It is not against any of you, but the project should be sorted in a consistent way. Such a mess simply makes no sense.

Sorry.

**Comment by fichtner** [comment]
Fair enough ;)

**Pull request closed without merging**
