### PR TITLE
www/nginx: insert correct SNI name. Add hook

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
Just corrected version of https://github.com/opnsense/plugins/pull/1991
also added a hook for post-conf.
fixes https://github.com/opnsense/plugins/issues/2006
Thanks!

### CODE REVIEW

**Comment by kulikov-a** [comment]
@fabianfrz 
hi.
look at this please

**Review by fabianfrz — APPROVED** [review]

**Comment by kulikov-a** [comment]
@fabianfrz 
thanks!

**Comment by kulikov-a** [comment]
@fabianfrz @fichtner 
is it probably better to wait for the https://github.com/opnsense/plugins/pull/2149 merge and fix the versions conflict?

**Comment by kulikov-a** [comment]
since https://github.com/opnsense/plugins/pull/2149 is stuck, trying to make it ready for review again

**Review by fichtner — APPROVED** [review]

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by kulikov-a** [comment]
@fichtner thanks!!

**Pull request merged**
