### PR TITLE
security/acme-client: Add Support for Lima-City DNS API 

### PR DESCRIPTION
**Pull request by laraveluser**
Integration for Lima-City DNS-API; cf. pull request at https://github.com/acmesh-official/acme.sh/pull/4757

### CODE REVIEW

**Comment by fraenki** [comment]
The acme.sh PR was not merged yet. We'll have to wait until the PR is merged _and_ we'll need a new release of acme.sh that includes this new feature. Afterwards we'll continue here and add this feature to Acme-Client.

**Comment by laraveluser** [comment]
> The acme.sh PR was not merged yet. We'll have to wait until the PR is merged _and_ we'll need a new release of acme.sh that includes this new feature. Afterwards we'll continue here and add this feature to Acme-Client.

The merge is now complete

**Comment by fraenki** [comment]
Progress! :) Now we're waiting for a new release of acme.sh...

**Comment by feroxib** [comment]
> Progress! :) Now we're waiting for a new release of acme.sh...

...which we finally got a few days ago 👌

**Review by fraenki — APPROVED** [review]

**Comment by fraenki** [comment]
Merged, thanks!

**Pull request merged**
