### PR TITLE
mail/postfix: Duplicate Message Fix, Milter Default Action Choice and Recipient Address Verification

### PR DESCRIPTION
**Pull request by windgmbh**
## (Really) Fix Duplicate Message Issue #1591

Issue #1591 concerning duplicate E-Mails was not fixed, because it was anticipated that Postfix 'milter_protocol' version would specify the IP version. Instead this specifies the [version of Sendmail's Milter Protocol](http://www.postfix.org/postconf.5.html#milter_protocol), which in Postfix+Rspamd's case should always be version 6.

To really fix the issue I have set Postfix', Rspamd Proxy's and Rspamd Worker's Connection to Unix Sockets. Because in OPNsense Postfix and Rspamd are set up to run on the same host, there is really no need to use TCP-Connections, which makes this the most ideal solution. 

```
Postfix ---/var/run/rspamd/milter.sock---> Rspamd Proxy Worker ---/var/run/rspamd/normal.sock---> Rspamd Normal Worker 
```

## Add `milter_default_action` choice
At the moment, if Rspamd becomes unavailable to Postfix, Postfix will accept the message. I have added a choice to use the 'tempfail' action. With this one, a 4xx Status Code is given until Rspamd becomes available again. 
This would prevent for example that a overloaded system would accept all (spam) messages. 

## Delete Milter Macros
Rspamd's [documentation](https://rspamd.com/doc/integration.html#configuring-postfix) does not require to add milter macros in Postfix' configuration anymore, because the Milter Protocol Version 6 is fully supported. 

## Add Recipient Address Verification
I have added a choice to enable Postfix' Recipient Address Verification. Although this may but a little bit more load onto the next SMTP hop, this may be a desired feature for many users. #1926 
Although there [some limitations](http://www.postfix.org/ADDRESS_VERIFICATION_README.html#limitations) of this feature, this is certainly something that a user should be able to choose.

### CODE REVIEW

**Comment by windgmbh** [comment]
Do I have to ask for a review manually/ explicitly? Since it is about `postfix` and `rspamd` probably @mimugmail and @fabianfrz need to review it? Thanks a lot!

**Comment by fichtner** [comment]
@mimugmail has to review, still a few days of vacation for him :)

**Comment by mimugmail** [comment]
Two things:

- This PR handles 2 plugins with 2 owners, for me it's ok 
- We added the choice for both protocols since for some it worked with 4 and some with 6. This would stick to socket-only, correct?

**Comment by windgmbh** [comment]
Hey @mimugmail 

thank you very much for looking at my request. I hope you had a nice vacation. 

## Milter protocol version

> it worked with 4 and some with 6

The choice of `milter_protocol` should not make any difference to the user. A major change from Milter protocol version `4` to version `6` is the [introduction of a `EOH` (End of Headers)](http://www.postfix.org/MILTER_README.html) milter stage. Otherwise they should be fully compatible to each other.
Rspamd recommends Milter version `6` in it's documentation [since May 2015](https://github.com/rspamd/rspamd.com/commit/4531952feb1794ed73308e64c151679d68063cb7#diff-bfeaac07cecb93ab472ed53e8744dc0f45f00f31423517c958535ae9ea48a29d). 
A reason to use an older milter protocol would be that a milter (Rspamd) would not support it. This choice would only change Postfix' behaviour which milter macros will be sent (and when). Because Rspamd supports all of those for a very long time, I decided to remove the setting completely, because it just introduces confusion while serving no purpose.

## Unix-socket only?

> This would stick to socket-only, correct?

The Rspamd Worker's configuration [would allow to listen on multiple interfaces](https://rspamd.com/doc/workers/), if that would be required. For a system that is running `postfix` and `rspamd` locally, I see no purpose in doing so:
* `postfix` will use the Rspamd Proxy Worker's socketfile when it is configured to do so. 
* Rspamd Proxy Workers (`milter.sock`) will contact Rspamd Normal Worker (`normal.sock`) through the socket connection as well. 

*There could be a quite theoretical use case, where someone uses remote clients to talk to a local Rspamd process on a OPNsense system. For that specific case, it may be suitable for Rspamd processes to listen on TCP ports as well.*

For the local Postfix however I would really recommend to use a socket connection, because it removes the confusion between IPv4/ IPv6 protocols that produces issue #1591. If we would allow TCP listeners to be configured, we should of course add a IP protocol choice *for real* now. 
That would add some complexity for a probably non-existent use case. 

If you would otherwise be uncomfortable, I will add it to the pull request.

**Comment by mimugmail** [comment]
I installed your branch but it throws templating errors. Didn't you get them during your tests?


```

root@OPNsense:~/wind # git clone https://github.com/windgmbh/plugins
Cloning into 'plugins'...
remote: Enumerating objects: 44265, done.
remote: Total 44265 (delta 0), reused 0 (delta 0), pack-reused 44265
Receiving objects: 100% (44265/44265), 8.73 MiB | 3.05 MiB/s, done.
Resolving deltas: 100% (17217/17217), done.
root@OPNsense:~/wind # cd plugins/mail/postfix/make upgrade
cd: Too many arguments.
root@OPNsense:~/wind # cd plugins/mail/postfix/
root@OPNsense:~/wind/plugins/mail/postfix # make upgrade
>>> Generating metadata for os-postfix-devel-1.18... done
>>> Staging files for os-postfix-devel-1.18... done
>>> Packaging files for os-postfix-devel-1.18:
file sizes/checksums    [82]: 100%
packing files           [82]: 100%
packing directories      [0]: 100%
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
        os-postfix-devel: 1.17

Number of packages to be removed: 1
[1/1] Deinstalling os-postfix-devel-1.17...
[1/1] Deleting files for os-postfix-devel-1.17: 100%
Reloading plugin configuration
Installing os-postfix-devel-1.18...
Extracting os-postfix-devel-1.18: 100%
Stopping configd...done
Starting configd.
Migrated OPNsense\Postfix\Antispam from 1.0.1 to 1.0.2
Keep version OPNsense\Postfix\Domain (1.0.1)
Migrated OPNsense\Postfix\General from 1.2.4 to 1.2.5
Keep version OPNsense\Postfix\Headerchecks (1.0.0)
Keep version OPNsense\Postfix\Recipient (1.0.0)
Keep version OPNsense\Postfix\Recipientbcc (1.0.0)
Keep version OPNsense\Postfix\Sender (1.0.0)
Keep version OPNsense\Postfix\Senderbcc (1.0.0)
Keep version OPNsense\Postfix\Sendercanonical (1.0.0)
Keep version OPNsense\Postfix\Address (1.0.0)
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Postfix: Execute error
Reloading template OPNsense/Syslog: OK


```


```
Jan  6 07:08:57 OPNsense.localdomain configd.py[34218]: [85f388fa-d4d2-4038-a59c-245becf4b4a4] generate template OPNsense/Postfix
Jan  6 07:08:57 OPNsense.localdomain configd.py[34218]: generate template container OPNsense/Postfix
Jan  6 07:08:57 OPNsense.localdomain configd.py[34218]: [85f388fa-d4d2-4038-a59c-245becf4b4a4] Inline action failed with OPNsense/Postfix OPNsense/Postfix/main.cf Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'. at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/template.py", line 247, in _generate     j2_page = self._j2_env.get_template(template_filename)   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template     return self._load_template(name, self.make_globals(globals))   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template     template = self.loader.load(self, name, globals)   File "/usr/local/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load     code = environment.compile(source, name, filename)   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile     self.handle_exception(source=source_hint)   File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception     reraise(*rewrite_traceback_stack(source=source))   File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise     raise value.with_traceback(tb)   File "/usr/local/opnsense/service/modules/../templates/OPNsense/Postfix/main.cf", line 209, in template     {% endif %} jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 506, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 341, in generate     raise render_exception   File "/usr/local/opnsense/service/modules/template.py", line 332, in generate     for filename in self._generate(template_name, create_directory):   File "/usr/local/opnsense/service/modules/template.py", line 249, in _generate     raise Exception("%s %s %s" % (module_name, template_filename, templExc)) Exception: OPNsense/Postfix OPNsense/Postfix/main.cf Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

```

**Comment by windgmbh** [comment]
Somehow a Jinja Syntax Error might have ended up in the final `mail/postfix: Add Recipient Address Verification` commit, that I have rectified now.

I ran the tests again and have gotten these results:

## Build Log

<details>

<p>

```
>>> Generating metadata for os-postfix-devel-1.18... done
>>> Staging files for os-postfix-devel-1.18... done
>>> Packaging files for os-postfix-devel-1.18:
file sizes/checksums    [82]: 100%
packing files           [82]: 100%
packing directories      [0]: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	os-postfix: 1.17

Number of packages to be removed: 1
[1/1] Deinstalling os-postfix-1.17...
[1/1] Deleting files for os-postfix-1.17: 100%
Reloading plugin configuration
Installing os-postfix-devel-1.18...
Extracting os-postfix-devel-1.18: 100%
Stopping configd...done
Starting configd.
Migrated OPNsense\Postfix\Antispam from 1.0.1 to 1.0.2
Keep version OPNsense\Postfix\Domain (1.0.1)
Migrated OPNsense\Postfix\General from 1.2.4 to 1.2.5
Keep version OPNsense\Postfix\Headerchecks (1.0.0)
Keep version OPNsense\Postfix\Recipient (1.0.0)
Keep version OPNsense\Postfix\Recipientbcc (1.0.0)
Keep version OPNsense\Postfix\Sender (1.0.0)
Keep version OPNsense\Postfix\Senderbcc (1.0.0)
Keep version OPNsense\Postfix\Sendercanonical (1.0.0)
Keep version OPNsense\Postfix\Address (1.0.0)
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Postfix: OK
Reloading template OPNsense/Syslog: OK

>>> Generating metadata for os-rspamd-devel-1.11... done
>>> Staging files for os-rspamd-devel-1.11... done
>>> Packaging files for os-rspamd-devel-1.11:
file sizes/checksums    [40]: 100%
packing files           [40]: 100%
packing directories      [0]: 100%
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 1 packages (of 0 packages in the universe):

Installed packages to be REMOVED:
	os-rspamd: 1.10

Number of packages to be removed: 1
[1/1] Deinstalling os-rspamd-1.10...
[1/1] Deleting files for os-rspamd-1.10: 100%
Reloading plugin configuration
Installing os-rspamd-devel-1.11...
Extracting os-rspamd-devel-1.11: 100%
Stopping configd...done
Starting configd.
Keep version OPNsense\Rspamd\RSpamd (1.0.2)
Reloading plugin configuration
Configuring system logging...done.
Reloading template OPNsense/Rspamd: OK
```
</p>
</details>

## Results

After applying new options in the GUI.

### Postfix

<details>
<summary>main.cf (excerpt)</summary>
<p>

```
smtpd_milters = unix:/var/run/rspamd/milter.sock
non_smtpd_milters = $smtpd_milters
milter_protocol = 6
milter_default_action = tempfail

smtpd_recipient_restrictions = reject_unknown_sender_domain, reject_unknown_recipient_domain, reject_non_fqdn_sender, reject_non_fqdn_recipient, permit_mynetworks, reject_unauth_destination, reject_unverified_recipient
```
</p>
</details>

### Rspamd

<details>
<summary>local.d/worker-normal.inc</summary>
<p>

```
upstream "local" {
  default = yes;
  hosts = "/var/run/rspamd/normal.sock";
}
bind_socket = "/var/run/rspamd/milter.sock mode=0666 owner=rspamd";
```
</p>
</details>

<details>
<summary>local.d/worker-normal.inc</summary>
<p>

```
bind_socket = "/var/run/rspamd/normal.sock mode=0666 owner=rspamd";
```
</p>
</details>

---

Sorry for my bad development attitude. I promise that I will do better next time. 

How is your opinion on listening on TCP4/ TCP6 ports? If you think it is necessary, I will add it as an option.

**Comment by mimugmail** [comment]
I installed your branch now on my test system, I'll have a look at it the next days. Looks good now.
No opinion yet :)

**Comment by fabianfrz** [comment]
I count @mimugmail as a maintainer of rspamd as well. He can approve that as well.

**Comment by windgmbh** [comment]
I may add that I am running the Unix Socket configuration (4fe003b) on a production system since mid November, because the issue with duplicate messages had to be fixed immediately. So at least for my setup it can be considered as thoroughly tested by now.

---

Concerning Unix sockets another though came to my mind: Even though the Redis connection does not cause any problems with TCP connections, it could be more consistent to use Unix sockets for the Redis connections as well. 

Redis is already configured to have a socket file in `/var/run/redis/redis.sock`, but has the wrong permissions (`700`) at the moment. 

```
$ ls -l /var/run/redis/redis.sock 
srwx------  1 redis  redis  0 Jan 12 16:02 /var/run/redis/redis.sock
```

In order to work, we could either set permissions to (`777`) or to `770` while adding the `rspamd` user to the `redis` group. 
I don't expect that to be a security risk compared to the current configuration, because the Redis connection is already exposed on a local TCP port for all local processes to communicate with. 

While this is, strictly speaking, not required to fix the issue with issue with duplicate messages, it may be better for from a design standpoint to use Unix socket for everything that has to do with `rspamd`.

---

If this is a change that you would favour as well, I could: 
1. add this to this pull request
2. open a new pull request.

Please let me know, what way you would prefer.

**Review by mimugmail — APPROVED** [review]
If there is no merge conflict, I'm OK with one PR over two plugins. Works one my end. Thanks :)

**Comment by fichtner** [comment]
Merged, thanks! ❤️

**Pull request merged**
