### PR TITLE
security/acme-client: feature & bugfix release

### PR DESCRIPTION
**Pull request by fraenki**
## New features
- Full integration with our HAProxy plugin (automatically injects configuration)
- Support for restart actions (pre-defined, configd commands and custom commands)

## Bugfixes
- Fix for #70: relax field validations for many input fields (name, description, altNames)
- Fix search fields
- Fix forceful re-issue of certificates (required if altNames was changed)
- Fix DNS-01 ISPconfig option (should be a checkbox)
- Respect if an item is disabled
- Do not expose lighttpd version
- Improve some help messages

### 1. Enable HAProxy Integration
**And don't forget to click the "Apply" button... :-)**

le000

### 2. Configure Validation Method
le001

**Be sure to select your HAProxy frontends:**

le002

### 3. Configure Restart Action

le003

### 4. Configure Certificate
Now select the "validation method" and "restart action" for your certificate:
le004

### CODE REVIEW

**Comment by fraenki** [comment]
@fitch: The new HAProxy integration requires the new dependency (a725776). Any objections?

**Comment by fichtner** [comment]
erm, yes... this doesn't look good, because it will also pull in haproxy and lua. where's the friction in the code between haproxy installed and not installed?

**Comment by fraenki** [comment]
@fichtner Currently there is nothing in the code to handle an absent haproxy plugin. It assumes that HAProxy is just there. Is there a command in the backend available to query the currently installed packages?

**Comment by fichtner** [comment]
@fraenki we'll have to add it if not there, let's talk this afternoon about how

**Comment by fraenki** [comment]
@fichtner I've removed the hardcoded dependency to our HAProxy plugin and disable HAProxy integration by default now.

**Comment by fraenki** [comment]
@fichtner I've added two more bugfixes. I promise these are the last ones for this release. :)

**Comment by fichtner** [comment]
Merged,thanks! :)

**Comment by lrosenman** [comment]
Fixed my issue, and we're happily using LE cert for the FW. (#70)

**Pull request merged**
