### PR TITLE
dns/bind: enhance allow transfer

### PR DESCRIPTION
**Pull request by iongchun**
- Make "Allow Transfer" and "Allow Query" configuration available to slave zones
- Add "Allow Transfer" to General page for default / fallback

### CODE REVIEW

**Comment by iongchun** [comment]
Fixes #1813

**Comment by mimugmail** [comment]
@fraenki you added the part with slave zone to hide specific settings, is this PR ok for you? 
I don't run it as a slave ..

**Comment by mimugmail** [comment]
@fraenki Did you already find the time to have a look

**Comment by fraenki** [comment]
@mimugmail Ooops, I wasn't aware that this PR is waiting for me to respond. Sorry about that.

**Review by fraenki — APPROVED** [review]

**Comment by fraenki** [comment]
@iongchun Merged, thanks!

**Pull request merged**
