### PR TITLE
Update to bgpd.conf templating

### LINKED ISSUE #171: Quagga/BGP: Deleting of related object create an error in the template
Hi,

with the new addition of route-maps and prefix-lists you can link them to the specific neighbors. 
When you delete a prefix-list and press save without deleting the list in the neighbor config, line gets into the config. Within the UI the prefix-list is gone, also when editing the neighbor it's gone, but you have to save the neighbor to completely remove it.

Generated config after deletion looks like:

```
router bgp 65553
 network 10.55.55.0/24
 neighbor 1.1.1.1 remote-as 65333
 neighbor 1.1.1.1 prefix-list  in

``` 
Between prefix-list and in should be the name of it. Now the restart of quagga fails.

The template looks like:

https://github.com/opnsense/plugins/blob/master/net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L30-L37

It seems that the if clause checking for content doesn't work, because when I add some debugs:

https://github.com/mimugmail/plugins/blob/master/net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L33-L36

I get:

```
router bgp 65553
 network 10.55.55.0/24
 neighbor 1.1.1.1 remote-as 65333
 neighbor 1.1.1.1 prefix-list  in
 prefixlist2_data
 {}

```
So prefixlist2_data is empty but it gets set altough is set:

https://github.com/opnsense/plugins/blob/master/net/quagga/src/opnsense/service/templates/OPNsense/Quagga/bgpd.conf#L33

Any idea @fabianfrz @fichtner why this wont get caught?

Thanks!

P.S.: This seems to be the only thing I've found with the new code ...

### PR DESCRIPTION
**Pull request by mimugmail**
This one fixes #171 

Small update to the if clause.

Please only merge into master, I'm still searching for more errors ... 

@fabianfrz @fichtner please review.

### CODE REVIEW

**Comment by mimugmail** [comment]
@fichtner @fabianfrz Is there something stopping this PR to get merged?

**Comment by fabianfrz** [comment]
@mimugmail yes: you added commits so we don't know when it is ready. Should I merge it?

**Comment by mimugmail** [comment]
Oh, sorry, you're right. Yes please merge! 👍

**Comment by fabianfrz** [comment]
@mimugmail done

**Pull request merged**
