### PR TITLE
NET/FRR: Add OSPFv3 Firewall Rules to Floating Ruleset

### PR DESCRIPTION
**Pull request by billgertz**
Wrote a first stab at firewall floating rule generation based on the OSPF() model already encoded in the frr.inc. This can probably be made more efficient by:

- Rolling the interfaces together into each rule (I'll keep researching, I'm guessing an array of string?)
- Using direction as 'both' (I don;t see any examples of that in the code base, hmmm?)

If I've stepped on any toes please let me know. I'll happily mend my ways.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@billgertz you probably need to rebase your branch, there's some acme stuff in there now.

**Comment by billgertz** [comment]
Crap garbage in my fork, closing.

**Comment by billgertz** [comment]
@AdSchellevis Thanks for letting me know. Tried to rebase and was stuck in resolution hell. Then I realized I didn't care about the old fork and just started fresh. A [new clean PR](https://github.com/opnsense/plugins/pull/3530) has been created. So far, my trial change is working on 23.7 without issues. This is going to need more testing.

**Comment by AdSchellevis** [comment]
@billgertz no problem, I'll try to take a look at the other PR

**Pull request closed without merging**
