### PR TITLE
Update fetchmailrc

### PR DESCRIPTION
**Pull request by mr44er**
deleted 1 space and changed sslproto to ssl
https://github.com/opnsense/plugins/issues/2532#issuecomment-918407189

### CODE REVIEW

**Comment by mimugmail** [comment]
Looks good, seems the syntax changed.
Would you mind bumping version in Makefile?

**Comment by mr44er** [comment]
I don't know how or where to do that. This was my first pull request... :/

**Comment by fichtner** [comment]
https://github.com/opnsense/plugins/blob/3bc072ad9cc6b0789a591cc1285d7e43a70ac197/mail/fetchmail/Makefile#L2

**Review by mimugmail — APPROVED** [review]
Looks good, thank you :)

**Review by fichtner — APPROVED** [review]

**Comment by fichtner** [comment]
Congrats on your first PR. Merged, thanks!

**Pull request merged**
