### PR TITLE
WIP net/frr: Add BGP password support

### PR DESCRIPTION
**Pull request by mimugmail**
Currently only supports v4 as it is a base for discussion first.
As discusses with @AdSchellevis we should do this right from the beginning as it interacts with setkey/SPD and IPsec.
The current approach only adds and deletes the line without any flushing. To me this looks ok so far.

Also adding @g-a-c for feedback if interested.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@mimugmail if you have the time and spirit to provide a test setup or an easy to install test config, that would be practical. As discussed I do want to dig into the `setkey` challenge to avoid future hard to fix disappointments in relation to IPsec.

**Comment by mimugmail** [comment]
@AdSchellevis I finished my lab, shall we arrange a teams via IRC the next days as discussed last month (time flies ...)?

**Comment by AdSchellevis** [comment]
@mimugmail sure, just ping me on irc.

**Comment by mmack** [comment]
Any update on this?

**Comment by AdSchellevis** [comment]
refactored setkey in https://github.com/opnsense/plugins/pull/2800

**Pull request closed without merging**
