### PR TITLE
mail/postfix: Add TLS compatibility modes

### PR DESCRIPTION
**Pull request by windgmbh**
## Issue 

The default TLS client/ server configurations of `mail/postfix` are not really up to the best practices anymore.

## My solution

Therefore I have added three compatibility modes:

* Old
* Intermediate
* Modern

for both `smtpd` (server) and `smtp` (client). I configured those different compatibility levels according to [Mozilla's TLS configuration recommendations](https://ssl-config.mozilla.org/#server=postfix) for Postfix.
With those, the user is easily able to choose between different compatibility levels depending on particular requirements/ philosophy regarding backwards compatibility. 

## Results

The results for different compatibility levels for `smtpd` look quite promising: 

<details>
<summary>Old compatibility</summary>
<p>

```
$ sslyze --starttls=smtp opnsense.local:25

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   opnsense.local:25                        => opnsense.local




 SCAN RESULTS FOR opnsense.local:25 - opnsense.local
 ---------------------------------------------

[...]

 * SSL 3.0 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * SSL 2.0 Cipher Suites:
     Attempted to connect using 7 cipher suites; the server rejected all cipher suites.

 * TLS 1.2 Cipher Suites:
     Attempted to connect using 156 cipher suites.

     The server accepted the following 18 cipher suites:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA256                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA                      256                      
        TLS_RSA_WITH_AES_128_GCM_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA                      128                      
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256       256       ECDH: X25519 (253 bits)
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384             256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             128       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256             128       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                128       ECDH: prime256v1 (256 bits)
        TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256         256       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               256       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_256_CBC_SHA256               256       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               128       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_128_CBC_SHA256               128       DH (2048 bits) 

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported


 * Certificates Information:
       Hostname sent for SNI:             opnsense.local
       Number of certificates detected:   1

 * TLS 1.1 Cipher Suites:
     Attempted to connect using 80 cipher suites.

     The server accepted the following 4 cipher suites:
        TLS_RSA_WITH_AES_256_CBC_SHA                      256                      
        TLS_RSA_WITH_AES_128_CBC_SHA                      128                      
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                128       ECDH: prime256v1 (256 bits)

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported


 * Deflate Compression:
                                          OK - Compression disabled

 * TLS 1.0 Cipher Suites:
     Attempted to connect using 80 cipher suites.

     The server accepted the following 4 cipher suites:
        TLS_RSA_WITH_AES_256_CBC_SHA                      256                      
        TLS_RSA_WITH_AES_128_CBC_SHA                      128                      
        TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA                256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA                128       ECDH: prime256v1 (256 bits)

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported


 * ROBOT Attack:
                                          OK - Not vulnerable.

 * OpenSSL Heartbleed:
                                          OK - Not vulnerable to Heartbleed

 * TLS 1.2 Session Resumption Support:
      With Session IDs: NOT SUPPORTED (0 successful resumptions out of 5 attempts).
      With TLS Tickets: OK - Supported.

 * Session Renegotiation:
       Client Renegotiation DoS Attack:   VULNERABLE - Server honors client-initiated renegotiations
       Secure Renegotiation:              OK - Supported

 * TLS 1.3 Cipher Suites:
     Attempted to connect using 5 cipher suites.

     The server accepted the following 3 cipher suites:
        TLS_CHACHA20_POLY1305_SHA256                      256       ECDH: X25519 (253 bits)
        TLS_AES_256_GCM_SHA384                            256       ECDH: X25519 (253 bits)
        TLS_AES_128_GCM_SHA256                            128       ECDH: X25519 (253 bits)


 * OpenSSL CCS Injection:
                                          OK - Not vulnerable to OpenSSL CCS injection

 * Elliptic Curve Key Exchange:
       Supported curves:                  X25519, X448, prime256v1, secp384r1, secp521r1
       Rejected curves:                   prime192v1, secp160k1, secp160r1, secp160r2, secp192k1, secp224k1, secp224r1, secp256k1, sect163k1, sect163r1, sect163r2, sect193r1, sect193r2, sect233k1, sect233r1, sect239k1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1

 * Downgrade Attacks:
       TLS_FALLBACK_SCSV:                 OK - Supported


 SCAN COMPLETED IN 8.58 S
 ------------------------
```
</p>
</details>

<details>
<summary>Intermediate compatibility</summary>
<p>

```
$ sslyze --starttls=smtp opnsense.local

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   opnsense.local                        => opnsense.local 




 SCAN RESULTS FOR opnsense.local:25 - opnsense.local
 ---------------------------------------------

[...]

 * TLS 1.0 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * TLS 1.2 Session Resumption Support:
      With Session IDs: NOT SUPPORTED (0 successful resumptions out of 5 attempts).
      With TLS Tickets: OK - Supported.

 * Session Renegotiation:
       Client Renegotiation DoS Attack:   VULNERABLE - Server honors client-initiated renegotiations
       Secure Renegotiation:              OK - Supported

 * TLS 1.2 Cipher Suites:
     Attempted to connect using 156 cipher suites.

     The server accepted the following 5 cipher suites:
        TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256       256       ECDH: X25519 (253 bits)
        TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384             256       ECDH: prime256v1 (256 bits)
        TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256             128       ECDH: prime256v1 (256 bits)
        TLS_DHE_RSA_WITH_AES_256_GCM_SHA384               256       DH (2048 bits) 
        TLS_DHE_RSA_WITH_AES_128_GCM_SHA256               128       DH (2048 bits) 

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    OK - Supported
       Legacy RC4 Algorithm               OK - Not Supported


 * Deflate Compression:
                                          OK - Compression disabled

 * OpenSSL Heartbleed:
                                          OK - Not vulnerable to Heartbleed

 * SSL 2.0 Cipher Suites:
     Attempted to connect using 7 cipher suites; the server rejected all cipher suites.

 * TLS 1.3 Cipher Suites:
     Attempted to connect using 5 cipher suites.

     The server accepted the following 3 cipher suites:
        TLS_CHACHA20_POLY1305_SHA256                      256       ECDH: X25519 (253 bits)
        TLS_AES_256_GCM_SHA384                            256       ECDH: X25519 (253 bits)
        TLS_AES_128_GCM_SHA256                            128       ECDH: X25519 (253 bits)


 * Elliptic Curve Key Exchange:
       Supported curves:                  X25519, X448, prime256v1, secp384r1, secp521r1
       Rejected curves:                   prime192v1, secp160k1, secp160r1, secp160r2, secp192k1, secp224k1, secp224r1, secp256k1, sect163k1, sect163r1, sect163r2, sect193r1, sect193r2, sect233k1, sect233r1, sect239k1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1

 * Downgrade Attacks:
       TLS_FALLBACK_SCSV:                 OK - Supported

 * ROBOT Attack:
                                          OK - Not vulnerable, RSA cipher suites not supported.

 * TLS 1.1 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * SSL 3.0 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * OpenSSL CCS Injection:
                                          OK - Not vulnerable to OpenSSL CCS injection


 SCAN COMPLETED IN 8.11 S
 ------------------------
```
</p>
</details>

<details>
<summary>Modern compatibility</summary>
<p>

```
$ sslyze --starttls=smtp opnsense.local:25

 CHECKING HOST(S) AVAILABILITY
 -----------------------------

   opnsense.local:25                        => opnsense.local




 SCAN RESULTS FOR opnsense.local:25 - opnsense.local
 ---------------------------------------------

 * TLS 1.0 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * TLS 1.2 Session Resumption Support:
      With Session IDs: OK - Server only supports TLS 1.3 which doesn't support Session IDs.
      With TLS Tickets: OK - Server only supports TLS 1.3 which doesn't support TLS tickets.

 * Session Renegotiation:
       Client Renegotiation DoS Attack:   OK - Not vulnerable
       Secure Renegotiation:              OK - Supported

 * TLS 1.1 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * Elliptic Curve Key Exchange:
       Supported curves:                  X25519, X448, prime256v1, secp384r1, secp521r1
       Rejected curves:                   prime192v1, secp160k1, secp160r1, secp160r2, secp192k1, secp224k1, secp224r1, secp256k1, sect163k1, sect163r1, sect163r2, sect193r1, sect193r2, sect233k1, sect233r1, sect239k1, sect283k1, sect283r1, sect409k1, sect409r1, sect571k1, sect571r1

 * ROBOT Attack:
                                          OK - Not vulnerable, RSA cipher suites not supported.

 * OpenSSL CCS Injection:
                                          OK - Not vulnerable to OpenSSL CCS injection

 * TLS 1.3 Cipher Suites:
     Attempted to connect using 5 cipher suites.

     The server accepted the following 3 cipher suites:
        TLS_CHACHA20_POLY1305_SHA256                      256       ECDH: X25519 (253 bits)
        TLS_AES_256_GCM_SHA384                            256       ECDH: X25519 (253 bits)
        TLS_AES_128_GCM_SHA256                            128       ECDH: X25519 (253 bits)


 * SSL 3.0 Cipher Suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * SSL 2.0 Cipher Suites:
     Attempted to connect using 7 cipher suites; the server rejected all cipher suites.

 * TLS 1.2 Cipher Suites:
     Attempted to connect using 156 cipher suites; the server rejected all cipher suites.

 * Deflate Compression:
                                          OK - Compression disabled

 * Downgrade Attacks:
       TLS_FALLBACK_SCSV:                 OK - Supported

[...]

 * OpenSSL Heartbleed:
                                          OK - Not vulnerable to Heartbleed


 SCAN COMPLETED IN 7.95 S
 ------------------------
```
</p>
</details>

## Test it

Feel free to test it:

```
$ sudo opnsense-patch -a windgmbh -c plugins -r opnsense-plugins 7701d0f3a156b9bd99e27382f485b6574330071a
```

### CODE REVIEW

**Comment by windgmbh** [comment]
Hey @mimugmail 
you are probably the person that will review this again.
Did you have time to look into it? Is my solution useful to the plugin? 
In case there is something that has to improved, please let me know and I will do it.

I am running this setup on multiple hosts for even longer than the pull request has been created without any issues so far.

**Comment by mimugmail** [comment]
@windgmbh sorry, please ping me more often, sometimes I forget things.
I installed your branch and test some combinations over the weekend 👍

**Comment by windgmbh** [comment]
> @windgmbh sorry, please ping me more often, sometimes I forget things.

I did not want to be too demanding, because I know that you have quite a lot to do with the many pull requests that you are getting.

> I installed your branch and test some combinations over the weekend

In my initial post you see some results of the testing that I have done initially. I tried all the possibilities for `smtp_tls_*` and `smtpd_tls_*` before submitting the pull request. For testing the server's settings, I recommend the tool `sslyze`, which can be found in the [Kali repositories](https://tools.kali.org/information-gathering/sslyze), [PyPi](https://pypi.org/project/sslyze/) or [GitHub](https://github.com/nabla-c0d3/sslyze). 

For testing whether the client's settings work as expected you might want to [look at the TLS Client Hello](https://serializethoughts.com/2014/07/27/dissecting-tls-client-hello-message) with WireShark, to check out which TLS versions/ cipher suites the client is asking for.

**Comment by windgmbh** [comment]
> I installed your branch and test some combinations over the weekend

@mimugmail Did your test proceed well this weekend? Do you require me to make changes/ improvements?

**Comment by mimugmail** [comment]
I'm still receiving emails, thx for the reminder

**Review by mimugmail — APPROVED** [review]
Not sure if we need to bump the version in model, but looks good.
Thx for your patience :)

**Comment by windgmbh** [comment]
> Not sure if we need to bump the version in model, but looks good.

Probably yes. Shall I add that or do you prefer doing that yourself upon the upcoming of the next release?

**Comment by fichtner** [comment]
@windgmbh do it ;)

**Comment by windgmbh** [comment]
@fichtner did it ;)
I did not rebase to make the review hopefully easier. I hope that's how you'd prefer it.

**Review by mimugmail — APPROVED** [review]
Great, thx :)

**Comment by windgmbh** [comment]
@fichtner Since @mimugmail approved the pull request: Is there anything that prevents you from merging? If the pull request requires anything else to get merged, just tell me and I'll help with the required changes. If anything should be done differently (in the future), I will do so.

**Comment by fichtner** [comment]
@windgmbh I was on leave for a month so this got stalled naturally. I will take a closer look tomorrow.

**Comment by fichtner** [comment]
Merged, thanks!

Migrating away from old settings like that isn't the best approach in the world but the new layout is superior to the old one so ok.

Next up: @windgmbh would you mind helping to test postfix 3.6 compatibility? FreeBSD ports already move to this version and it is said to have a few changes.

**Comment by windgmbh** [comment]
> Merged, thanks!

Thanks a lot as well! 

> Migrating away from old settings like that isn't the best approach in the world but the new layout is superior to the old one so ok.

I agree. I usually keep track of changes in Mozillas TLS recommendations. In case there are any, I will apply them. 

> Next up: @windgmbh would you mind helping to test postfix 3.6 compatibility? FreeBSD ports already move to this version and it is said to have a few changes.

Happy to help. I will take a look at the changes and try to make it work.

**Pull request merged**
