### PR TITLE
fix: delete button, decription field not working; add ui response to …

### PR DESCRIPTION
**Pull request by fabianfrz**
…clicking the clock

### CODE REVIEW

**Comment by fichtner** [comment]
@fabianfrz will you rebase and bump the revision?

**Comment by fichtner** [comment]
Nevermind, found the branch in the main repo... very handy, thanks!

**Comment by fabianfrz** [comment]
@fichtner I usually put my plugins changes on a branch in the opnsense repository so you can change it without any problems because of permissions - it makes it also easier because others could make a pull request on that branch if needed before the merge is done.

**Comment by fichtner** [comment]
I know, I asked you to do this a while ago ;)

**Pull request merged**
