### PR TITLE
net/haproxy: change server state and weight on-the-fly 

### PR DESCRIPTION
**Pull request by andeman**
Set the server state and weight via haproxy socket commands without applying configuration.

Add feature for: https://github.com/opnsense/plugins/issues/486.

### CODE REVIEW

**Comment by fraenki** [comment]
@andeman Thanks for this great contribution! :heart: 

I've noticed a few things that should probably be added to the in-line help or documentation (later; I'll take care for this):

If a server is in MAINT state, changing the weight is not visible in the GUI. The new weight is only visible when the server state is changed (i.e. to "UP"). I'd assume that this is a HAProxy limitation or design decision, nothing that needs to be changed in the plugin, but it could be confusing for new users.

If a backend uses a static balancing algorithm like "Source-IP Hash" (the default in os-haproxy), then the weight must be specified in %, otherwise the following error message would appear:

```
Backend is using a static LB algorithm and only accepts weights '0%' and '100%'.
```

The error message is clear, so no urgent need to change something in the plugin. However, it would probably be nice if the plugin would automatically add % to the value.

**Review by fraenki — APPROVED** [review]

**Comment by fraenki** [comment]
@fichtner Please do _not_ merge this to stable/21.1 just yet, I want to release this as os-haproxy 3.0 (#2214).

**Comment by fichtner** [comment]
Ack, I added dd38b7d7a267 just for cleanups and traceability.

**Comment by fichtner** [comment]
PS: nice work @andeman

**Pull request merged**
