### PR TITLE
using latest Snort V2 VRT Snapshot available

### PR DESCRIPTION
**Pull request by j0nny55555**
There is a more recent Snort VRT Ruleset Snapshot, this should allow the collection of it
It appears there are no Snort Issues or PRs being tracked

This is my first PR for OPNSense, and probably my 2nd or 3rd PR in Github ever, please help me improve this if necessary

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@j0nny55555 just to be sure, you tried this ruleset on OPNsense before opening the PR? I don't mind merging, but I don't use this myself.

**Comment by j0nny55555** [comment]
I am using the 29151 VRT ruleset on my OPNSense - it works

I am not sure how I would test the latest version 29200 available, but I was able to download it manually to my laptop to inspect one of the rule files, that's when I noticed the versions available and the hardcoded version the VRT OPNSense plugin is using

OPNSense is amazing, thank you and all contributors!! Is there a guide on how to test modifications such as this?

**Comment by AdSchellevis** [comment]
@j0nny55555 you can change the xml file on the machine itself and fetch contents.  You can find the file on the firewall here: `/usr/local/opnsense/scripts/suricata/metadata/rules/snort-vrt.xml`

**Comment by j0nny55555** [comment]
@AdSchellevis nice, I updated that file and went to tell OPNSense to update it's rules and noticed that the file version is a variable that you can update in the UI at the https://opnsenserouter.localdomain/ui/ids#download_settings
I've updated that as well and saved, then hit download and saw it check and refresh all rules, once completed, everything is operating well

Yes, version 29200 works!

thank you again for the guidance and check on this PR!!

**Pull request merged**
