### PR TITLE
security/acme-client: release 4.0 [only for 24.1]

### PR DESCRIPTION
**Pull request by fraenki**
see plugin changelog for details

### CODE REVIEW

**Comment by fraenki** [comment]
FWIW, I've tested the data migration on several firewalls and it was working perfectly fine.

**Comment by fichtner** [comment]
@fraenki you haven't changed the version number. I suppose 4.0 is done? I need an anwser for tomorrow morning to be able to get this into the final 24.1 otherwise it's going to have 3.20.


Cheers,
Franco

**Comment by fraenki** [comment]
@fichtner D'oh! :man_facepalming: Fixed in master.

**Comment by fichtner** [comment]
No problem, thanks!

**Pull request merged**
