### PR TITLE
Rebellion Theme fix for Firewall Schedule etc

### PR DESCRIPTION
**Pull request by marjohn56**

### CODE REVIEW

**Comment by opnsenseuser** [comment]
i can´t send you any message. so i have to do it over github. - martin@team-rebellion.net
LMTP error after RCPT TO:<martin@team-rebellion.net>:
552 5.2.2 <martin@team-rebellion.net> Quota exceeded (mailbox for user is full)

**Comment by opnsenseuser** [comment]
i think you have the wrong files. i will sent you the files again!. please clean up the mailbox

**Comment by opnsenseuser** [comment]
[theme-cicada.zip](https://github.com/opnsense/plugins/files/2019185/theme-cicada.zip)
[theme-tukan.zip](https://github.com/opnsense/plugins/files/2019186/theme-tukan.zip)

**Comment by marjohn56** [comment]
Sorry Rene. I'll go look at my mailbox now.... hmm... something odd with the rebellion server. I'll PM you with one of my other addresses,

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
