### PR TITLE
Fix frr ospfd template on redistribute config section

### PR DESCRIPTION
**Pull request by cedvan**
Just fix this issue : https://github.com/opnsense/plugins/issues/1400

### CODE REVIEW

**Comment by cedvan** [comment]
I tried, but the template system works oddly, I do not understand how to do it :disappointed: ...

**Comment by cedvan** [comment]
To revision number, up `19.1` to `19.2` or `19.1.1` ?

**Comment by mimugmail** [comment]
Just remove the first space before `redistribute`.
Regarding Makefile just make PLUGIN_REVISION a 2 in https://github.com/opnsense/plugins/blob/master/net/frr/Makefile

**Comment by cedvan** [comment]
:warning: This fix is important, when the routing fails, the firewall may become unreachable after the update ...

**Comment by mimugmail** [comment]
You can edit the file until release in /usr/local/opnsense/... Then service configd restart.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by fichtner** [comment]
Can you check c4923b3a18449c for me ?

**Comment by cedvan** [comment]
Ok, let me try ;)

**Comment by cedvan** [comment]
It's works ;)

**Comment by fichtner** [comment]
Splendid, thanks ❤️ 

Note this is for 19.7, 19.1.10 will not receive the fix anymore since builds have already been finished a few days ago and there will be no more 19.1 updates beyond the one to be able to upgrade to 19.7.

**Comment by cedvan** [comment]
No problem, I've freez upgrade to my gateways, I wait 19.7

**Pull request merged**
