### PR TITLE
Adding Selfhost DNS for acme.sh

### PR DESCRIPTION
**Pull request by Marvo2011**
Adding Selfhost DNS for acme.sh

https://github.com/acmesh-official/acme.sh/pull/3873

### CODE REVIEW

**Review by fraenki — APPROVED** [review]

**Comment by fraenki** [comment]
LGTM!
@Marvo2011 Please be aware that this will only work when acme.sh provides a [new release](https://github.com/acmesh-official/acme.sh/releases) which contains the "selfhost" DNS API hook. This will probably take some time. I'll merge it anyways, but I wanted to let you know upfront.

**Comment by fraenki** [comment]
Merged, thanks!

**Comment by fraenki** [comment]
@fichtner Is this merge already too late for the next OPNsense release? If so, I'll bump the version of os-acme-client again. Otherwise I'll just add it to the release notes of 3.8.

**Comment by fichtner** [comment]
We don’t plan a release in the next to weeks for 21.7. Could change, but very likely not next week with 22.1-RC1 preparation.

**Pull request merged**
