### PR TITLE
BGP

### PR DESCRIPTION
**Pull request by fabianfrz**
@mimugmail this are my changes to your commits. this closes #112

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner this is for testing

**Comment by fichtner** [comment]
Super, thanks for this guys!

**Comment by fabianfrz** [comment]
No problem. Can this be available as a dev version of the plugin?

**Comment by fichtner** [comment]
It will be there automatically: os-quagga-devel is built from master branch

**Comment by fabianfrz** [comment]
thanks, this way users like @mimugmail may test the plugin. I never used BGP so I don't know the way of configuring it. Release is next week?

**Comment by fichtner** [comment]
Wednesday next week I think, depending on how testing goes for the latest core additions.

**Comment by mimugmail** [comment]
I'll try to setup a big test environment in ProfitBricks and test most of the stuff.

Thanks for your help and patience with this PR 👍

**Comment by mimugmail** [comment]
@fabianfrz @fichtner  I setup a topology with 4 routers in a circle, upper ones in AS 65001, bottom ones in AS 65002. iBGP and eBGP work as expected and there were no issues setting up this via UI.

Only thing is that pressing the save buttons is not responsive. When I press save there's no progress, but when I switch to another menue and back, everything was saved. Also when adding a neigbor, pressing save doesn't close the window. I have to click on the X.

**Comment by fabianfrz** [comment]
@mimugmail 👍 

We can add BGPv4 to the next release if you like. `17.1.5` will come with `RIP` and `OSPF`.

So it could be included in `17.1.6` as we should have  at least a (short) testing period.

**Comment by mimugmail** [comment]
Great! When I'm back at work I'll start adding route-maps to BGP and a diagnostics page.

**Pull request merged**
