### PR TITLE
net/freeradius: Add logging support

### PR DESCRIPTION
**Pull request by mimugmail**
As the name says ...

### CODE REVIEW

**Comment by mimugmail** [comment]
Last update fixes #423 crash report send per mail.

**Comment by fichtner** [comment]
Thanks, ready for pull? :)

**Comment by mimugmail** [comment]
Yep :)

2017-12-10 13:47 GMT+01:00 Franco Fichtner <notifications@github.com>:

**Comment by fichtner** [comment]
done, thank you!

**Pull request merged**
