### PR TITLE
net/freeradius: Fix users file for CP accounting

### PR DESCRIPTION
**Pull request by mimugmail**
reorderd users file, please don't merge, have to doulbecheck with Boris.

### CODE REVIEW

**Comment by mimugmail** [comment]
@fichtner with 7ed367f I added a newline. Does opnsense-patch respects this? If I add it it's not recognized. But when cloning my repo it's in ...

**Comment by fichtner** [comment]
opnsense-patch should cope just fine :)

**Comment by fichtner** [comment]
but we should merge+squash without the version bump to work with opnsense-patch (it can't find the version number file in an install).

**Comment by mimugmail** [comment]
ok pls do it :)

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
