### PR TITLE
www/nginx: import naxsi core rules into configuration

### PR DESCRIPTION
**Pull request by fabianfrz**
allow to install naxsi default rules

### CODE REVIEW

**Comment by fabianfrz** [comment]
After Import:

Policies:
screenshot_20181007_104522

Rules:
screenshot_20181007_104629

**Comment by mimugmail** [comment]
I'll test with an Exchange and OWA on Monday. Thanks for your work :)

**Comment by fabianfrz** [comment]
@mimugmail please note that this does only download, It will not apply them to your locations.

**Comment by mimugmail** [comment]
Sure, I'll so the rest via policy .. thx

**Comment by mimugmail** [comment]
Ok, I installed all rules, was quite happy the policies were already there (amazing work Fabian) .. I just enabled all rules for testing and got:

```
2018/10/07 17:35:08 [emerg] 28968#100193: Naxsi-Config : Incorrect line MainRule id:1004 (/usr/obj/usr/ports/www/nginx/work/naxsi-0.56/naxsi_src/naxsi_skeleton.c/813)... in /usr/local/etc/nginx/nginx.conf:27
2018/10/07 17:35:08 [emerg] 29095#100193: Naxsi-Config : Incorrect line MainRule id:1004 (/usr/obj/usr/ports/www/nginx/work/naxsi-0.56/naxsi_src/naxsi_skeleton.c/813)... in /usr/local/etc/nginx/nginx.conf:27
2018/10/07 17:37:00 [emerg] 14761#101409: Naxsi-Config : Incorrect line MainRule id:1004 (/usr/obj/usr/ports/www/nginx/work/naxsi-0.56/naxsi_src/naxsi_skeleton.c/813)... in /usr/local/etc/nginx/nginx.conf:27

```

Which is:

`MainRule id:1004 "rx:*/" "msg:mysql comment (*/)" "mz:ARGS|$HEADERS_VAR_X:Cookie" "s:$policyefa53d6e9053472596afd53291516b1c:8";
`

**Comment by fabianfrz** [comment]
@mimugmail this must be a bug in the rule rendering (which means the bug has already existed before), I'll fix it.

**Comment by fabianfrz** [comment]
@mimugmail Found and fixed the issue - the regex flag was inverted which caused the issue because some rules use special chars which won't work in regex mode without proper escaping.  Now it should correctly escape.

For your information: you can also toggle the property in your config in all str rules to make it working but you are probably faster if you delete all policies and rules and do a reimport.

**Comment by mimugmail** [comment]
I tried it now .. 

At first with every policy enabled I got:

```
2018/10/08 13:57:29 [error] 91882#100484: *2 NAXSI_EXLOG: ip=myIP&server=mobilewaf.mydomain.de&uri=%2Fowa%2F&id=1206&zone=HEADERS&var_name=cookie&content=X-BackEndCookie%3DS-1-5-21-754468121-1773743388-1963001494-1928%3Du56Lnp2ejJqBzcjLyM6bx87Sx5zKyNLLm8%2Bc0p3IzpvSzc2azJqZxpnOmsacgYHNz87H0s7P0s3Nq87KxcvMxc%2FI%3B%20PHPSESSID%3D8859c20df979621f0b345ee2568e6d52%3B%20PBack%3D0%3B%20ClientId%3D3F4A5DE7B95148FF93C2AFF628FB192E%3B%20UC%3Df32f54a0ee7940b59455bbe76bd52079%3B%20RoutingKeyCookie%3Dv1%3A1508f414-6307-4664-a1f2-2b79e63186f7%40mydomain.de%3B%20AppcacheVer%3D15.1.544.27%3Ade-debase%3B%20X-OWA-CANARY%3D2F9eKcfZWkmfFcByrORc1mB07heiINYIhehtQW5OlfoklNC_4mt9pLkBbVjxeihFLbbUiuU12gY., client: myIP, server: mobilewaf.mydomain.de, request: "GET /owa/ HTTP/2.0", host: "mobilewaf.mydomain.de"
2018/10/08 13:57:29 [error] 91882#100484: *2 NAXSI_FMT: ip=myIP&server=mobilewaf.mydomain.de&uri=/owa/&learning=0&vers=0.56&total_processed=1&total_blocked=1&block=1&cscore0=$policy232c98ef104c49038247a9dfce446278&score0=8&zone0=HEADERS&id0=1206&var_name0=cookie, client: myIP, server: mobilewaf.mydomain.de, request: "GET /owa/ HTTP/2.0", host: "mobilewaf.mydomain.de"
2018/10/08 13:57:30 [error] 91882#100484: *2 NAXSI_EXLOG: ip=myIP&server=mobilewaf.mydomain.de&uri=%2Ffavicon.ico&id=19&zone=URL&var_name=&content=, client: myIP, server: mobilewaf.mydomain.de, request: "GET /favicon.ico HTTP/2.0", host: "mobilewaf.mydomain.de", referrer: "https://mobilewaf.mydomain.de/owa/"
2018/10/08 13:57:30 [error] 91882#100484: *2 NAXSI_FMT: ip=myIP&server=mobilewaf.mydomain.de&uri=/favicon.ico&learning=0&vers=0.56&total_processed=2&total_blocked=2&block=1&zone0=URL&id0=19&var_name0=, client: myIP, server: mobilewaf.mydomain.de, request: "GET /favicon.ico HTTP/2.0", host: "mobilewaf.mydomain.de", referrer: "https://mobilewaf.mydomain.de/owa/"

```

Then I disabled policies 1200-1300 since they were affected (I know I could only do this with 1206), but then I always got blocked of ID19 (which is error "no rules loaded").

I'm not sure if it still missing something or I'm too stupid (hopefully the second) :)

**Comment by fabianfrz** [comment]
have you added the custom policies in the location?

**Comment by mimugmail** [comment]
Yes, first I added all six, then I got the error above. Then I removed 1200-1300 from location and it gots blocked cause of rule 19.

**Comment by fabianfrz** [comment]
can you mail me your config, it works for me - it seems like you trigger the internal that your config is missing some rules.

**Comment by Oxima69** [comment]
same issue here. blocked cause of rule 19. is there any news on this topic ?

**Pull request merged**
