### PR TITLE
net/wireguard: allow fqdns in endpoint, fix for init script

### PR DESCRIPTION
**Pull request by mimugmail**
Wrong group, blocked packets. With HostnameFiled also FQDN in Endpoints allowed.

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by mimugmail** [comment]
Too late for 18.7.2 devel pkg? :)

**Comment by fabianfrz** [comment]
@mimugmail I don't think so ;)

**Comment by fichtner** [comment]
last builds will start on Wednesday so plenty of time :)

**Pull request merged**
