### PR TITLE
FIX - Sensor not starting without server enabled

### PR DESCRIPTION
**Pull request by juliocbc**
Sensor now starts even with local server disabled.

### CODE REVIEW

**Comment by mimugmail** [comment]
@juliocbc thanks for this fix, glad you are trying to use this feature.
I'd first like to talk to the author of maltrail as it doesn't make sense to set http port when remote logging is used.  I'll the issue one opened

**Comment by juliocbc** [comment]
@mimugmail thank you for all the good work you have been doing to the OPNsense community!

**Comment by fichtner** [comment]
@mimugmail did this resolve upstream or do we still need the PR?

**Comment by mimugmail** [comment]
I'm already preparing a patch for upstream, it took a bit to tag a release at maltrail project.

**Comment by juliocbc** [comment]
Hi @mimugmail ! Any news about it?

**Review by mimugmail — APPROVED** [review]
I though this was fixed upstream, maybe something changed during the releases. Better to solve this via templating for plugin stability. As listenport is required and has a default it will not break anything

**Comment by MikhailKasimov** [comment]
Possibly some misunderstanding based on ```I'm already preparing a patch for upstream``` phrase  is? And, in fact, there's no need in additional patches because of https://github.com/stamparm/maltrail/issues/6020 ?

**Comment by mimugmail** [comment]
Upstream meant to FreeBSD so the port in OPNsense gets updated.
But it still stands, when I'm trying to start maltrail without HTTP_PORT sensor.py doesn't start:

```
root@OPNsense:~ # python3 /usr/local/share/maltrail/sensor.py
Maltrail (sensor) #v0.26.1

[i] using configuration file '/usr/local/share/maltrail/maltrail.conf'
[!] invalid configuration value for 'HTTP_PORT' ('')

```

I you like you can have a talk to Miroslav but for me the proposed solution is also fine.

**Comment by stamparm** [comment]
@mimugmail it should be ok now with the latest revision

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
