### PR TITLE
Fix tooltip and many other corrections.

### PR DESCRIPTION
**Pull request by marjohn56**
As it says

### CODE REVIEW

**Comment by fabianfrz** [comment]
shouldn't the SCSS be changed too

**Comment by fichtner** [comment]
Yes, I just mentioned that in the forum. And we need a version or revision bump.

**Comment by marjohn56** [comment]
scss files updated.

@fichtner or someone try building these, I'm not 100% convinced that my Koala is setup correctly.

**Comment by fabianfrz** [comment]
@marjohn56 what is Koala?

**Comment by fabianfrz** [comment]
Found some issues in the theme: #501 - maybe this can be added here as well.

**Pull request merged**
