### PR TITLE
net/freeradius: add routes and v6 address

### PR DESCRIPTION
**Pull request by mimugmail**
- redesign users template to allow multi adds
- add Framed-Route attribute for OpenVPN 
- add Framed-IPv6-Address attribute
 
Seems there is a merge conflict

### CODE REVIEW

**Comment by fichtner** [comment]
Will you fix the makefile merge conflict ( 1.5.3 vs 1.5.2 ) ?

**Comment by mimugmail** [comment]
No idea how to do this :) I forked when it was 1.5.2 and you pushed 1.5.3 after this I guess.

**Comment by mimugmail** [comment]
changed ...

**Comment by fichtner** [comment]
done, thanks! :)

**Pull request merged**
