### PR TITLE
New theme for opnsense >> vicuna (dark anthrazit)

### PR DESCRIPTION
**Pull request by opnsenseuser**
New Theme for Opnsense >> Vicuna (dark anthrazit)

login:
grafik

gui:
grafik

grafik

grafik

grafik

grafik

grafik

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@fichtner I would be very happy if you could merge the new theme before the next opnsense release. I wish you a successful new year, good health and I look forward to our good cooperation again. regards rené

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by opnsenseuser** [comment]
@fichtner i think there went something wrong with the mergin.
the files in the folders are dublicated. 
logos are missing too. i´m I am 100% sure that everything is correct. 
even when installing with "opnsense-patch -c plugins fa1afc1c", thousands of strange characters run across the screen.

**Comment by fichtner** [comment]
opnsense-patch is for patching, not installing brand new files.

**Comment by opnsenseuser** [comment]
@fichtner do you know why vicuna isn´t available in the latest opnsense 20.1.1 update ?
regards
rené

**Comment by opnsenseuser** [comment]
@fichtner sorry, it´s in the latest update, but not in the descripton for 20.1.1

**Comment by fichtner** [comment]
Fixed the announcements.

**Comment by arch1mede** [comment]
Hi, this to me is probably the best looking dark theme however, in the traffic section from the dash board I see gray dots rather than the colors associated with the traffic:

image

Looks to be in the same when you go into the Reporting -> Traffic

**Pull request merged**
