### PR TITLE
security/acme-client: release 3.0

### PR DESCRIPTION
**Pull request by fraenki**
see plugin changelog for details

### CODE REVIEW

**Comment by fraenki** [comment]
@fichtner @AdSchellevis Just a heads-up that I plan to rename the plugin's GUI name from "Let's Encrypt client" to "ACME Client". This represents the changes in acme.sh, which now supports 3 other CAs in addition to the Let's Encrypt CA. Keeping the old name would just be confusing in the long run. By coincidence the plugin's package name has always been os-acme-client. :)

Other question: would it be possible to add a heads-up to the release notes of the upcoming OPNsense release? I assume that otherwise many users may miss the name change, causing much confusion (and support requests).

FYI, I want to perform more tests in the upcoming days before merging it to master.

**Comment by AdSchellevis** [comment]
@fraenki I expect we can highlight the change a bit more, either on the update line or in the prelude for the release. Just make sure you keep @fichtner posted on what changes when, if it's only naming and doesn't really break anything, it shouldn't matter putting it in a minor release.

**Comment by fichtner** [comment]
@AdSchellevis @fichtner sure we already talked about it briefly and me like this change so far ❤️

**Comment by fraenki** [comment]
I've upgraded several firewalls to os-acme-client 3.0 and acme.sh 3.0, everything worked as expected. The model migration was flawless with every configuration. And I was able to register new accounts and create/renew/revoke certificates without any issues. I've also tested the new possibility to use multiple CAs, and my test with using both Let's Encrypt and ZeroSSL was successful too.

**Comment by fraenki** [comment]
@fichtner Feel free to merge os-acme-client 3.0 and amce.sh 3.0 for the next release. Please mention the name change in the release notes. Thanks! :)

**Comment by fichtner** [comment]
@fraenki will do, thanks a lot!

**Pull request merged**
