### PR TITLE
mail/rspamd: fix model (missing properties), constraint bugs

### PR DESCRIPTION
**Pull request by fabianfrz**
@mimugmail please test this. I think half of your model is missing

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner I want to wait for @mimugmail since I did this very quickly and I tested it only on ui_devtools and not on a real machine. He should know if it acts like expected now.

**Comment by mimugmail** [comment]
Great, thx to all. I had a look at other modules came after 1.6.X, but nothing which require user input, so for me the plugin should be feature complete :)

**Comment by fabianfrz** [comment]
@fichtner it should be ok now:

grafik

**Comment by fichtner** [comment]
great, cheers guys 🍻

**Pull request merged**
