### PR TITLE
Freeradius TLS

### PR DESCRIPTION
**Pull request by schreibubi**
Add support for TLS and implement common name checking on certificates. Allow additional characters in the usernames, since those are required for this use-case

### CODE REVIEW

**Comment by mimugmail** [comment]
What happens on your side if you only set TLS and not enable the new checkbox?

**Comment by mimugmail** [comment]
Forget it, had reread the old template, good one 👍

**Comment by schreibubi** [comment]
Sure, will do the Makefile and pkg-descr update.

**Comment by schreibubi** [comment]
Any chance of getting this merged?

**Comment by mimugmail** [comment]
@fichtner any chance to get this merged too? no need for stable with 20.7.4

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by mimugmail** [comment]
@schreibubi are you still using this feature? I think this is broken sind 22.7.8 which introduces FR 3.2.1. 
The default changed a bit which might be the error:

https://github.com/FreeRADIUS/freeradius-server/blob/master/raddb/sites-available/check-eap-tls#L66

**Comment by schreibubi** [comment]
@mimugmail This is a bug in FR3.2.1, see my bug report here: FreeRADIUS/freeradius-server#4820 
It was fixed already, but will be only available in the next release.
In the meantime you can disable Freeradius -> EAP -> Check TLS Common-Name to have it working again.

**Comment by mimugmail** [comment]
You
Are
Awesome
:)

**Pull request merged**
