### PR TITLE
tukan/cicada (no expansion delay / animation / nv.d3.css) fixes

### PR DESCRIPTION
**Pull request by opnsenseuser**
no expansion delay / animation  -> https://github.com/opnsense/core/issues/2554
nv.d3.css fixes
other small fixes

### CODE REVIEW

**Comment by fichtner** [comment]
Good morning. Ready for pull or wait? :)

**Comment by marjohn56** [comment]
https://forum.opnsense.org/index.php?topic=9825.0

**Comment by opnsenseuser** [comment]
if it is this problem then it is a common problem. does he mean that? https://github.com/opnsense/core/issues/2747

**Comment by marjohn56** [comment]
It's fine with the default theme, only appears with our themes.

**Comment by opnsenseuser** [comment]
@fichtner please wait with the pull.
@marjohn56 Screenshot?

**Comment by marjohn56** [comment]
And it's there with any number of columns. This is mine with 3 columns.

image

**Comment by marjohn56** [comment]
@fichtner  - I seem to be making a habit of throwing in spanners at the last minute. 🤔

**Comment by fichtner** [comment]
I'll fix the firewall widget tomorrow. I think this is a core issue with the widget structure itself.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by marjohn56** [comment]
Okey dokey. I'll go and update rebellion  to match René's changes.

**Comment by opnsenseuser** [comment]
@marjohn56 you're right. 
But it's kinda weird because you've taken over the css code from opnsense theme 1: 1. 
the problem should not occur with you, too

@fichtner in the production environment, the problem really only occurs in our(dark, cicada, tukan) themes. in the development environment for all themes (also opnsense). strange

**Comment by opnsenseuser** [comment]
prod: (opnsense theme)
grafik

development: (opnsense theme)
grafik

**Comment by opnsenseuser** [comment]
@fichtner thx for mergin!

**Comment by marjohn56** [comment]
> @marjohn56 you're right.
> But it's kinda weird because you've taken over the css code from opnsense theme 1: 1.
> the problem should not occur with you, too
> 
> @fichtner in the production environment, the problem really only occurs in our(dark, cicada, tukan) themes. in the development environment for all themes (also opnsense). strange

perhaps it's the way the widget is pulling in the other themes.

**Comment by fichtner** [comment]
I'll fix the widget. All other widgets are fine so I blame that one. ;)

**Comment by marjohn56** [comment]
@opnsenseuser  - As you say, Rebellion is basically Opnsense theme with colour changes, so it's a little odd. I'll wait on any changes to Rebellion until they've worked their way into the default theme.

**Pull request merged**
