### PR TITLE
sysutils/apuled plugin (scripted version - from Cloudfence) 

### PR DESCRIPTION
**Pull request by juliocbc**
PC Engines APU LED plugin to show some system status using the front LEDs.

This PR started from this: [https://forum.opnsense.org/index.php?topic=10177.msg55459#msg55459](url)

### CODE REVIEW

**Comment by fichtner** [comment]
Thanks! Merged manually. Version set to 0.1 and development only.

There are some quirks to work out:

Monitoring IP is hardcoded... it either needs a pass-through address from the cron job or latch on to some other setting.

The cron job could be made automatic, also the loading of the apuled.ko on boot. It would remove some friction from the scripting.

What do you think?

**Comment by juliocbc** [comment]
Thank you for all the great work @fichtner that you and the core team being doing!

About monitor IP, I agree! I'll revise it, maybe use the same IPs from the monitor IP gateway setting. What do you think?

The automatic cron job it's a must be done feature for sure! There are some reference code that I can follow?

**Comment by fichtner** [comment]
Thanks to you as well. I'm not sure what's easier as Multi-WAN is tricky. For now it could be a setting for a custom monitor IP. I just don't like putting e.g. google in and running it by default if you know what I mean.

For cron see src/etc/inc/plugins.inc.d/core.inc:function core_cron()

It needs a plugin file apuled.inc with function apuled_cron() and not necessarily a GUI in the first iteration

**Comment by soder10** [comment]
Remark for myself, that there is this plugin to check for.

**Comment by juliocbc** [comment]
@fichtner please take a look it: [Monitor IP](https://github.com/cloudfence/apuled/commit/d0643d41c5dd68d34a8c3081d8e46954110f8000)

What do you think?

**Comment by fichtner** [comment]
That's a clever idea and if it works yes please :)

**Comment by juliocbc** [comment]
@fichtner 

It works well in my tests. How to PR again, since this is already closed?

**Comment by fichtner** [comment]
Open new PR against current master. :)

**Comment by juliocbc** [comment]
> Open new PR against current master. :)
> […](#)
> On 15. Jul 2019, at 13:50, Julio Cesar Camargo (JCC) ***@***.***> wrote: @fichtner It works well in my tests. How to PR again, since this is already closed? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Done! #1410

**Pull request closed without merging**
