### PR TITLE
add support for custom configuration

### PR DESCRIPTION
**Pull request by fabiocastagnino**
like for http server add support for custom configuration in stream server

### CODE REVIEW

**Comment by fichtner** [comment]
Uuid-based override dirs don’t seem to be very portable. Not sure where @fabianfrz stands WRT this. Personally I’m not going to merge it in this state.

**Comment by fabianfrz** [comment]
@fichtner I have them in the HTTP section already. They are there to allow easy extension for advanced users only.

**Comment by fabianfrz** [comment]
@fabiocastagnino: don't forget to version bump + add a changelog entry

**Comment by fichtner** [comment]
@fabianfrz ok, I'm interpreting this as approval and add missing stuff after merge.

**Pull request merged**
