### PR TITLE
The Tukan theme - blue/white - First Commit

### PR DESCRIPTION
**Pull request by marjohn56**
https://forum.opnsense.org/index.php?topic=7834.0

### CODE REVIEW

**Comment by marjohn56** [comment]
@fabianfrz - back from my holiday... 

what enhancement do you need?

**Comment by fabianfrz** [comment]
@marjohn56 the enhancement tag means this PR contains new functionality, new plugin etc. It is just a category for the PR. `bug` means contains a bugfix so it is higher priority.

**Comment by marjohn56** [comment]
@fabianfrz - I learn something new almost every day. ;)

Update from René

**Comment by fichtner** [comment]
Merged, thanks! Setting it back to version 0.1 though ;)

**Pull request merged**
