### PR TITLE
WIP net/frr: Add BGP password support

### PR DESCRIPTION
**Pull request by AdSchellevis**
replacement for https://github.com/opnsense/plugins/pull/2645, adding setkey rafactor in https://github.com/opnsense/plugins/commit/782cedc94945bc058ad1e56de8349e5fbdb544ab

### CODE REVIEW

**Comment by fichtner** [comment]
@AdSchellevis this doesn't look right from GitHub

**Comment by AdSchellevis** [comment]
@fichtner hmm, this is odd, let me try to rebase again and see if this is fixable. GitHub was also down from my end yesterday evening, odd

**Comment by AdSchellevis** [comment]
if @mimugmail agrees with the content, we should squash merge it and rewrite the commit message, the trail is a bit messy now.

**Comment by mimugmail** [comment]
Sure, love it. Thx for your help :)

**Review by mimugmail — APPROVED** [review]

**Comment by AdSchellevis** [comment]
@mimugmail you're welcome, it's merged

**Comment by mimugmail** [comment]
@AdSchellevis works great on my end. Let's let it sleep in devel until 22.1.1 so ppl will have time to test a devel pkg :)

**Pull request merged**
