### PR TITLE
Colour Change to table warning

### PR DESCRIPTION
**Pull request by marjohn56**
Hard to read tables when using a warning colour.

### CODE REVIEW

**Comment by fichtner** [comment]
You may want to coordinate with @opnsenseuser to update the scss as well otherwise this change will be purged quickly by the update machinery.

**Comment by marjohn56** [comment]
Why would @opnsenseuser have anything to do with the rebellion theme?

**Comment by marjohn56** [comment]
What I did forget was to update the version info though. I'll do that now.

**Comment by fichtner** [comment]
Good question 😊

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
