### PR TITLE
net/freeradius: add remote mysql support

### PR DESCRIPTION
**Pull request by mimugmail**
Created a draft PR :) 

Regarding #1092

### CODE REVIEW

**Comment by fabianfrz** [comment]
since almost all backends are equally to configure, I would suggest to call it externalDB instead of mysql and add a dropdown to select it where you can add only MySQL for now. This would allow to reuse the fields without duplicating them.

@fichtner What do you think? The validation can still be enforced (SetIfConstraint).

**Comment by mimugmail** [comment]
ok, should be able to merge now :)

**Comment by fichtner** [comment]
update version?

**Comment by mimugmail** [comment]
Can we stay at 1.9.0? I want to add a warning that DHCP is in experimental state but release with stable version (19.1.4). Ok?

**Comment by fichtner** [comment]
It can create update issues for -devel users, manual reinstall is required... but why not. :)

**Pull request merged**
