### PR TITLE
Add L2TP linkup and linkdown fields

### PR DESCRIPTION
**Pull request by ccesario**
Add L2TP linkup/linkdown fields do add routes

Refer to #1422

### CODE REVIEW

**Comment by fabianfrz** [comment]
I don't like the idea of this implementation. It would be better to run a configd call like "configctl l2tp linkup" from the shell and put the logic into a handler. The handler could just run all scripts in a directory like l2tp.linkup.d to keep that pluggable and it keeps executable out of the UI which may lead to a local privilege escalation vulnerability.

**Comment by ccesario** [comment]
> I don't like the idea of this implementation. It would be better to run a configd call like "configctl l2tp linkup" from the shell and put the logic into a handler. The handler could just run all scripts in a directory like l2tp.linkup.d to keep that pluggable and it keeps executable out of the UI which may lead to a local privilege escalation vulnerability.

Hi @fabianfrz,
I understood your comment, but I only followed the code, adding content into, as original code.

**Comment by ccesario** [comment]
> No custom injection glue please.

Hi @fichtner , what is the correct way todo this? Because I only add code into hardcoded files.

**Comment by fichtner** [comment]
Let's just close this and talk over at #1422

**Pull request closed without merging**
