### PR TITLE
cicada - little tooltip fix

### PR DESCRIPTION
**Pull request by opnsenseuser**
@fichtner sorry, i missed a correction i did already for tukan!
cicada - little tooltip fix

### CODE REVIEW

**Comment by fichtner** [comment]
maybe you want this too depending on what you already did: placeholder colour is not the normal text colour and could lead to confusion... https://github.com/opnsense/core/commit/371430212

**Comment by opnsenseuser** [comment]
Thanks for the info, but I have already adjusted and already merged.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by opnsenseuser** [comment]
great 👍

**Pull request merged**
