### PR TITLE
dns/dyndns: add desec.io wildcard support

### LINKED ISSUE #2482: dyndns: desec.io wildcard support
```
[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
```

The dyndns (1.24_2) desec configuration does not yet support wildcard entries.
As https://github.com/opnsense/plugins/blob/master/dns/dyndns/src/etc/inc/plugins.inc.d/dyndns/phpDynDNS.inc#L1253 indicates.

Related documentation:

- https://desec.readthedocs.io/en/latest/dyndns/configure.html#custom-configuration
- https://desec.readthedocs.io/en/latest/dyndns/update-api.html#update-api-authentication

### PR DESCRIPTION
**Pull request by luclu**
Adds https://desec.io wildcard support - see #2482

This is my first PR; I will happely incorporate any feedback.
Also note that I didn't packaged and tested the changes (as I still need to figure that out) - so I only validated the desec-API call via the https://insomnia.rest app.

Closes #2482.

### CODE REVIEW

**Comment by fichtner** [comment]
hi @luclu,

Looking at https://github.com/opnsense/plugins/commit/71a8c222684 what you want to achieve should be a one-liner?


Cheers,
Franco

**Comment by fichtner** [comment]
Ok, three lines... one for each case :)

**Comment by luclu** [comment]
hi @fichtner, 

thank you for helping :)

I could change the if statement to a ternary operator like:
`$result = condition ? value_true : value_false;` - if you want me to.

Best,
Luca

**Comment by fichtner** [comment]
Er, no, just add the wildcard services to the switch case.

**Comment by luclu** [comment]
Ah I see - this should be all then, right?

**Comment by fichtner** [comment]
Looks good to me, thanks! ❤️

**Pull request merged**
