### PR TITLE
www/nginx: Load logs for single server on demand

### PR DESCRIPTION
**Pull request by 8191**
I've tested PR #2165 on a OPNsense installation with many nginx HTTP servers configured (~20) and performance is not too good. Loading of the error/access logging pages takes up to one minute! With this PR loading improves to less than a second:

Loading of the logging page takes very long if many servers are configured.
With this change the single log files for a server are loaded only after
clicking the down error for the server entry in the log view.

### CODE REVIEW

**Comment by 8191** [comment]
@fabianfrz Maybe you have to chance for a review before 22.1 gets released? 😄

**Comment by fabianfrz** [comment]
looks good

**Review by fabianfrz — APPROVED** [review]

**Comment by 8191** [comment]
@fabianfrz Thanks for the review. Can you merge this PR or do we need @fichtner ?

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
