### PR TITLE
Restore TSIG key name entry to secondary zones

### PR DESCRIPTION
**Pull request by miken32**
Fixes a regression caused by commit 2fceec58

### CODE REVIEW

**Comment by fichtner** [comment]
CC @mimugmail @fraenki

**Review by pmhausen — APPROVED** [review]
Hi all,

I don't have a matching setup to test but the changes look reasonable. Only one question: will this work when multiple master servers are configured?

Currently the UI form permits multiple addresses and the plugin correctly expands these to e.g.:
```
zone "intern.punkt.de" {
        type slave;
        masters { 217.29.45.12; 217.29.45.13; };
        file "/usr/local/etc/namedb/slave/intern.punkt.de.db";
```

If the changes do not break that, I'm fine with them.

**Comment by miken32** [comment]
@pmhausen yes and if you have a key set for the zone it looks like this:

```
zone "example.ca" {
        type slave;
        masters { 192.168.241.3 key "zonexfr-key"; 192.168.242.200 key "zonexfr-key"; };
        file "/usr/local/etc/namedb/slave/example.ca.db";
        allow-query { localnet; };
};
```

This patch is just putting it back the way it was before the regression.

**Comment by AdSchellevis** [comment]
@miken32 thanks!

**Comment by pmhausen** [comment]
Big thanks from me, too! Happy holidays to everyone, regardless if/how you celebrate.

**Comment by fichtner** [comment]
Likewise, happy holidays!

**Pull request merged**
