### PR TITLE
dns/bind: small quality of life improvements

### PR DESCRIPTION
**Pull request by fraenki**
#### reject built-in ACL names
I was naively naming an ACL "any" and this silently broke my BIND:

```
root@opnsense:~ # service named restart
named not running? (check /var/run/named/pid).
/usr/local/etc/namedb/named.conf:3: attempt to redefine builtin acl 'any'
/usr/local/etc/rc.d/named: ERROR: named-checkconf for /usr/local/etc/namedb/named.conf failed
```

Now the four built-in ACL names are rejected.

#### fix truncated checkboxes
I've noticed that the checkboxes in the first column are a bit truncated:

os-bind_ui_glitch

It seems this was caused by missing CSS classes.

#### add button to delete selected items
After fixing the checkboxes I've noticed that they are effectively useless, because the button to delete multiple items is missing, so I've added it.

#### relax ACL name mask
Finally I've made a small change to allow underscores and hyphens in ACL names.

### CODE REVIEW

**Comment by fraenki** [comment]
@mimugmail, please review :)

**Review by mimugmail — APPROVED** [review]
Looks good, thx! 👍

**Comment by fraenki** [comment]
@fichtner Would you merge this for 20.7.5? :)

**Comment by fichtner** [comment]
Only if Michael approves. We forgot to talk about it yesterday.

**Comment by mimugmail** [comment]
For me ok when window is still open :)

Franco Fichtner <notifications@github.com> schrieb am Mi., 18. Nov. 2020,
07:46:

> Only if Michael approves. We forgot to talk about it yesterday.
>

**Comment by fichtner** [comment]
ok consider it done :)

**Pull request merged**
