### PR TITLE
www/caddy: Add option to disable TLS in domain

### PR DESCRIPTION
**Pull request by Monviech**
Fixes: https://github.com/opnsense/plugins/issues/4074

### CODE REVIEW

**Comment by Monviech** [comment]
Still thinking about this. I might invert the logic of it since I dislike "enable to deactivate something" fields.

**Comment by swhite2** [comment]
> Still thinking about this. I might invert the logic of it since I dislike "enable to deactivate something" fields.

Since this is a checkbox it's not that big of a deal, but with other option types "keeping everything empty" should be the sensible default as this minimizes the chance of people forgetting what they added/removed and can simply go back to a clean state without much trouble. Just my 2 cents really :)

**Comment by Monviech** [comment]
@swhite2 That makes sense, I have changed the logic back to my original plan and it looks much cleaner and easier to read that way.

**Comment by swhite2** [comment]
LGTM

**Pull request merged**
