### PR TITLE
sysutils/nut: add apcupsd support

### PR DESCRIPTION
**Pull request by xbb**
Adds apcupsd-ups driver support

Man page: https://www.mankier.com/8/apcupsd-ups

Example output from NUT diagnostics page:

```
battery.charge: 100.0
battery.charge.low: 5
battery.date: 2017-10-21
battery.runtime: 3120.0
battery.runtime.low: 180
battery.voltage: 27.1
device.mfr: APC
device.model: Smart-UPS 1000
device.serial: XXXXXXXX
device.type: ups
driver.name: apcupsd-ups
driver.parameter.pollinterval: 60
driver.parameter.port: 192.168.50.1
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.internal: 0.04
input.frequency: 50.0
input.voltage: 233.2
output.frequency: 50.0
output.voltage: 233.2
output.voltage.nominal: 230
ups.date: 2021-04-18
ups.delay.shutdown: 0
ups.delay.start: 0
ups.firmware: UPS 09.4
ups.firmware.aux: 00.5
ups.id: APCUPS
ups.load: 31.8
ups.mfr: APC
ups.mfr.date: 2011-09-26
ups.model: Smart-UPS 1000
ups.realpower.nominal: 700.0
ups.serial: XXXXXXXX
ups.status: OL
ups.temperature: 29.2
ups.test.result: OK
ups.time: 23:14:10
```

### CODE REVIEW

**Review by mimugmail — APPROVED** [review]
Model needs version bump, rest looks good, thx! :)

**Comment by xbb** [comment]
> Model needs version bump, rest looks good, thx! :)

Done, thanks!

**Comment by mimugmail** [comment]
@fichtner ready for merge

**Comment by fichtner** [comment]
Merged, thanks! ❤️

**Pull request merged**
