### PR TITLE
net/haproxy: release 2.6

### PR DESCRIPTION
**Pull request by fraenki**
## New features
- add support for `http-response set-status` to manipulate HTTP status codes

## Bugfixes
- fix invalid backend name when using `nbsrv` in ACLs

## Enhancements
none

### CODE REVIEW

**Comment by fraenki** [comment]
@fichtner I'd merge this for os-haproxy 2.5 to stable branch, if you have no objections.

**Comment by fichtner** [comment]
sure, but you will need to bump revision or version. don't want to touch 18.1.3 builds again to do an early Monday release. We will have to push 18.1.4 the same week, strongswan has a cve so that could be picked up as well.

**Comment by fichtner** [comment]
(to be precise: 18.1.3 is ready for release, but we wait till Monday because we don't want to release on Friday)

**Comment by fraenki** [comment]
OK, so I'll make this os-haproxy 2.6 instead :)

**Comment by fichtner** [comment]
yes please, I'll pick it up after merge.

**Pull request merged**
