### PR TITLE
Add staticd to routing suite

### PR DESCRIPTION
**Pull request by fmeppo**
Quagga includes staticd, a service for configuring and injecting static routes into the frr suite.  Normally it's not necessary to use this to set up a basic static route in OPNsense, but in certain scenarios it's useful for frr to see the static routes as connected (so they can be leveraged from BGP and OSPF sessions).  I ran into this problem when setting up BGP on my home OPNsense instance to connect to the DN42 project, and the fastest way I could find to work around it was to add my static routes via staticd.  I hate to set up one-off code manually on my relatively clean OPNsense setup, so....

Here's a couple diffs to add staticd to the "Routing" tab.  The only general option is to enable/disable the service, but you can define IPv4 and v6 routes with optional gateways.  I didn't add a dedicated diagnostics entry, since staticd routes show up in the existing views of the system routing table (including in Routing/Diagnostics), and not every feature of staticd is supported - but what's included should work pretty seamlessly.

Happy to reopen as a feature request, or add extra functionality, or modify the included diffs as needed.  It's my first OPNsense pull request, so please let me know what's proper protocol here.

### CODE REVIEW

**Comment by mimugmail** [comment]
As dicussed in #2284 I'm not sure how this might break the legacy routing behavior. If you consider pulling frr to core there should only be one way to handle routing. If it stays Tier3 plugin happy to have a deeper look

**Comment by AdSchellevis** [comment]
I think I agree with Michael here, if we move FRR to core at some point (which is likely a good idea), we end up with two places to define static routes, one being tightly integrated and being able to track gateway changes and the other one (FRR) not playing by the same rules, which adds confusion and has the risk of breaking the static routes that where already there. 

When possible, I would prefer another option to reach the same goals, but in that case it might be better to open a ticket explaining the use-case that's currently not possible and try to seek an alternative option. This likely takes time and user interaction to figure out the options I'm afraid.

**Comment by fmeppo** [comment]
staticd interacts with the routing table the same way BGP and OSPF will - routes added via frr (whatever the source) will be added and removed when they cease being relevant.  If an interface goes down the route disappears, as this is a function of the kernel routing table.  Existing routing behavior is unchanged (unless you turn on frr in the first place, in which case it's very likely you want more than basic routing).

One key motivator was mentioned in core issue #4995 (which is why I didn't open a new issue here): sometimes you want to have more kernel-based routes than you advertise via BGP/OSPF.  In this case you can't redistribute kernel routes, but you can redistribute static routes (e.g., those added via staticd).  Unfortunately, without this PR there's no way to add static routes in a way frr can see.  This isn't exactly typical behavior, so I could see adding some cautionary text somewhere (as @mimugmail mentioned in #2284 ).

In my case, I need to add a route to a specific IP address via wireguard interface - and the IP is outside the network assigned to the interface.  wgX is effectively a point-to-point interface, but unless a broader subnet is assigned (like the link-local networks for IPv6) the default routing table won't include a path to this IP.  It's possible to explicitly add this route via system tables, but frr won't see it (particularly if we're not re-exporting kernel routes) and will not believe the target IP is connected.  Since the target IP is my BGP peer, the peer is assumed to be not connected and no routes are learned.  With staticd this becomes an easy fix; just add an explicit route to the BGP peer and things work.  Yes, mistakes here can create conflict with system-defined (or wireguard-defined) routes....but OPNsense lets me override default behavior in other areas (like DNS), so I've always considered the plugin system to be a definite strength.

I'd like to do whatever's necessary to get functionality like this merged - including adding support for other staticd options (like SR-TE) that system routing will likely never support.  @AdSchellevis, you mentioned opening a support issue and starting some user interaction; is that the appropriate next step here?  If so, I'm happy to open something along the lines of #1770, #2284, or #3128 to track the concern.

**Comment by AdSchellevis** [comment]
@fmeppo thank you for explaining the need, I have to think about this for a bit. Let's keep this PR open for further discussion and skip additional tickets as they already seem to be there. 

In short, we need to redistribute a (set of) route[s], but when choosing redistribute kernel, we're offering too much to the other end, right?

**Comment by mimugmail** [comment]
Redistribute routes of staticd works a bit better compared to system routes in FreeBSD. In the past we had some forum posts also complaining about it. Never found the time to compare both myself

**Comment by fmeppo** [comment]
@AdSchellevis - you're correct, in that staticd helps redistribute routes (when we can't redistribute all kernel routes).  I hit that case, and one extra: if I have a kernel route to my BGP peer traffic will flow but frr does not see the BGP host as connected.  frr expects BGP peers to either be in the same subnet as my router's IP or have a route defined (within the frr framework).  staticd works around both issues nicely.

**Comment by AdSchellevis** [comment]
When using OSPF, I expected to be able to publish only a partial set of my static routes using route-maps, but to be honest, after setting up a simple setup and publishing "kernel" I seem to end up with all of them instead of the intended ones. BGP might be different, but having a separate set of static routes for redistribution might at least be a lot easier.

I still think we should make the purpose very explicit in some way, I'll put this PR on my list of things to review and merge.

**Comment by fmeppo** [comment]
Exactly.  You can do some filtering with BGP route maps, but that gets tricky (and your route map config becomes as complex as your system route config, excluding stuff you don't want to redistribute).

I'm happy to modify these diffs as needed, just let me know.  In the meantime, thanks for the reviews.

**Comment by AdSchellevis** [comment]
@fmeppo I've created a new branch (https://github.com/opnsense/plugins/tree/frr_staticd) to restructure the code a bit and make it more inline with how core components work. My current modifications are https://github.com/opnsense/plugins/commit/2835fa6a0d908be6b3f381b305e4f0dcd23ea87f, I'm not finished yet as some validations are still missing, but I wanted to ask you to take a look anyway.

**Comment by AdSchellevis** [comment]
@fmeppo I've opened a new PR using your code with my additions, can you take a look at https://github.com/opnsense/plugins/pull/3904 and let me know if this works for you?

**Pull request closed without merging**
