### PR TITLE
dns/ddclient: Use interface as ip source

### LINKED ISSUE #2784: dns/ddclient - Please add possibility to select interface for each account
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
I use two ethernet interfaces with dynamic ip addresses and thus need ddclient to specify which ip address to use when updating the dyn dns service. In my case Google Domains

**Describe the solution you'd like**
A select box, similar to the one in the deprecated dyndns plugin

**Additional context**

I have edited ddclient.conf manually and I got it to work as I wanted. Noted that the generated ddclient.conf does not follow the ddclient.conf.sample exactly. The result is unpredictable when adding a line with `use if=...` without trailing comma and back-slash in the second google record.
The example below works fine for me.

```
daemon=300
syslog=yes                  # log update msgs to syslog
pid=/var/run/ddclient.pid   # record PID in file.

#
# setup how we expect to retrieve an IP address
#
use=web, web=http://checkip.dyndns.org/, web-skip="Current IP Address:"

protocol=googledomains
ssl=yes
login=**redacted**
password=**redacted**
strp81.**redacted**.com

protocol=googledomains, \
use=if, if=igb2, \
ssl=yes, \
login=**redacted**, \
password=**redacted** \
strp81-4g.**redacted**.com
```

### PR DESCRIPTION
**Pull request by MrRoundRobin**
Added the option to use an interface as ip source, either global or per account. fixes #2784 

Added the options in the overview but it could look nicer. I don't know how to hide the if the option is not used:
image

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@MrRoundRobin I've added https://github.com/opnsense/plugins/commit/dc16aac90714c6496c0c41bdcc494fe4d8ccff1e into a new branch (https://github.com/opnsense/plugins/tree/dns_ddclient_interfaces). The multiple interfaces doesn't seem to be functional on my end, maybe you can register another account and try the configuration on your end? According to their docs (https://ddclient.net/usage.html#multiple-ips) it should be possible, on my end it never tries to fetch another address. (tried with two accounts)

If you kill the active ddclient service, you can easily start in debug mode using:
```
ddclient -foreground -debug -verbose
```

**Comment by mitchell-bumgarner** [comment]
For whoever may need this tidbit of information I found out today; If you manually set the interface via the `/usr/local/etc/ddclient.conf` config file, the ddclient and OPNSense's implementation of it, does respect that setting.

```
ssl=yes, \
use=if, if=em2, \ #`em2` is my 2nd WAN interface, you'd use whatever interface you want to have as your public IP.
protocol=googledomains, \
login='username_here', \
password='password_here', \
subdomain.domain-tld.com, \
```

Interestingly enough, the GUI does not show the domains that are configured, via the CLI, in that config file. I haven't done a full reboot after yet, so I am not filing a bug until after I do that, just in case it's a full server reboot that will show those domain entries.

**Comment by MrRoundRobin** [comment]
@AdSchellevis I tested with this configuration:
image

which results in the following config:
image

and that config worked perfectly

What was your config?



@mitchell-bumgarner The configuration system in opnsense overrides the config files from its own backend. That's why the front end will not show your manual edits.

**Comment by MrRoundRobin** [comment]
@AdSchellevis I tested with this configuration:
image

which results in the following config:
image

and that config worked perfectly

What was your config?



@mitchell-bumgarner The configuration system in opnsense overrides the config files from its own backend. That's why the front end will not show your manual edits.

**Comment by AdSchellevis** [comment]
@MrRoundRobin I tried the latest code, not sure what went wrong the last time but it seems to be functional now on my test setup as well.

**Comment by AdSchellevis** [comment]
merged in https://github.com/opnsense/plugins/pull/2813 thanks @MrRoundRobin

**Pull request closed without merging**
