### PR TITLE
Support IPv6 DynDNS update for Google Domains (closes #1691)

### LINKED ISSUE #1691: Support IPV6 DynDNS update for Google Domains
**Is your feature request related to a problem? Please describe.**
The dyndns plugin supports ipv4 updated for google domains, but it does not support ipv6. Both address types use the exact same API as per google's documentation: https://support.google.com/domains/answer/6147083?hl=en.

I am not familiar with the opnsense codebase, and I haven't touched php in over 15 years, otherwise I would have tried to give it a try and submit a pull request. However, if someone here is inclined, it is probably a trivial fix :) Thanks for the great work, and I hope to see this soon in a new release!

### PR DESCRIPTION
**Pull request by jabacz-dev**
I created a patch to allow IPv6 updates.

Basically, it's just a second name with "... (v6)" to indicate "use IPv6" flag should be triggered.
Then the ipv6 address from tracked interface will be used in POST data instead of ipv4.
Luckily the google domains API does not differenciate between v4/v6 address format and `:` is an _allowed unescaped_ character in url query strings by [RFC3986](https://tools.ietf.org/html/rfc3986#appendix-A)

**Attention**
As I have no google domains account, I could not confirm the successful update by myself.
But XDebug trace to a configured dummy domain is looking fine.

**Usage/testing**
- configure the new "Google Domains (v6)" profile additionally to your exisiting ipv4 based one.
- Both ipv4 and ipv6 addresses on tracked interface will get updated, but  _independent_ from each other.

### CODE REVIEW

**Comment by fichtner** [comment]
Unfortunately I can't merge this without testing. Making such changes to plug it in is quite easy, but if we ship and get bug reports that won't look so well.

**Comment by jabacz-dev** [comment]
Ok I got feedback from @remote-deploy who opened the issue #1691, he tested with google domains and it looks ok.
Would it be sufficient to merging if he confirms it is working?

**Comment by jabacz-dev** [comment]
@fichtner: can you please look again into merging this PR, it was tested ok as described in #1691

**Comment by Starkstromkonsument** [comment]
Hi, please take a look at https://github.com/opnsense/plugins/issues/1611#issuecomment-706129596 and #2053. As you are also interested in contributing to the dyndns-plugin, would you like to help? Please join the discussion at #1611 if you are interested. Thank you.

**Comment by jabacz-dev** [comment]
Hi *,

apparently something went wrong with the branch updates on my fork. It should have been a simple rebase of my commit on top of current master. I am sorry for upcoming confusion, feel free to delete pull request / branch / issue to tidy up.

The original fix is very small, only couple lines in 3 files for those still interested.
Look here: https://github.com/jabacz-dev/plugins/commit/803ee023da4936fb3c2d26d0c3a857e418daedd8

**Pull request closed without merging**
