### PR TITLE
dns/bind: update template paths to 9.18

### PR DESCRIPTION
**Pull request by sestary**
The package update in https://github.com/opnsense/plugins/pull/3192 did not update new version's changes to the configuration file path changes:

9.16 - https://cgit.freebsd.org/ports/tree/dns/bind916/pkg-plist
9.18 - https://cgit.freebsd.org/ports/tree/dns/bind918/pkg-plist

TLDR: /usr/local/etc/named/master is now /usr/local/etc/named/primary and /usr/local/etc/named/slave is now /usr/local/etc/named/secondary

### CODE REVIEW

**Comment by sestary** [comment]
I did not increase the version number in the `Makefile` since I wasn't sure if that was needed in this case.

**Comment by mimugmail** [comment]
Is this really necessary when using a fixed path or do you encounter an error when running the devel version

**Comment by sestary** [comment]
I was working on fixing another issue, and the devel version wouldn't run specifically because these files are no longer in the right place:

```
zone "localhost"        { type master; file "/usr/local/etc/namedb/primary/localhost-forward.db"; };
zone "127.in-addr.arpa" { type master; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };
zone "0.ip6.arpa"       { type master; file "/usr/local/etc/namedb/primary/localhost-reverse.db"; };
```

**Comment by fichtner** [comment]
Agree here with moving all. The only issue I see here is that eventually GUI should also follow the official bind nomenclature, which is tricky because it is also used in JavaScript and could subtly break while doing it. For now this PR is best...

**Review by mimugmail — APPROVED** [review]
Ok, thx :) But please let it in devel for next release

**Comment by sestary** [comment]
> Agree here with moving all. The only issue I see here is that eventually GUI should also follow the official bind nomenclature, which is tricky because it is also used in JavaScript and could subtly break while doing it. For now this PR is best...

I can take a stab at that in another PR in the next few days, the next release will be in January I'm assuming? I am using almost every feature in this plugin at this point so would be relatively easy for me to test.

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by fichtner** [comment]
This is also in the API endpoint URLs. We can switch those for a major release, but as I said it's not unlikely we will miss something doing so. 23.1 is not that far away, but it should be attempted for sure if @mimugmail agrees.


Cheers,
Franco

**Comment by sestary** [comment]
We definitely need to update the API endpoint in `acme-client`: https://github.com/opnsense/plugins/issues/3103

**Pull request merged**
