### PR TITLE
net/quagga: add a firewall rule for unicast traffic

### PR DESCRIPTION
**Pull request by fabianfrz**
part of #346
Waiting for feedback of the Ticket author.

### CODE REVIEW

**Comment by fabianfrz** [comment]
@fichtner can I merge this as I don't want a stale PR when switching the backend?

**Comment by fabianfrz** [comment]
@fichtner now I will adjust the files for FRR

**Comment by fichtner** [comment]
can you make a copy so we can cleanly discontinue quagga plugin?

**Comment by fabianfrz** [comment]
@fichtner I would prefer making an empty os-quagga package with an os-frr dependency

**Comment by fichtner** [comment]
no just a os-frr people can flip / install on their own

the models stay the same so it's just that maintenance effort of installing the other plugin

**Comment by fichtner** [comment]
(And I believe os-quagga will auto-deinstall if os-frr is used)

**Comment by fabianfrz** [comment]
We should also think about the conflict of the stale quagga package which conflicts with frr. This is why I plan this change to the end of the release.

**Comment by fichtner** [comment]
see my last comment, I think this works automatically if people install os-frr plugin (because they need to as going to be stated in the release notes)

**Pull request merged**
