### PR TITLE
Updated lists

### PR DESCRIPTION
**Pull request by marcushoff**
Updated hbbtv->smarttv list, since its name changed by maintainer.
Removed RansomWare Tracker, since it's no longer maintained nor accesible.
Updated dnsbl.sh accordingly.
---
This is my first pull request here, sorry if I did it wrong.

### CODE REVIEW

**Comment by fichtner** [comment]
@marcushoff can we have #1712 merged into this one PR ?

**Comment by marcushoff** [comment]
Sure, I just wasn't sure how to make that in one PR

**Comment by fichtner** [comment]
@marcushoff you can add more changes to the same patch-2 branch :)

**Comment by marcushoff** [comment]
got it, I'll try that next time :)

**Comment by fichtner** [comment]
For the sake of review and clarity I have to insist on asking you to merge the two PRs...

**Comment by marcushoff** [comment]
Created new PR #1716

**Pull request closed without merging**
