### PR TITLE
security/clamav: migrate to syslog-ng

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi
ref. https://forum.opnsense.org/index.php?topic=31198.0
maybe it makes sense to switch to using syslog? )
from
clamav
to
clamav2
verbose logging option added, just in case
thanks!

### CODE REVIEW

**Review by mimugmail — APPROVED** [review]
Lovely, thx :)

**Comment by kulikov-a** [comment]
Thanks!)

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by kulikov-a** [comment]
Thanks again!
It was fast)

**Pull request merged**
