### PR TITLE
sysutils/nut: rename services

### PR DESCRIPTION
**Pull request by mimugmail**
... for better readability. Also seems you patches to nut.inc works. No idea why it didn't last time, perhaps I had my own repo used.

### CODE REVIEW

**Comment by fichtner** [comment]
Hmmm, I don't necessarily agree here. It would be more straightforward to use the binary's names as is. What readability do you mean exactly?

**Comment by mimugmail** [comment]
Services overview in the dashboard. upsmon and nut are easy to see when you have multiple plugins installed

**Comment by fichtner** [comment]
Ok fine :)

**Comment by fichtner** [comment]
Thanks!

**Pull request merged**
