### PR TITLE
security/acme-client: fix support for the OPNsense BIND plugin

### PR DESCRIPTION
**Pull request by n35k3nd1r**
Solution for problems while detecting the root zone.

I have three zones in Bind. 
API Call "/domain/get" return this:

`{"domain":{"domains":{"domain":{"ed754b55-364b-4c65-abb5-142ba284c78b":{"enabled":"1","type":{"master":{"value":"master","selected":1},"slave":{"value":"slave","selected":0}},"masterip":"","allownotifyslave":{"":{"value":"","selected":1}},"domainname":"zone1.de","allowtransfer":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":0},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"hetznerDNS","selected":1},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":0}},"allowquery":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":1},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"hetznerDNS","selected":0},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":0}},"serial":"2003082203","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"alexander.plate@gmx.de","dnsserver":"ns1.zone1.de"},"4718a57b-ea2f-4d1e-bb83-ce84e51c8fce":{"enabled":"1","type":{"master":{"value":"master","selected":1},"slave":{"value":"slave","selected":0}},"masterip":"","allownotifyslave":{"":{"value":"","selected":1}},"domainname":"zone1.arpa","allowtransfer":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":0},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"hetznerDNS","selected":0},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":0}},"allowquery":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":0},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"hetznerDNS","selected":0},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":1}},"serial":"2003312244","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"admin@mail.zone1.arpa","dnsserver":"ns1.zone1.de"},"dae3ad43-7485-41be-8971-ac72f9a81dd9":{"enabled":"1","type":{"master":{"value":"master","selected":1},"slave":{"value":"slave","selected":0}},"masterip":"","allownotifyslave":{"":{"value":"","selected":1}},"domainname":"zone2.de","allowtransfer":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":0},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"DNS","selected":1},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":0}},"allowquery":{"":{"value":"none","selected":0},"6aa8c879-843a-44b3-9b79-aaea62fd8fe2":{"value":"global","selected":1},"ef5965c3-df4a-41ef-8f41-f0fb7d0770aa":{"value":"DNS","selected":0},"772ac5ad-7b98-4524-be4e-0f7d9a4094b6":{"value":"local","selected":0}},"serial":"2003312243","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"Alexander.plate@gmx.de","dnsserver":"ns1.zone1.de"}}}}}`
From this the original function cannot detect a root domain.

The new API Call '/domain/searchDomain' return this:
`{"rows":[{"uuid":"4718a57b-ea2f-4d1e-bb83-ce84e51c8fce","enabled":"1","type":"master","masterip":"","domainname":"zone1.arpa","allowtransfer":"","allowquery":"local","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"admin@mail.zone1.arpa","dnsserver":"ns1.asrex.de"},{"uuid":"dae3ad43-7485-41be-8971-ac72f9a81dd9","enabled":"1","type":"master","masterip":"","domainname":"zone2.de","allowtransfer":"DNS","allowquery":"global","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"Alexander.plate@gmx.de","dnsserver":"ns1.zone2.de"},{"uuid":"ed754b55-364b-4c65-abb5-142ba284c78b","enabled":"1","type":"master","masterip":"","domainname":"zone1.de","allowtransfer":"DNS","allowquery":"global","ttl":"86400","refresh":"21600","retry":"3600","expire":"3542400","negative":"3600","mailadmin":"alexander.plate@gmx.de","dnsserver":"ns1.zone1.de"}],"rowCount":3,"total":3,"current":1}`
Here the new function can easily detect the root domain.
This requires that enabled is set to 1 and type is master on this zone.

### CODE REVIEW

**Comment by fraenki** [comment]
I haven't used the API of os-bind yet, so a review of @mimugmail would be much appreciated :)

**Comment by mimugmail** [comment]
@fraenki the code in Acme for BIND plugin is also not from me, I don't use this feature. Technically get and searchDomain should give all values back, but I cannot verify if existing function fails

**Comment by fraenki** [comment]
OK, I'll look into this.

We should probably submit the fix upstream to acme.sh once it's verified and working:
https://github.com/acmesh-official/acme.sh/blob/dev/dnsapi/dns_opnsense.sh

Having a copy of this file in the "plugins" repo was always meant as a temporary solution until acme.sh adds it to their repo (IIRC).

**Comment by n35k3nd1r** [comment]
@fraenki the main difference between the two functions is the output of the zones.
get gives too much back in my opinion and is too much clustered for the function.
searchDomain returns every zone in curly brackets and no more curly brackets are inside, so we can easy make lines from the output and search for the right line

**Comment by fraenki** [comment]
I've compare both versions of the dnsapi file:

https://github.com/acmesh-official/acme.sh/blob/dev/dnsapi/dns_opnsense.sh
https://github.com/opnsense/plugins/blob/master/security/acme-client/src/opnsense/scripts/OPNsense/AcmeClient/dns_opnsense.sh

The version that is included with acme.sh has received several bugfixes and is superior to our copy, making our copy obsolete.

So I suggest the following:
- I will remove our copy of `dns_opnsense.sh` and the symlink in the next release, so we will use the superior upstream version
- @n35k3nd1r Could you please submit your fix to [acme.sh](https://github.com/acmesh-official/acme.sh/pulls) by opening a pull request against their version? This would benefit everyone. :)

Does this sound acceptable?

**Comment by n35k3nd1r** [comment]
Yes this is a very good idea! 
I think I will test the function again after the next release and see if the fix is still necessary. 
The latest file also contains changes in this area.

**Pull request closed without merging**
