### PR TITLE
WOL widget fix

### PR DESCRIPTION
**Pull request by kulikov-a**
Hi!
fix button binding after cutting scripts from widgets
ref. https://forum.opnsense.org/index.php?topic=22202.0
closes https://github.com/opnsense/plugins/issues/2285
Thanks!

### CODE REVIEW

**Comment by fichtner** [comment]
Neat, thanks a lot. Can you bump the version of the widget and remove the revision line from Makefile?

**Comment by kulikov-a** [comment]
@fichtner thanks!!

**Comment by fichtner** [comment]
Merged, thanks! ❤️ 

I invited you into GitHub org, mainly to make issue assignment possible. We really appreciate your help. 😊

**Comment by kulikov-a** [comment]
THANKS!! I'm very flattered)

**Pull request merged**
