### PR TITLE
net/ndproxy: Add ndproxy count

### PR DESCRIPTION
**Pull request by Monviech**
While troubleshooting I hammered `sysctl net.inet6.ndproxycount` in the shell relentlessly.

It is the only number that shows your configuration is correct and that something indeed happens. Having it exposed in the GUI is valuable.

image

### CODE REVIEW

**Comment by fichtner** [comment]
I don't like this for multiple reasons: we have a generic script for sysctls, it really doesn't add enough value to be shown here and it overcomplicates the configuration page. My person feeling is to leave this out.

**Comment by Monviech** [comment]
I'm okay with this. Thanks for your honest opinion. :)

**Comment by fichtner** [comment]
The backend (configd action)

**Comment by Monviech** [comment]
Ah okay thanks totally missed that. At least I learned something from this. :)

```
configctl system sysctl values net.inet6.ndproxycount
{"net.inet6.ndproxycount":"0"}
```

**Comment by fichtner** [comment]
Yep that’s the one. 👍

if there were more precise sysctls I would agree with the suggestion though. Thanks for the proposal in any case 😊

**Pull request closed without merging**
