### PR TITLE
[net/freeradius] Add attribute enabled check in config files

### PR DESCRIPTION
**Pull request by reza-ebrahimi**
Fix for issue #878

### CODE REVIEW

**Comment by mimugmail** [comment]
I got this when installing your repo:

`Sep 30 07:51:57 OPNsense configd.py: [8c031ed8-fc46-4cd0-94b5-f712b6490956] Inline action failed with OPNsense/Freeradius OPNsense/Freeradius/dictionary 'user_list' is undefined at Traceback (most recent call last):   File "/usr/local/opnsense/service/modules/processhandler.py", line 509, in execute     return ph_inline_actions.execute(self, inline_act_parameters)   File "/usr/local/opnsense/service/modules/ph_inline_actions.py", line 51, in execute     filenames = tmpl.generate(parameters)   File "/usr/local/opnsense/service/modules/template.py", line 332, in generate     raise render_exception Exception: OPNsense/Freeradius OPNsense/Freeradius/dictionary 'user_list' is undefined`


Please check on your side ...

**Comment by reza-ebrahimi** [comment]
@mimugmail Thanks, fixed

**Comment by mimugmail** [comment]
@fichtner this can be merged now ..

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
