### PR TITLE
mail/fetchmail: fix fetchmailrc permissions

### PR DESCRIPTION
**Pull request by mimugmail**
and move to stable ...

### CODE REVIEW

**Comment by fichtner** [comment]
Merged, thanks!

**Comment by mimugmail** [comment]
Why did this take so long?? 🥇

**Comment by fichtner** [comment]
sorry, growing old :D

**Comment by mr44er** [comment]
`


2021-09-12T17:04:40 | configd.py[41345] | [882a4bc5-f7c7-4326-93a0-1ee3dbc07184]  Script action stderr returned "b'File /usr/local/etc/fetchmailrc must  have no more than -rwx------ (0700) permissions.\nFile  /usr/local/etc/fetchmailrc must have no more than -rwx------ (0700)  permissions.'"
-- | -- | --


`

...but permissions are right:

`
-rwx------   1 fetchmail        fetchmail            155 Sep 12 17:04 fetchmailrc
-rw-------   1 fetchmail        fetchmail            107 Sep  6 04:28 fetchmailrc.sample
`

`poll imap.gmail.com protocol imap username "xxx@gmail.com" password "xxxpw" is xxx@mylocalpostfixdomain smtphost localhost`

gmailsettingforpop3




Trying to use the plugin for the first time. No idea right now, no mails. :D

**Comment by mimugmail** [comment]
Please open a new issue to discuss :)

**Comment by mr44er** [comment]
Aight, will do :)

**Pull request merged**
