### PR TITLE
[WIP] added a backend to access unbound diagnostics via the API

### PR DESCRIPTION
**Pull request by fabianfrz**
it has currently **NO** GUI support

### CODE REVIEW

**Comment by fichtner** [comment]
Just quickly for today: shouldn't this be in the core? I know you like ruby but if that's the reason it's not we should maybe switch to python still :)

**Comment by fabianfrz** [comment]
@fichtner yes, you said **no `ruby` in `core`** around two years ago ;)

**Comment by fichtner** [comment]
this is still true, we need to reduce the size of the images. but if you agree let's redo this in python. is there more scripting coming? what's the scope of this diagnostics tool?

**Comment by fabianfrz** [comment]
@fichtner I wrap the `unbound-control` tool to the API, so the data like statistics can be queried via it.
The results are converted to json so they may be displayed on the GUI too. This is useful to generate charts, debug issues like described in the forum (MS diagnostics data) etc. It is for general cli less unbound debugging.

**Comment by fichtner** [comment]
so you don't foresee a lot of code needed in this wrapper? processing, storing, writing synchronously into e.g. a database?

**Comment by fichtner** [comment]
*asynchronously

**Comment by fabianfrz** [comment]
the wrapper only allows to access data from unbound, the is no persistence as it does not access any configuration file. I am not sure if it would make sense to allow to dynamically add zones as this should be done by using the unbound configuration pages.

**Comment by fichtner** [comment]
ok, would you mind taking this to the core instead then, currently with the ruby script but without the dependency and then I can rebuild the script in python? it would also allow to simplify/align unbound code, also making room for unbound configd commands like start and stop.

**Comment by fabianfrz** [comment]
@fichtner should not it be finished before?

**Comment by fichtner** [comment]
opnsense-devel is for all work in progress :)

**Comment by fichtner** [comment]
just want to avoid landing this in plugins when it then moves over...

**Comment by fabianfrz** [comment]
@fichtner ok

**Comment by fabianfrz** [comment]
@fichtner should we rename it to unbound then?

**Comment by fichtner** [comment]
Yes, in core.git master some Unbound directories already exist for scripts and models.

**Comment by fabianfrz** [comment]
@fichtner moved to core#1504 on core

**Pull request closed without merging**
