### PR TITLE
Posfix: enable smtpd_sasl_auth when permit_sasl_authenticated is sele…

### PR DESCRIPTION
**Pull request by fhloston**
…cted

### CODE REVIEW

**Comment by mimugmail** [comment]
How do you handle user management with using sasl? CLI?

**Comment by fhloston** [comment]
> How do you handle user management with using sasl? CLI?

yes. 

`saslpasswd2 -c -u <domain> <user>`

**Comment by fhloston** [comment]
os-postfix in 20.7.1 does not know smtpd_sasl_auth_enable anymore:

`postconf: warning: /usr/local/etc/postfix/main.cf: unused parameter: smtpd_sasl_auth_enabled=yes`

`opnsense-revert -r 20.7 os-postfix` reverts to working smtpd sasl auth

:-1:

**Comment by mimugmail** [comment]
Can you add a new if-clause near line 116 and remove it from current line?

**Comment by fhloston** [comment]
Like this?

**Review by mimugmail — APPROVED** [review]
Exactly, sorry for the delay! 
@fichtner I can do version bump after merge

**Comment by fhloston** [comment]
Does it help if I do the version bump?

**Comment by fichtner** [comment]
Merged, thanks!

**Pull request merged**
