### PR TITLE
net/frr: Add FRR profile selection (defaults directive)

### LINKED ISSUE #2124: net/frr: Allow switching between defaults "traditional" and "datacenter"
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**
Not a problem but a bit of an inconvenience. FRR currently uses the "traditional" profile which defaults to pretty conservative timers. This is probably a good idea for WAN routing, but for environments where BGP is only (or mainly) used for internal routing, they're too high. Short hiccups or outages will result in minutes of downtime, as opposed to seconds. It is possible to make FRR use more aggressive timers by switching to the datacenter profile, see http://docs.frrouting.org/en/latest/basic.html#profiles
There are a couple of other implications which i believe are defined here https://github.com/FRRouting/frr/blob/master/yang/frr-deviations-bgp-datacenter.yang.

**Describe the solution you'd like**
Add an option to switch between profiles using the `frr defaults` directive. Currently there are just two options, "traditional" and "datacenter", so it could also be made into a checkbox. "traditional" should remain the default for backwards compatibility.

**Describe alternatives you've considered**
none

**Additional context**
This feature would complement the feature to configure timers individually per neighbor. In larger environments, it could become tedious to configure them all manually. A global switch to use the datacenter profile instead would be much easier.

### PR DESCRIPTION
**Pull request by marcquark**
closes #2124

### CODE REVIEW

**Comment by mimugmail** [comment]
can you revert the last one? It will go into 1.20, I already have a PR open and we add it afterwards.

**Review by mimugmail — APPROVED** [review]
Tested the patch here, looks good :)

**Comment by fichtner** [comment]
Merge now, fix changelog later?

**Comment by mimugmail** [comment]
Yes, last commit should go into 1.20 section recently merged. Thx

**Comment by fichtner** [comment]
Merged, thanks ❤️

**Pull request merged**
