### PR TITLE
Theme/Tukan - color redesign

### PR DESCRIPTION
**Pull request by opnsenseuser**
Theme/Tukan - redesign
as requested - cross-out/strikeout text in the row for disabled rules/nat (see screenshot)
https://forum.opnsense.org/index.php?topic=21634.15

### CODE REVIEW

**Comment by opnsenseuser** [comment]
grafik

grafik

grafik

grafik

grafik

**Comment by opnsenseuser** [comment]
@fichtner I'm a little disappointed that you haven't merged the two theme updates for the next version.

**Comment by opnsenseuser** [comment]
I do not understand that it all sticks on you

**Comment by opnsenseuser** [comment]
can nobody support you so that you don't always have to do everything?

**Comment by AdSchellevis** [comment]
Like all other projects and businesses in the world **we** do have to divide our time. Please do not underestimate the effort it takes to engineer a project like ours on a daily basis. 

Sometimes you just have to wait for your turn, complaining that you're not on top of the priority list this time won't do much good other than annoy people.

**Comment by opnsenseuser** [comment]
@AdSchellevis I can confirm 100%. and with things like functional upgrades, this is 100% comprehensible. but when it comes to template updates, I miss the traceability of all the appreciation for the work you are doing.

**Comment by opnsenseuser** [comment]
more than screenshots, which already show that it fits and I can't invest my time for the community and your project either.

**Comment by fichtner** [comment]
The way I see it complaining wastes time but waiting doesn't. I don't really see the point in the drama here.

**Comment by fichtner** [comment]
You should review your process for "stimulation" as it causes more issues than it solves currently. I guess the disappointment goes both ways.

**Comment by opnsenseuser** [comment]
if you have more time i would like to discuss this topic, because i can't understand where the problem lies with a templete. but if i understand it, i'm 100% ready to change the way I work. I think you should always address topics, because that's the only way to improve things.

**Comment by fichtner** [comment]
It's a theme and you are constantly pushing changes to it which is perfectly fine but either you need to ask for merge explicitly when you have a state that is ready to merge or work on it further.... this PR is already at +4,024 −8,053 lines changed so it's really not reviewed in 30 seconds... For themes in general one update per release is all we can do best case so it's really not appropriate to be pushy beyond that.

**Comment by fichtner** [comment]
This IS your current release history. I really don't see your point of your work not being picked up.

```
community/21.1/21.1.1:o plugins: os-theme-cicada 1.26 (contributed by Team Rebellion)
community/21.1/21.1.1:o plugins: os-theme-vicuna 1.2 (contributed by Team Rebellion)
community/21.1/21.1.2:o plugins: os-theme-cicada 1.27 (contributed by Team Rebellion)
community/21.1/21.1.2:o plugins: os-theme-tukan 1.24 (contributed by Team Rebellion)
community/21.1/21.1.2:o plugins: os-theme-vicuna 1.3 (contributed by Team Rebellion)
```

**Comment by opnsenseuser** [comment]
I have now understood that. in the future i will finish a template completely before i upload it. But this way of working came about because I never know when the next release will come and unfortunately I also notice again and again that classes are arbitrarily created in css, which sometimes you only come across by chance. if every programmer were to access the standard opnsense classes before defining his own again, i wouldn't have to do theme updates as often. but unfortunately it doesn't matter to anyone. so i have to invest the time and pay for it again. Nobody asks me how much time I have to spend on it.

**Comment by fichtner** [comment]
Please don't unload. It's pointless. You know how to create tickets early and often to solve these issues.

The question still is: is this PR ready to merge or not? Which other PR do you want merged?

**Comment by fichtner** [comment]
Stop lying to yourself, every project has these issues and you know it :D

**Comment by fichtner** [comment]
You know all this time I spend replying is lost elsewhere, first and foremost tending to contributor PRs?

**Comment by opnsenseuser** [comment]
1. I don't understand why you feel personally attacked. I didn't blame you personally. on the contrary, I asked (see above) why everything sticks to you alone.
2. the css code is chaos and you can tell if you, like me, deal with the css classes in the course of a template that is not only white.
3. I said that if you had time we would discuss your allegations against me. You yourself decided that you wanted to discuss it now.
4. I don't get any money for my work.
5. Is opnsense not allowed to criticize?
6. I will stick to your desired specifications

**Comment by fichtner** [comment]
Thank you for your understanding.

**Comment by opnsenseuser** [comment]
👍 me and everyone else know what a great job you do. and everyone in the community knows that you have incredible know-how that I and many others would like to have. I mean that seriously.

**Comment by opnsenseuser** [comment]
PR READY

**Comment by fichtner** [comment]
Merged, thanks

**Comment by opnsenseuser** [comment]
```
root@router:~ # opnsense-patch -c plugins e7eed12d
Found local copy of e7eed12d, skipping fetch.
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From e7eed12d7b2c3fbcc71719e430a3382da6c4796f Mon Sep 17 00:00:00 2001
|From: =?UTF-8?q?Ren=C3=A9?= <34602360+opnsenseuser@users.noreply.github.com>
|Date: Wed, 10 Mar 2021 17:33:16 +0100
|Subject: [PATCH] Theme/Tukan - color redesign (#2249)
|
|---
| misc/theme-tukan/Makefile                     |     2 +-
| .../stylesheets/bootstrap-select-1.13.3.scss  |    59 +-
| .../themes/tukan/assets/stylesheets/main.scss | 11667 +++++-----------
| .../tukan/assets/stylesheets/tokenizer2.scss  |    32 +-
| .../build/css/bootstrap-select-1.13.3.css     |     2 +-
| .../tukan/build/css/jquery.bootgrid.css       |     6 +-
| .../www/themes/tukan/build/css/main.css       |   297 +-
| .../build/css/pick-a-color-1.2.3.min.css      |     4 +-
| .../www/themes/tukan/build/css/tokenize2.css  |     8 +-
| .../www/themes/tukan/build/images/caret.png   |   Bin 1219 -> 2935 bytes
| 10 files changed, 4024 insertions(+), 8053 deletions(-)
|
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss
|index 150b35e363..6d3fa13e9f 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss
--------------------------
Patching file opnsense/www/themes/tukan/assets/stylesheets/bootstrap-select-1.13.3.scss using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 11.
Hunk #2 succeeded at 19.
Hunk #3 succeeded at 39.
Hunk #4 succeeded at 62.
Hunk #5 succeeded at 79.
Hunk #6 succeeded at 118.
Hunk #7 succeeded at 133.
Hunk #8 succeeded at 170.
Hunk #9 succeeded at 194.
Hunk #10 succeeded at 212.
Hunk #11 succeeded at 261.
Hunk #12 succeeded at 289.
Hunk #13 succeeded at 305.
Hunk #14 succeeded at 320.
Hunk #15 succeeded at 331.
Hunk #16 succeeded at 338.
Hunk #17 succeeded at 345.
Hunk #18 succeeded at 370.
Hunk #19 succeeded at 381.
Hunk #20 succeeded at 390.
Hunk #21 succeeded at 405.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
|index 9319aaa62a..f99129bc81 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/main.scss
--------------------------
Patching file opnsense/www/themes/tukan/assets/stylesheets/main.scss using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 1.
Hunk #2 succeeded at 361.
Hunk #3 succeeded at 1231.
Hunk #4 succeeded at 1253.
Hunk #5 succeeded at 1807.
Hunk #6 succeeded at 1827.
Hunk #7 succeeded at 3185.
Hunk #8 succeeded at 3287.
Hunk #9 succeeded at 4534.
Hunk #10 succeeded at 5425.
Hunk #11 succeeded at 5436.
Hunk #12 succeeded at 5458.
Hunk #13 succeeded at 5469.
Hunk #14 succeeded at 5563.
Hunk #15 succeeded at 5572.
Hunk #16 succeeded at 6378.
Hunk #17 succeeded at 6526.
Hunk #18 succeeded at 6623.
Hunk #19 succeeded at 7241.
Hunk #20 succeeded at 7338.
Hunk #21 succeeded at 7437.
Hunk #22 succeeded at 8553.
Hunk #23 succeeded at 8612.
Hunk #24 succeeded at 8649.
Hunk #25 succeeded at 8659.
Hunk #26 succeeded at 8774.
Hunk #27 succeeded at 8894.
Hunk #28 succeeded at 9097.
Hunk #29 succeeded at 9171.
Hunk #30 succeeded at 9183.
Hunk #31 succeeded at 9204.
Hunk #32 succeeded at 9555.
Hunk #33 succeeded at 9563.
Hunk #34 succeeded at 9619.
Hunk #35 succeeded at 9636.
Hunk #36 succeeded at 9644.
Hunk #37 succeeded at 10214.
Hunk #38 succeeded at 10267.
Hunk #39 succeeded at 10423.
Hunk #40 succeeded at 10488.
Hunk #41 succeeded at 10500.
Hunk #42 succeeded at 10543.
Hunk #43 succeeded at 10619.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss
|index bf8dfa8901..831c175858 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss
--------------------------
Patching file opnsense/www/themes/tukan/assets/stylesheets/tokenizer2.scss using Plan A...
Reversed (or previously applied) patch detected!  Assuming -R.Hunk #1 succeeded at 7.
Hunk #2 succeeded at 43.
Hunk #3 succeeded at 51.
Hunk #4 succeeded at 88.
Hunk #5 succeeded at 129.
Hunk #6 succeeded at 136.
Hunk #7 succeeded at 148.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css
|index d8cfa48d25..01c6683218 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css
--------------------------
Patching file opnsense/www/themes/tukan/build/css/bootstrap-select-1.13.3.css using Plan A...
Hunk #1 succeeded at 25.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/jquery.bootgrid.css b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/jquery.bootgrid.css
|index 7f871447e6..3440c283d3 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/jquery.bootgrid.css
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/jquery.bootgrid.css
--------------------------
Patching file opnsense/www/themes/tukan/build/css/jquery.bootgrid.css using Plan A...
Hunk #1 succeeded at 39.
Hunk #2 succeeded at 95.
Hunk #3 succeeded at 142.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
|index df4a0ea045..f99129bc81 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/main.css
--------------------------
Patching file opnsense/www/themes/tukan/build/css/main.css using Plan A...
Hunk #1 succeeded at 1.
Hunk #2 succeeded at 27.
Hunk #3 succeeded at 68.
Hunk #4 succeeded at 77.
Hunk #5 succeeded at 91.
Hunk #6 succeeded at 211.
Hunk #7 succeeded at 925.
Hunk #8 succeeded at 997.
Hunk #9 succeeded at 1051.
Hunk #10 succeeded at 1133.
Hunk #11 succeeded at 1183.
Hunk #12 succeeded at 2040.
Hunk #13 succeeded at 2052.
Hunk #14 succeeded at 2083.
Hunk #15 succeeded at 2277.
Hunk #16 succeeded at 2302.
Hunk #17 succeeded at 2334.
Hunk #18 succeeded at 2355.
Hunk #19 succeeded at 2470.
Hunk #20 succeeded at 2893.
Hunk #21 succeeded at 2945.
Hunk #22 succeeded at 2965.
Hunk #23 succeeded at 3026.
Hunk #24 succeeded at 3167.
Hunk #25 succeeded at 3199.
Hunk #26 succeeded at 3350.
Hunk #27 succeeded at 3475.
Hunk #28 succeeded at 3562.
Hunk #29 succeeded at 3592.
Hunk #30 succeeded at 3940.
Hunk #31 succeeded at 4076.
Hunk #32 succeeded at 4094.
Hunk #33 succeeded at 4102.
Hunk #34 succeeded at 4218.
Hunk #35 succeeded at 4257.
Hunk #36 succeeded at 4399.
Hunk #37 succeeded at 4421.
Hunk #38 succeeded at 4471.
Hunk #39 succeeded at 4528.
Hunk #40 succeeded at 4687.
Hunk #41 succeeded at 5057.
Hunk #42 succeeded at 5073.
Hunk #43 succeeded at 5230.
Hunk #44 succeeded at 5498.
Hunk #45 succeeded at 5699.
Hunk #46 succeeded at 5729.
Hunk #47 succeeded at 5751.
Hunk #48 succeeded at 5798.
Hunk #49 succeeded at 5842.
Hunk #50 succeeded at 5851.
Hunk #51 succeeded at 5947.
Hunk #52 succeeded at 5960.
Hunk #53 succeeded at 5977.
Hunk #54 succeeded at 6011.
Hunk #55 succeeded at 6025.
Hunk #56 succeeded at 6090.
Hunk #57 succeeded at 6146.
Hunk #58 succeeded at 6203.
Hunk #59 succeeded at 6254.
Hunk #60 succeeded at 6268.
Hunk #61 succeeded at 6281.
Hunk #62 succeeded at 6292.
Hunk #63 succeeded at 6350.
Hunk #64 succeeded at 6363.
Hunk #65 succeeded at 6414.
Hunk #66 succeeded at 6497.
Hunk #67 succeeded at 6507.
Hunk #68 succeeded at 6517.
Hunk #69 succeeded at 6526.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/pick-a-color-1.2.3.min.css b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/pick-a-color-1.2.3.min.css
|index 0606f04c53..4cfbe3d1f4 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/pick-a-color-1.2.3.min.css
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/pick-a-color-1.2.3.min.css
--------------------------
Patching file opnsense/www/themes/tukan/build/css/pick-a-color-1.2.3.min.css using Plan A...
Hunk #1 succeeded at 22.
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/tokenize2.css b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/tokenize2.css
|index 56bd92a6d0..8feb992392 100644
|--- a/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/tokenize2.css
|+++ b/misc/theme-tukan/src/opnsense/www/themes/tukan/build/css/tokenize2.css
--------------------------
Patching file opnsense/www/themes/tukan/build/css/tokenize2.css using Plan A...
Hunk #1 succeeded at 6.
Hunk #2 succeeded at 17.
Hunk #3 succeeded at 80.
Hmm...  Ignoring the trailing garbage.
done
All patches have been applied successfully.  Have a nice day.
root@router:~ #
```

**Comment by opnsenseuser** [comment]
sorry....something did go wrong with the merging

**Comment by opnsenseuser** [comment]
@fichtner do you need the branch again to get rid of the merging problem? Do i need to upload the code again? See the errors above. regards rené

**Comment by AdSchellevis** [comment]
@opnsenseuser best make sure the master branch is in the state you would like to see it in before the next release slot. you can always build a theme package manually on your end. A proper use of opnsense-patch comes with strict management from the contributors end.

**Comment by opnsenseuser** [comment]
@AdSchellevis should i upload both themes again on github?

**Comment by opnsenseuser** [comment]
> 
> 
> @opnsenseuser best make sure the master branch is in the state you would like to see it in before the next release slot. you can always build a theme package manually on your end. A proper use of opnsense-patch comes with strict management from the contributors end.

**Comment by opnsenseuser** [comment]
> 
> 
> @opnsenseuser best make sure the master branch is in the state you would like to see it in before the next release slot. you can always build a theme package manually on your end. A proper use of opnsense-patch comes with strict management from the contributors end.

whatever went wrong here. I can not understand. I also noticed the white space and never got an error message. and always uploaded to the right branch. in between always synced with the "master". Whatever the problem, I can re-upload both themes. should I do that?

**Pull request merged**
