### PR TITLE
misc/theme-cicada: Unify scrollbar colors to theme.

### PR DESCRIPTION
**Pull request by ArtistsTechGuy**
The scrollbar was showing up as a solid light colored bar which didn't actually show your position within the page.

* Change scrollbar to dark colors from within the theme.
* Remove arbitrary gap at top of scrollbar.
* On hover highlight as opnsense orange.

Please let me know if there is anything I missed about making a contribution,  I'm open to all corrections/suggestions.

### CODE REVIEW

**Comment by opnsenseuser** [comment]
@ArtistsTechGuy nice idea. Unfortunately, this does not work in all browsers. the only possibility to modify the scrollbar in all browsers is to program it with javascript. but that costs resources.

**Comment by opnsenseuser** [comment]
i made a few browser screenshots to see, that ::-webkit-scrollbar works only in chrome. no ie and no firefox support and no mobile support. 
As i said, you need javascript to fix this in all browsers.

Firefox:
firefox

IE11:
ie11

Chrome:
chrome

**Comment by fabianfrz** [comment]
@opnsenseuser there is support for firefox too but it seems to be not working on Linux:
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color

grafik

**Comment by opnsenseuser** [comment]
@fabianfrz after i have already programmed many web pages and i already had the problem most of the time i know that the only 100% way is to program it with javascript.

**Comment by opnsenseuser** [comment]
something like that:
https://github.com/buzinas/simple-scrollbar

**Comment by opnsenseuser** [comment]
@fichtner @fabianfrz 
should i implement this for one of the future opnsense versions (javascript solution) or not?

**Comment by opnsenseuser** [comment]
@fabianfrz So then we have a solution for Firefox and Chrome for Windows and Linux. 
Is that correct? Is that enough ?

**Comment by fabianfrz** [comment]
@opnsenseuser probably yes since Edge will be based on chomium in the future.

**Comment by fabianfrz** [comment]
you can also define it to all elements if you like by using another CSS selector (for example body for the body element), so you don't have to inject css classes everywhere. Afaik there are only two places where scroll bars are used: body and the left side bar (maybe also some widgets).

**Comment by opnsenseuser** [comment]
there are a few classes. to name a few:

**Comment by opnsenseuser** [comment]
@ArtistsTechGuy 
@fabianfrz 
@fichtner 
did a new request with all your modifications too
see -> https://github.com/opnsense/plugins/pull/1132

**Comment by opnsenseuser** [comment]
@ArtistsTechGuy your changes are merged -> thx very very much for your support!!

**Comment by ArtistsTechGuy** [comment]
Wow you guys work fast!  I had a super busy couple weeks and finally remembered I made this pull request, came back and all the work was done.  Glad I could be a little help to this great project and will try to contribute in the future as well.

Closing pull request.

**Comment by opnsenseuser** [comment]
👍

**Pull request closed without merging**
