### PR TITLE
net/haproxy: Release 3.10

### PR DESCRIPTION
**Pull request by fraenki**
See plugin changelog for details.

**NOTE: This release is intended for OPNsense 22.1, it should NOT be merged to previous releases due to the possibility of breaking changes.**

### CODE REVIEW

**Comment by fraenki** [comment]
@fichtner This PR should be merged for OPNsense 22.1, but not for 21.7.x. How should we proceed? Should I merge it to master now, or do you want to merge it in-time for final 22.1 builds?

**Comment by fichtner** [comment]
Merge to master and I will either merge without haproxy dependency switch for 21.7.8 or leave it out or you make a separate PR for it? I just think of some big fixes apply for 21.7.8 they should probably be added there?

**Comment by fichtner** [comment]
In any case 22.1-RC2 is going to be released without this for the time being.

**Comment by fraenki** [comment]
@fichtner These changes are solely for HAProxy 2.4, they may be considered harmful for HAProxy 2.2 setups. So I'd like to not include this in 21.7.8 (or any other 21.7 release), but only in 22.1. I'll merge it to master as suggested. :)

**Comment by fichtner** [comment]
ok moved to stable/22.1 via e647470076

**Pull request merged**
