### PR TITLE
net/wireguard - add option to enable verbose logging

### PR DESCRIPTION
**Pull request by pmhausen**
While debugging a production WireGuard setup I found myself repeatedly enabling verbose logging in `/etc/rc.conf.d/wireguard`. So let's add that to the UI, now shall we? ;)

Kind regards,
Patrick

### CODE REVIEW

**Comment by pmhausen** [comment]
So what do you think about my lastest commits?

**Comment by mimugmail** [comment]
Totally fine with it, but it needs upstream changes, so WE wait for it?

**Comment by pmhausen** [comment]
I already submitted a pull request for our own port. That's why I asked. It will need some watching of where upstream is going with respect to the kernel module, because it only works with the wireguard-go implementation. So I think it's best to keep it local and re-evaluate after we switch to FreeBSD 13 ...

**Comment by pmhausen** [comment]
If you don't feel like integrating this just yet, I can close the pull request, of course.

I run some "pure FreeBSD" WireGuard instances too and will have an eye on the kernel module implementation and upstream improvements, anyway. No problem re-visiting our module when the kernel module has become the standard.

**Comment by pmhausen** [comment]
If you don't feel like integrating this just yet, I can close the pull request, of course.

I run some "pure FreeBSD" WireGuard instances too and will have an eye on the kernel module implementation and upstream improvements, anyway. No problem re-visiting our module when the kernel module has become the standard.

**Comment by pmhausen** [comment]
https://github.com/opnsense/ports/pull/135#issuecomment-966589467

**Pull request closed without merging**
