### PR TITLE
Maltrail: Integrate fail2ban IP-list with firewall aliases

### PR DESCRIPTION
**Pull request by jkellerer**
Maltrail from version 0.21.19, offers an IP list that is assembled from detected src IPs matching a regular expression.

This PR includes this regular expression in `maltrail.conf` using the default value proposed by the Maltrail project. 
Further it adds an option to the server form to auto generate an alias that periodically loads the IP list from the local Maltrail server endpoint.

Note: This is a first attempt to make the feature usable. It may make sense to also allow to configure the REGEX, but this may come in another PR.

### CODE REVIEW

**Comment by MikhailKasimov** [comment]
Hello!

As I can see, ```FAIL2BAN_REGEX``` default option is a little bit wider: https://github.com/stamparm/maltrail/blob/master/maltrail.conf#L48 . Perhaps, should be updated for current pull-request too?

**Comment by jkellerer** [comment]
@MikhailKasimov, thanks for the hint. Adding scanners and spammers makes sense.

**Comment by jkellerer** [comment]
Hi @mimugmail , is this addition acceptable and would you mind reviewing it?

**Review by mimugmail — APPROVED** [review]
I added your code to my machine and it works really nice. Love the addition. Would you mind bumping the version and adding changelog. @fichtner is the php code ok for you?

**Comment by jkellerer** [comment]
Changelog added and version incremented to 1.8

**Comment by Technikte** [comment]
Any chance to get this merged ? It seems ready or..

**Pull request merged**
