### PR TITLE
Add URL of Antivirus service to help text

### PR DESCRIPTION
**Pull request by abraxxa**
I had a hard time finding out the correct URL for the Squid config, this should help others to get this working.

### CODE REVIEW

**Comment by mimugmail** [comment]
The link is documented? :)

https://docs.opnsense.org/manual/how-tos/proxyicapantivirusinternal.html

It would be better to change the default within Web Proxy, but I thought this was already done ..

**Comment by fichtner** [comment]
It was https://github.com/opnsense/core/commit/0e581c8c7, but it won't be an effective default until we release new images based on 17.7.5.

We have always tried to avoid adding URLs to translatable help text, it ends up as typos in other languages and bounces the translations unnecessarily.

I would prefer to keep this out of the code and suggest adding it to the doc, but since that is already done is it ok to not merge this?

**Comment by abraxxa** [comment]
Interesting, as this is a different url than what I've found in the c-icap config file and used: icap://localhost:1344/srv_clamav.
I wasn't sure what the correct place for it is, change at will.

**Comment by fichtner** [comment]
It's the same, but in your case IPv4 using pseudo DNS :) I think the rationale for ::1 was IPv6 is here to stay and squid does not start without IPv6 support anyway. Closing then, thanks for the pointer in any case.

**Comment by abraxxa** [comment]
I was referring to the url endpoint not the hostname. I chose localhost because c-icap was configured to listen on ::1 by default but Squid for icap://127.0.0.1/endpoint.

**Comment by mimugmail** [comment]
https://github.com/opnsense/plugins/blob/master/www/c-icap/src/opnsense/service/templates/OPNsense/CICAP/virus_scan.conf#L2-L3

Endpoint is `antivirus_module` and for compatibility reasons there are two aliases `srv_clamav` and `virus_scan`

**Comment by abraxxa** [comment]
Should we then use ‚antivirus_module‘ for the docs?

**Comment by mimugmail** [comment]
No, we'll keep `virus_scan` .. it's a well known value :)

**Pull request closed without merging**
